const MODULE_STATUSES = {
  READY_TO_PACKAGE: 'ready_to_package',
  NEEDS_MODULE_MANIFEST: 'needs_module_manifest',
  NEEDS_DEPENDENCY_MAPPING: 'needs_dependency_mapping',
  NEEDS_INSTALL_HOOKS: 'needs_install_hooks',
  NEEDS_LICENSE_GATE: 'needs_license_gate',
  NEEDS_MARKETPLACE_LISTING: 'needs_marketplace_listing',
  NEEDS_WHITE_LABEL_RULES: 'needs_white_label_rules',
  BLOCKED: 'blocked',
  FUTURE_MODULE: 'future_module',
}

const MODULE_MAP = [
  {
    moduleId: 'smokecraft-experience',
    moduleName: 'SmokeCraft Experience Module',
    moduleType: 'experience',
    coreOrAddon: 'core',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['passport-connections', 'venue-onboarding'],
    requiredRoutes: ['/smokecraft', '/passport', '/connections'],
    requiredServices: ['smokecraftJourney', 'passportProgress', 'passportEntry'],
    requiredComponents: ['SmokeCraftAssetScreen', 'SmokeCraftHotspotLayer', 'SmokeCraftAssetRoute'],
    requiredDocs: ['docs/PHASE_13B_DRAGDROP_ACTIVATION.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 2 — SmokeCraft Experience Module',
  },
  {
    moduleId: 'pos360',
    moduleName: 'POS360 Module',
    moduleType: 'pos',
    coreOrAddon: 'core',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['venue-onboarding', 'checkout', 'inventory-ispae'],
    requiredRoutes: ['/pos360', '/api/pos360'],
    requiredServices: ['pos360ExternalOpsStatusService', 'loccExternalOpsBridgeService'],
    requiredComponents: ['POS360'],
    requiredDocs: ['docs/POS360_ENGINE.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 3 — POS360 Module',
  },
  {
    moduleId: 'eat-command-hub',
    moduleName: 'E.A.T. Command Hub Module',
    moduleType: 'command_hub',
    coreOrAddon: 'core',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['pos360', 'inventory-ispae', 'locc'],
    requiredRoutes: ['/eat', '/api/eat'],
    requiredServices: ['eatCommandHubContract'],
    requiredComponents: ['EATCommandHub'],
    requiredDocs: ['docs/EAT_COMMAND_HUB.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 4 — E.A.T. Command Hub Module',
  },
  {
    moduleId: 'inventory-ispae',
    moduleName: 'Inventory Availability Module (ISPAE)',
    moduleType: 'inventory',
    coreOrAddon: 'core',
    premiumEligible: false,
    enterpriseEligible: true,
    dependencies: ['venue-onboarding', 'database'],
    requiredRoutes: ['/api/inventory'],
    requiredServices: ['inventoryAvailabilityEngine', 'inventoryExternalOpsBridgeService'],
    requiredComponents: [],
    requiredDocs: ['docs/INVENTORY_AVAILABILITY_ENGINE.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 5 — Inventory Availability Module / ISPAE',
  },
  {
    moduleId: 'reorder-dmrc',
    moduleName: 'Reorder Connector Add-On Module (DMRC)',
    moduleType: 'reorder',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['inventory-ispae', 'vendor-partner', 'eocg'],
    requiredRoutes: ['/api/reorder'],
    requiredServices: ['reorderConnectorService', 'purchaseOrderSubmissionGateway', 'reorderExternalSubmissionBridgeService'],
    requiredComponents: [],
    requiredDocs: ['docs/REORDER_CONNECTORS.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created', 'vendor_credentials_required_for_live'],
    nextBuildPrompt: 'Module Build 6 — Reorder Connector Add-On Module / DMRC',
  },
  {
    moduleId: 'locc',
    moduleName: 'Live Operations Command Center Module (LOCC)',
    moduleType: 'operations',
    coreOrAddon: 'core',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['inventory-ispae', 'reorder-dmrc', 'eprl'],
    requiredRoutes: ['/api/locc'],
    requiredServices: ['loccDashboardService', 'roleSafetyGateway', 'loccExternalOpsBridgeService'],
    requiredComponents: ['LOCCDashboard'],
    requiredDocs: ['docs/LIVE_OPERATIONS_COMMAND_CENTER.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 7 — Live Operations Command Center Module / LOCC',
  },
  {
    moduleId: 'eocg',
    moduleName: 'External Operations Connector Gateway Module (EOCG)',
    moduleType: 'external_ops',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['locc', 'inventory-ispae', 'reorder-dmrc'],
    requiredRoutes: ['/api/external-pos', '/api/vendor-gateway', '/api/operational-sync', '/api/live-external-ops'],
    requiredServices: ['liveExternalOperationsReadinessService', 'externalPOSConnectorGateway', 'vendorConnectorGateway', 'purchaseOrderSubmissionGateway'],
    requiredComponents: ['LiveExternalOpsReadinessPanel', 'ExternalPOSReadinessPanel', 'VendorGatewayReadinessPanel'],
    requiredDocs: ['docs/EXTERNAL_POS_VENDOR_GATEWAY_AND_LIVE_OPERATIONS.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created', 'external_credentials_required_for_live'],
    nextBuildPrompt: 'Module Build 8 — External Operations Connector Gateway Module / EOCG',
  },
  {
    moduleId: 'venue-onboarding',
    moduleName: 'Venue Onboarding Module',
    moduleType: 'onboarding',
    coreOrAddon: 'core',
    premiumEligible: false,
    enterpriseEligible: false,
    dependencies: ['database'],
    requiredRoutes: ['/api/venue'],
    requiredServices: ['venueOnboardingService'],
    requiredComponents: [],
    requiredDocs: ['docs/VENUE_ONBOARDING.md'],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 1 — NOVEE OS Module Packaging Foundation',
  },
  {
    moduleId: 'vendor-partner',
    moduleName: 'Partner Vendor Module',
    moduleType: 'vendor',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['venue-onboarding'],
    requiredRoutes: ['/api/partner-vendors'],
    requiredServices: ['partnerVendorService'],
    requiredComponents: [],
    requiredDocs: [],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 1 — NOVEE OS Module Packaging Foundation',
  },
  {
    moduleId: 'checkout',
    moduleName: 'Payment/Checkout Module',
    moduleType: 'checkout',
    coreOrAddon: 'core',
    premiumEligible: false,
    enterpriseEligible: false,
    dependencies: ['inventory-ispae', 'database', 'stripe'],
    requiredRoutes: ['/api/checkout'],
    requiredServices: ['checkoutService'],
    requiredComponents: [],
    requiredDocs: [],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created', 'stripe_credentials_required'],
    nextBuildPrompt: 'Module Build 1 — NOVEE OS Module Packaging Foundation',
  },
  {
    moduleId: 'kds',
    moduleName: 'KDS Module',
    moduleType: 'kds',
    coreOrAddon: 'core',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['pos360', 'inventory-ispae'],
    requiredRoutes: ['/api/kds'],
    requiredServices: ['kdsEngine'],
    requiredComponents: [],
    requiredDocs: [],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 1 — NOVEE OS Module Packaging Foundation',
  },
  {
    moduleId: 'ncie',
    moduleName: 'NCIE Module',
    moduleType: 'intelligence',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['inventory-ispae', 'pos360'],
    requiredRoutes: ['/api/ncie'],
    requiredServices: ['noveeOSNCIEService'],
    requiredComponents: [],
    requiredDocs: [],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 1 — NOVEE OS Module Packaging Foundation',
  },
  {
    moduleId: 'passport-connections',
    moduleName: 'Passport Connections Module',
    moduleType: 'experience',
    coreOrAddon: 'core',
    premiumEligible: false,
    enterpriseEligible: false,
    dependencies: ['venue-onboarding', 'smokecraft-experience'],
    requiredRoutes: ['/passport', '/connections'],
    requiredServices: ['passportProgress', 'passportEntry'],
    requiredComponents: [],
    requiredDocs: [],
    currentStatus: 'sealed_and_verified',
    packagingReadiness: MODULE_STATUSES.NEEDS_MODULE_MANIFEST,
    blockers: ['module_manifest_not_created'],
    nextBuildPrompt: 'Module Build 2 — SmokeCraft Experience Module',
  },
  {
    moduleId: 'white-label-licensing',
    moduleName: 'White-Label Licensing Module',
    moduleType: 'licensing',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['venue-onboarding'],
    requiredRoutes: ['/api/licensing'],
    requiredServices: ['whiteLabelLicensingReadinessService'],
    requiredComponents: ['WhiteLabelLicenseTierCard'],
    requiredDocs: ['docs/FINAL_PRODUCTION_LOCKDOWN_AND_MODULE_READINESS.md'],
    currentStatus: 'readiness_mapped',
    packagingReadiness: MODULE_STATUSES.FUTURE_MODULE,
    blockers: ['module_build_9_not_started'],
    nextBuildPrompt: 'Module Build 9 — White-Label Marketplace Licensing Module',
  },
  {
    moduleId: 'marketplace-registry',
    moduleName: 'Marketplace Registry Module',
    moduleType: 'marketplace',
    coreOrAddon: 'addon',
    premiumEligible: true,
    enterpriseEligible: true,
    dependencies: ['white-label-licensing'],
    requiredRoutes: ['/api/marketplace'],
    requiredServices: ['marketplacePackagingReadinessService'],
    requiredComponents: ['MarketplaceReadinessPanel'],
    requiredDocs: ['docs/FINAL_PRODUCTION_LOCKDOWN_AND_MODULE_READINESS.md'],
    currentStatus: 'readiness_mapped',
    packagingReadiness: MODULE_STATUSES.FUTURE_MODULE,
    blockers: ['module_build_9_not_started'],
    nextBuildPrompt: 'Module Build 9 — White-Label Marketplace Licensing Module',
  },
]

export function buildModuleReadinessMap() {
  return {
    total_modules: MODULE_MAP.length,
    core_modules: MODULE_MAP.filter(m => m.coreOrAddon === 'core').length,
    addon_modules: MODULE_MAP.filter(m => m.coreOrAddon === 'addon').length,
    premium_eligible: MODULE_MAP.filter(m => m.premiumEligible).length,
    enterprise_eligible: MODULE_MAP.filter(m => m.enterpriseEligible).length,
    modules: MODULE_MAP,
    post_phase_module_build_required: true,
    module_install_not_built_yet: true,
    readiness_mapped_only: true,
  }
}

export function getModuleReadinessById(moduleId) {
  return MODULE_MAP.find(m => m.moduleId === moduleId) || null
}

export function getCoreModules() {
  return MODULE_MAP.filter(m => m.coreOrAddon === 'core')
}

export function getAddonModules() {
  return MODULE_MAP.filter(m => m.coreOrAddon === 'addon')
}

export function getPremiumModules() {
  return MODULE_MAP.filter(m => m.premiumEligible)
}

export function getEnterpriseModules() {
  return MODULE_MAP.filter(m => m.enterpriseEligible)
}

export function getModuleDependencies(moduleId) {
  const mod = getModuleReadinessById(moduleId)
  return mod ? mod.dependencies : []
}

export function getModulePackagingBlockers(moduleId) {
  const mod = getModuleReadinessById(moduleId)
  return mod ? mod.blockers : []
}

export function buildPostPhaseModuleBuildPlan() {
  return {
    series_name: 'POST-PHASE AUDIT AND MODULE BUILD SERIES',
    note: 'These are post-phase module builds, not Phase 20.',
    sequence: [
      { step: 1, name: 'Post-Phase Final Audit Review', description: 'Review all 19 phases, verify sealed state, document any gaps.' },
      { step: 2, name: 'Module Build 1 — NOVEE OS Module Packaging Foundation', description: 'Build the module registry, manifest format, install/uninstall hooks, and license gate foundation.' },
      { step: 3, name: 'Module Build 2 — SmokeCraft Experience Module', description: 'Package SmokeCraft + Passport + Connections as a standalone licensed module.' },
      { step: 4, name: 'Module Build 3 — POS360 Module', description: 'Package POS360 as a standalone licensed module with venue activation.' },
      { step: 5, name: 'Module Build 4 — E.A.T. Command Hub Module', description: 'Package E.A.T. command hub as a module with hook registration.' },
      { step: 6, name: 'Module Build 5 — Inventory Availability Module / ISPAE', description: 'Package ISPAE as a core inventory module with live sync readiness.' },
      { step: 7, name: 'Module Build 6 — Reorder Connector Add-On Module / DMRC', description: 'Package DMRC as a premium add-on with vendor credential requirements.' },
      { step: 8, name: 'Module Build 7 — Live Operations Command Center Module / LOCC', description: 'Package LOCC as a module with role safety and approval gate.' },
      { step: 9, name: 'Module Build 8 — External Operations Connector Gateway Module / EOCG', description: 'Package EOCG as a module with live credential activation.' },
      { step: 10, name: 'Module Build 9 — White-Label Marketplace Licensing Module', description: 'Build the white-label licensing engine, reseller tiers, and marketplace registry.' },
    ],
  }
}
