/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ── Stitch Material Design 3 Color System ── */
        'background':                  '#131314',
        'surface':                     '#131314',
        'surface-dim':                 '#131314',
        'surface-bright':              '#39393a',
        'surface-container-lowest':    '#0e0e0f',
        'surface-container-low':       '#1b1b1c',
        'surface-container':           '#1f1f20',
        'surface-container-high':      '#2a2a2b',
        'surface-container-highest':   '#353436',
        'surface-variant':             '#353436',
        'surface-tint':                '#e9c176',
        'on-background':               '#e5e2e3',
        'on-surface':                  '#e5e2e3',
        'on-surface-variant':          '#d1c5b4',
        'inverse-surface':             '#e5e2e3',
        'inverse-on-surface':          '#303031',
        'primary':                     '#e9c176',
        'primary-container':           '#c5a059',
        'primary-fixed':               '#ffdea5',
        'primary-fixed-dim':           '#e9c176',
        'on-primary':                  '#412d00',
        'on-primary-container':        '#4e3700',
        'on-primary-fixed':            '#261900',
        'on-primary-fixed-variant':    '#5d4201',
        'inverse-primary':             '#775a19',
        'secondary':                   '#ffb95a',
        'secondary-container':         '#c68315',
        'secondary-fixed':             '#ffddb6',
        'secondary-fixed-dim':         '#ffb95a',
        'on-secondary':                '#462a00',
        'on-secondary-container':      '#3d2400',
        'on-secondary-fixed':          '#2a1800',
        'on-secondary-fixed-variant':  '#643f00',
        'tertiary':                    '#dac1bb',
        'tertiary-container':          '#b7a09a',
        'tertiary-fixed':              '#f7ddd6',
        'tertiary-fixed-dim':          '#dac1bb',
        'on-tertiary':                 '#3c2d28',
        'on-tertiary-container':       '#473733',
        'on-tertiary-fixed':           '#261814',
        'on-tertiary-fixed-variant':   '#54433e',
        'outline':                     '#9a8f80',
        'outline-variant':             '#4e4639',
        'error':                       '#ffb4ab',
        'error-container':             '#93000a',
        'on-error':                    '#690005',
        'on-error-container':          '#ffdad6',
        'accent-success':              '#4ade80',
      },
      fontFamily: {
        'display-lg':  ['"Playfair Display"', 'serif'],
        'headline-xl': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'body-lg':     ['Montserrat', 'sans-serif'],
        'body-md':     ['Montserrat', 'sans-serif'],
        'label-lg':    ['Montserrat', 'sans-serif'],
        'label-sm':    ['Montserrat', 'sans-serif'],
        sans:          ['Montserrat', 'sans-serif'],
        serif:         ['"Playfair Display"', 'serif'],
      },
      fontSize: {
        'display-lg':  ['64px',  { lineHeight: '72px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px',  { lineHeight: '56px',  fontWeight: '600' }],
        'headline-lg': ['32px',  { lineHeight: '40px',  fontWeight: '500' }],
        'headline-md': ['24px',  { lineHeight: '32px',  fontWeight: '500' }],
        'body-lg':     ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':     ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'label-lg':    ['14px',  { lineHeight: '20px',  letterSpacing: '0.1em',  fontWeight: '600' }],
        'label-sm':    ['12px',  { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      spacing: {
        'gutter':              '32px',
        'unit':                '8px',
        'card-padding':        '24px',
        'margin':              '64px',
        'container-max-width': '1440px',
      },
      maxWidth: {
        'container-max-width': '1440px',
      },
      boxShadow: {
        'tactile':   '0 10px 40px rgba(0, 0, 0, 0.6)',
        'glow-gold': '0 0 25px rgba(233, 193, 118, 0.25)',
      },
      keyframes: {
        'subtle-float': {
          '0%':   { transform: 'translateY(0)' },
          '50%':  { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0)' },
        },
        'shine': {
          to: { backgroundPosition: '200% center' },
        },
        'gold-pulse': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(233,193,118,0.4)' },
          '50%':     { boxShadow: '0 0 0 6px rgba(233,193,118,0)' },
        },
        'ping-gold': {
          '75%,100%': { transform: 'scale(2)', opacity: '0' },
        },
        'status-pulse': {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0.5' },
        },
      },
      animation: {
        'floating':     'subtle-float 6s ease-in-out infinite',
        'shine':        'shine 4s linear infinite',
        'gold-pulse':   'gold-pulse 2s ease-in-out infinite',
        'ping-gold':    'ping-gold 1.5s cubic-bezier(0,0,0.2,1) infinite',
        'status-pulse': 'status-pulse 2s cubic-bezier(0.4,0,0.6,1) infinite',
      },
    },
  },
  plugins: [],
}
