/**
 * SmokeCraft Required-Interaction Manifest — Discovery Package.
 *
 * The first canonical, repository-backed definition of what educational
 * interaction each of the 21 primary curriculum sessions is required to
 * contain. Built by direct source inspection of every session component
 * (src/pages/smokecraft/*.jsx), the shared completion path
 * (src/context/GuestSessionContext.jsx's `awardSessionRewards`), and the
 * server-side completion authority (server/controllers/playerStateController.js
 * `handleCompleteSession` + server/services/smokecraft/playerStateService.js
 * `completeSession`) — not guessed, not inferred from route names alone.
 *
 * REQUIRED-INTERACTION DEFINITION (this pass's canonical definition,
 * per mandate section 4): a required interaction is a meaningful player
 * action — assessment, classification, placement, matching, ordering,
 * hotspot identification, construction inspection, flavor/pairing
 * decision, or mentor-guided response — whose OUTCOME is evaluated and
 * whose correctness/completeness is verified server-side before session
 * completion and XP are granted. Reading text, watching media, opening a
 * modal, clicking Next/Complete, or moving a UI control that is never
 * evaluated server-side does NOT qualify by itself, even if it captures
 * real player input into client or server state.
 *
 * KEY ARCHITECTURAL FINDING (verified by source read, not assumed):
 * `awardSessionRewards()` / `completeSessionOnServer()` /
 * `handleCompleteSession()` together form ONE real, idempotent,
 * server-authoritative completion+XP mechanism used by EVERY one of the
 * 21 sessions — XP amounts are looked up server-side from
 * `sessionRewardTable.js` by `sessionId`, never client-supplied, so XP
 * itself cannot be spoofed or duplicated for any session. However, this
 * shared endpoint accepts only `sessionId` — it has no parameter for,
 * and therefore cannot evaluate, the player's actual interaction
 * answer/selection. So the "session completes and awards XP safely"
 * property holds universally, but the STRICTER "the required
 * interaction's correctness is what gates that completion" property
 * does NOT hold for any session that has no OTHER, dedicated,
 * answer-evaluating endpoint of its own.
 *
 * Only 3 of the 21 sessions have such a dedicated, answer-evaluating,
 * server-authoritative endpoint distinct from the generic completion
 * call: Session 11/22 (real pairing engine — scores/ranks a real
 * cigar+beverage combination) and Session 14 (real mentor-guidance
 * service — serves dynamic, guest-activity-derived content, verified
 * to honestly fall back rather than fabricate). Session 23 has a
 * dedicated GET status endpoint but no evaluated submission. The
 * remaining 17 sessions capture real player input (selections, ratings,
 * flavor-wheel taps) but store it ONLY in local `GuestSessionContext`
 * state (an already-approved non-authoritative cache elsewhere in this
 * app) — never submitted to any endpoint that validates or scores it —
 * before the same generic, interaction-agnostic completion call fires.
 */

export const INTERACTION_TYPES = Object.freeze([
  'orientation-dashboard', 'device-simulation-selection', 'content-exploration',
  'exploration-with-selection', 'construction-classification', 'technique-selection',
  'stepwise-instructional', 'tasting-rating-capture', 'flavor-wheel-selection',
  'pairing-decision-and-scoring', 'mentor-guided-response', 'topic-exploration',
  'multi-category-rating', 'rule-based-summary-review', 'status-gated-certification',
  'checklist-review', 'reward-display', 'final-recommendation-display',
])

export const GAP_CLASSIFICATIONS = Object.freeze([
  'COMPLETE_AND_VERIFIED', 'COMPLETE_BUT_UNTESTED', 'PARTIAL', 'VISUAL_ONLY',
  'WRONG_INTERACTION_TYPE', 'MISSING', 'BLOCKED', 'DUPLICATED_OR_CONFLICTING',
])

const SHARED_COMPLETION = {
  canonicalApi: 'POST /api/smokecraft/player-state/sessions/:sessionId/complete',
  canonicalService: 'server/services/smokecraft/playerStateService.js#completeSession',
  canonicalPersistence: 'smokecraft_session_completions (guest_reference, session_id unique)',
  progressionRequired: true,
  persistenceRequired: true,
}

export const REQUIRED_INTERACTIONS = Object.freeze([
  {
    sessionId: 'entry', sessionNumber: 1, phaseId: 1,
    route: '/smokecraft/welcome', title: 'Welcome to Today’s Experience',
    learningObjective: 'Orient the player to the session flow and today’s cigar/venue/mentor context.',
    requiredInteractionId: 'S1-ORIENTATION', requiredInteractionType: 'orientation-dashboard',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/WelcomeExperience.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Orientation screen — no assessment is educationally appropriate here; real dashboard content confirmed by prior captured-content audit.',
  },
  {
    sessionId: 'humidor-match', sessionNumber: 2, phaseId: 1,
    route: '/smokecraft/humidor-match', title: 'Choose Your Cigar',
    learningObjective: 'Apply humidor environment knowledge (temp/humidity/seal/airflow) to select an appropriate cigar.',
    requiredInteractionId: 'S2-HUMIDOR-SELECTION', requiredInteractionType: 'device-simulation-selection',
    completionRequired: true, scoringRequired: true, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/HumidorMatch.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/humidor-match; POST /api/smokecraft/player-state/sessions/humidor-match/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt; playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=selection_image, activity_key=humidor-match); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-c-api.mjs (39/39)', 'verify-smokecraft-required-interaction-package-c-browser.mjs (17/17)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-c/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package C: the real image-based environment selection (Virtual Humidor / Dry Box / Travel Case) is now server-evaluated — the server independently knows Virtual Humidor is the only climate-controlled, factually correct choice. An incorrect selection is recorded as a real attempt but never completes the session; every attempt is audited.',
  },
  {
    sessionId: 'meet-your-cigar', sessionNumber: 3, phaseId: 1,
    route: '/smokecraft/meet-your-cigar', title: 'Meet Your Cigar',
    learningObjective: 'Explore the selected cigar’s brand/blend/wrapper/binder/filler/factory profile.',
    requiredInteractionId: 'S3-PROFILE-EXPLORATION', requiredInteractionType: 'content-exploration',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/MeetYourCigar.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/meet-your-cigar; POST /api/smokecraft/player-state/sessions/meet-your-cigar/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt (SESSION_DEFS["meet-your-cigar"]); playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=exploration, activity_key=meet-your-cigar); smokecraft_tasting_drafts (activityKey=meet-your-cigar, checkpoint draft resume); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-d-api.mjs (34/34)', 'verify-smokecraft-required-interaction-package-d-browser.mjs (15/15)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-d/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package D: the 3 sections that ever carry real content for this fixed catalog (Brand/Blend/Wrapper — Binder/Filler/Factory/Master Blender are always "Not available") are now required, server-validated checkpoints, plus a required final synthesis (which detail most influenced the player\'s impression) before completion. A real pre-existing defect was found and fixed in this pass: smokecraftRewards.js had no entry for this session, so awardSessionRewards() silently no-op\'d and the session could never complete server-side through the real path at all, before or after prior packages.',
  },
  {
    sessionId: 'terroir', sessionNumber: 4, phaseId: 1,
    route: '/smokecraft/terroir', title: 'Terroir',
    learningObjective: 'Understand how country/region/soil/climate shape a cigar’s character.',
    requiredInteractionId: 'S4-TERROIR-EXPLORATION', requiredInteractionType: 'content-exploration',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/Terroir.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/terroir; POST /api/smokecraft/player-state/sessions/terroir/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt (SESSION_DEFS.terroir); playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=exploration, activity_key=terroir); smokecraft_tasting_drafts (activityKey=terroir, checkpoint draft resume); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-d-api.mjs (34/34)', 'verify-smokecraft-required-interaction-package-d-browser.mjs (15/15)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-d/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package D: the 5 real terroir-shaping factors (Country/Region/Soil/Climate/Growing Conditions) are now required, server-validated checkpoints, plus a required final synthesis (which factor most shapes character) before completion. Same pre-existing missing-reward-table-entry defect as Session 3 was found and fixed here too.',
  },
  {
    sessionId: 'format', sessionNumber: 5, phaseId: 1,
    route: '/smokecraft/format', title: 'Construction Inspection',
    learningObjective: 'Classify cigar shape/size (Robusto/Toro/Churchill/Corona/Gordo/Torpedo) and its effect on burn/body.',
    requiredInteractionId: 'S5-SHAPE-CLASSIFICATION', requiredInteractionType: 'construction-classification',
    completionRequired: true, scoringRequired: true, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/Format.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/format; POST /api/smokecraft/player-state/sessions/format/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt; playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=sequence, activity_key=format); smokecraft_tasting_drafts (activityKey=format, draft resume); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-c-api.mjs (39/39)', 'verify-smokecraft-required-interaction-package-c-browser.mjs (17/17)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-c/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package C: the player now sequences the 6 real shapes from shortest to longest burn time via keyboard-accessible move-earlier/move-later controls — the server independently owns and validates the correct order (derived from each shape\'s own documented burnTime range). An incorrect sequence never completes the session; every attempt is audited.',
  },
  {
    sessionId: 'cut-toast-light', sessionNumber: 6, phaseId: 1,
    route: '/smokecraft/cut-toast-light', title: 'Choose Your Cut',
    learningObjective: 'Select an appropriate cut style (Straight/V-Cut/Punch) for the chosen cigar.',
    requiredInteractionId: 'S6-CUT-SELECTION', requiredInteractionType: 'technique-selection',
    completionRequired: true, scoringRequired: true, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/CutToastLight.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/cut-toast-light; POST /api/smokecraft/player-state/sessions/cut-toast-light/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt; playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=match, activity_key=cut-toast-light); smokecraft_tasting_drafts (activityKey=cut-toast-light, draft resume); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-c-api.mjs (39/39)', 'verify-smokecraft-required-interaction-package-c-browser.mjs (17/17)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-c/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package C: the player now matches each real cut method to its real defining characteristic (condensed directly from the existing METHOD_TIPS content) via an accessible native-select matching interface — the server independently owns and validates the correct relationship map. An incorrect or incomplete matching never completes the session; every attempt is audited.',
  },
  {
    sessionId: 'lighting-tutorial', sessionNumber: 7, phaseId: 1,
    route: '/smokecraft/lighting-tutorial', title: 'Lighting Tutorial',
    learningObjective: 'Learn the correct step-by-step lighting technique.',
    requiredInteractionId: 'S7-LIGHTING-STEPS', requiredInteractionType: 'stepwise-instructional',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/LightingTutorial.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Real, substantive 8-step tutorial + Mentor Tip (strongest captured educational prose per prior audit) — an instructional-technique session; no assessment is educationally required beyond the walkthrough itself.',
  },
  {
    sessionId: 'first-third', sessionNumber: 8, phaseId: 2,
    route: '/smokecraft/first-third', title: 'First Draw',
    learningObjective: 'Capture and evaluate real tasting observations (aroma/draw/body/flavor/burn/ash) for the first third.',
    requiredInteractionId: 'S8-TASTING-CAPTURE', requiredInteractionType: 'tasting-rating-capture',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/FirstThird.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/tasting-observation/first-third; POST /api/smokecraft/player-state/sessions/first-third/complete',
    canonicalService: 'server/services/smokecraft/tastingObservationService.js#submitTastingObservation; playerStateService.js#completeSession (gated by hasTastingObservationEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=tasting_observation, activity_key=first-third)',
    testReferences: ['verify-smokecraft-required-interaction-package-a-api.mjs (26/26)', 'verify-smokecraft-required-interaction-package-a-browser.mjs (14/14)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-a/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package A: real tasting observations are now submitted server-side (submitTastingObservation) and completeSession() refuses to complete Session 8 without that evidence already recorded — verified end-to-end via API and real-browser tests, including rejection without evidence, cross-player isolation, and duplicate-submission idempotency.',
  },
  {
    sessionId: 'flavor-memory', sessionNumber: 10, phaseId: 2,
    route: '/smokecraft/flavor-memory', title: 'Flavor Memory Exercise',
    learningObjective: 'Select flavor-wheel notes and intensity/body/strength ratings for the cigar tasted.',
    requiredInteractionId: 'S10-FLAVOR-WHEEL', requiredInteractionType: 'flavor-wheel-selection',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/FlavorMemory.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/flavor-memory; POST /api/smokecraft/player-state/sessions/flavor-memory/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt; playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=hotspot, activity_key=flavor-memory); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-c-api.mjs (39/39)', 'verify-smokecraft-required-interaction-package-c-browser.mjs (17/17)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-c/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package C: the existing 8 flavor-wheel zones are real, data-driven hotspot overlays — the server independently validates that at least 2 real, in-vocabulary hotspots were selected before completion (the same principled resolution already used by Package A for inherently subjective sensory/tasting content — flavor perception cannot be objectively "graded," but a fabricated/out-of-vocabulary hotspot id is rejected). An out-of-vocabulary hotspot never completes the session; every attempt is audited.',
  },
  {
    sessionId: 'pairing-lab', sessionNumber: 11, phaseId: 2,
    route: '/smokecraft/pairing-lab', title: 'Suggested Pairings',
    learningObjective: 'Apply pairing theory (complement/contrast/balance) to select and defend a real beverage pairing.',
    requiredInteractionId: 'S11-PAIRING-DECISION', requiredInteractionType: 'pairing-decision-and-scoring',
    completionRequired: true, scoringRequired: true, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/PairingLab.jsx',
    canonicalApi: 'server/routes/pairingEngineRoutes.js', canonicalService: 'server/services/smokecraft/pairingEngineService.js',
    canonicalPersistence: 'smokecraft_pairing_saves / smokecraft_pairing_save_revisions',
    progressionRequired: true, persistenceRequired: true,
    testReferences: ['verify-smokecraft-hf5b1-pairing-engine.mjs (36/36)', 'scripts/validateSmokecraftPairingEngineAuthority.mjs (PASS)'],
    proofReferences: ['public/proof/smokecraft-post-humidor-audit/09-pairing-engine-audit.md'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Real, server-authoritative rule-based pairing engine with real scoring/explanation/persistence — confirmed complete in two prior audit passes.',
  },
  {
    sessionId: 'second-third', sessionNumber: 12, phaseId: 3,
    route: '/smokecraft/second-third', title: 'Flavor Evolution',
    learningObjective: 'Capture tasting-evolution observations for the second third.',
    requiredInteractionId: 'S12-TASTING-CAPTURE', requiredInteractionType: 'tasting-rating-capture',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/SecondThird.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/tasting-observation/second-third; POST /api/smokecraft/player-state/sessions/second-third/complete',
    canonicalService: 'server/services/smokecraft/tastingObservationService.js#submitTastingObservation; playerStateService.js#completeSession (gated by hasTastingObservationEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=tasting_observation, activity_key=second-third)',
    testReferences: ['verify-smokecraft-required-interaction-package-a-api.mjs (26/26)', 'verify-smokecraft-required-interaction-package-a-browser.mjs (14/14)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-a/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package A: same server-authoritative evidence gate as Session 8, with its own distinct observation vocabulary enforced server-side — verified end-to-end via API and real-browser tests.',
  },
  {
    sessionId: 'mentor-commentary', sessionNumber: 14, phaseId: 3,
    route: '/smokecraft/mentor-commentary', title: 'Mentor Commentary',
    learningObjective: 'Receive real, activity-derived mentor guidance on the session so far.',
    requiredInteractionId: 'S14-MENTOR-GUIDANCE', requiredInteractionType: 'mentor-guided-response',
    completionRequired: true, scoringRequired: false, mentorRequired: true,
    canonicalComponent: 'src/pages/smokecraft/MentorCommentary.jsx',
    canonicalApi: 'server/routes/mentorGuidanceRoutes.js',
    canonicalService: 'server/services/smokecraft (mentor guidance service)',
    canonicalPersistence: 'mentor guidance / activity-derived state (Holistic Fix 5B-2)',
    progressionRequired: true, persistenceRequired: true,
    testReferences: ['verify-smokecraft-hf5b2a-mentor-guidance.mjs (21/21)', 'scripts/validateSmokecraftMentorGuidanceAuthority.mjs (PASS)'],
    proofReferences: ['public/proof/smokecraft-post-humidor-audit/08-mentor-engine-audit.md'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Real, server-owned, activity-derived guidance with an honest low-signal fallback for a fresh guest — confirmed complete in two prior audit passes. Correctly thin (no interaction beyond Back/Continue) when no mentor is selected — an honest empty state, not a defect.',
  },
  {
    sessionId: 'knowledge-drop', sessionNumber: 15, phaseId: 3,
    route: '/smokecraft/knowledge-drop', title: 'Knowledge Drop',
    learningObjective: 'Explore 4 educational topics (Tobacco/Fermentation/Aging/Factory Story).',
    requiredInteractionId: 'S15-TOPIC-EXPLORATION', requiredInteractionType: 'topic-exploration',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/KnowledgeDrop.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/selection/knowledge-drop; POST /api/smokecraft/player-state/sessions/knowledge-drop/complete',
    canonicalService: 'server/services/smokecraft/selectionClassificationService.js#submitSelectionAttempt (SESSION_DEFS["knowledge-drop"], graded against server-owned KNOWLEDGE_DROP_ANSWERS); playerStateService.js#completeSession (gated by hasSelectionEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=exploration, activity_key=knowledge-drop); smokecraft_tasting_drafts (activityKey=knowledge-drop, quiz-answer draft resume); smokecraft_award_audit (attempt history)',
    testReferences: ['verify-smokecraft-required-interaction-package-d-api.mjs (34/34)', 'verify-smokecraft-required-interaction-package-d-browser.mjs (15/15)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-d/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package D: the previously-optional, client-graded per-topic quiz is now the required interaction — all 4 topics must be answered correctly, graded server-side against the server\'s own copy of the real answer key (never the client-visible practice-UI answer field), plus a required final synthesis (most useful topic). Unlike Sessions 3/4, correctness here is objectively graded, matching the real quiz content already authored in this component.',
  },
  {
    sessionId: 'final-third', sessionNumber: 16, phaseId: 4,
    route: '/smokecraft/final-third', title: 'Flavor Finish',
    learningObjective: 'Capture final-third tasting observations (aroma/intensity/burn/aftertaste).',
    requiredInteractionId: 'S16-TASTING-CAPTURE', requiredInteractionType: 'tasting-rating-capture',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/FinalThird.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/tasting-observation/final-third; POST /api/smokecraft/player-state/sessions/final-third/complete',
    canonicalService: 'server/services/smokecraft/tastingObservationService.js#submitTastingObservation; playerStateService.js#completeSession (gated by hasTastingObservationEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=tasting_observation, activity_key=final-third)',
    testReferences: ['verify-smokecraft-required-interaction-package-a-api.mjs (26/26)', 'verify-smokecraft-required-interaction-package-a-browser.mjs (14/14)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-a/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package A: combined flavor+focus-card vocabulary submitted and validated server-side before completion; verified end-to-end via API and real-browser tests.',
  },
  {
    sessionId: 'scorecard', sessionNumber: 19, phaseId: 5,
    route: '/smokecraft/scorecard', title: 'Rate Every Category',
    learningObjective: 'Rate the cigar across 6 categories (Appearance/Construction/Draw/Burn/Flavor/Pairing Match) with real per-category guidance.',
    requiredInteractionId: 'S19-MULTI-CATEGORY-RATING', requiredInteractionType: 'multi-category-rating',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/Scorecard.jsx',
    ...SHARED_COMPLETION,
    canonicalApi: 'POST /api/smokecraft/player-state/scorecard/submit; POST /api/smokecraft/player-state/sessions/scorecard/complete; GET/PUT /api/smokecraft/player-state/tasting/scorecard/draft',
    canonicalService: 'server/services/smokecraft/scorecardEvaluationService.js#submitScorecardCompletion; playerStateService.js#completeSession (gated by hasScorecardEvidence)',
    canonicalPersistence: 'smokecraft_activity_attempts (activity_type=scorecard, activity_key=scorecard); smokecraft_tasting_drafts (activityKey=scorecard, shared with Package A/Mini Tasting)',
    testReferences: ['verify-smokecraft-required-interaction-package-b-api.mjs (34/34)', 'verify-smokecraft-required-interaction-package-b-browser.mjs (12/12)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-b/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package B: all 6 categories must be rated and are validated server-side (range 1-5, real vocabulary) before completion; the server independently computes and owns the weighted overall score (the client can no longer submit its own overall/passed/xpEarned). Reuses the exact same evidence ledger and draft table/routes established by Package A — no second scoring system. Verified end-to-end via API and real-browser tests, including cross-player/cross-session isolation, concurrency, and stale-draft-after-completion rejection.',
  },
  {
    sessionId: 'ai-summary', sessionNumber: 21, phaseId: 6,
    route: '/smokecraft/ai-summary', title: 'Session Summary',
    learningObjective: 'Review a rule-based (explicitly non-AI) summary of the session’s captured data.',
    requiredInteractionId: 'S21-SUMMARY-REVIEW', requiredInteractionType: 'rule-based-summary-review',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/AISummary.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'A review/recap session by design, not an assessment — Accept/Dismiss on each real summary panel is the appropriate interaction; honestly disclosed as rule-based, not AI-generated.',
  },
  {
    sessionId: 'pairing-recommendations', sessionNumber: 22, phaseId: 6,
    route: '/smokecraft/pairing-recommendations', title: 'Personalized Pairing Recommendations',
    learningObjective: 'Apply pairing theory to a personalized, scored recommendation set and select/save one.',
    requiredInteractionId: 'S22-PAIRING-DECISION', requiredInteractionType: 'pairing-decision-and-scoring',
    completionRequired: true, scoringRequired: true, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/PairingRecommendations.jsx',
    canonicalApi: 'server/routes/pairingEngineRoutes.js', canonicalService: 'server/services/smokecraft/pairingEngineService.js',
    canonicalPersistence: 'smokecraft_pairing_saves / smokecraft_pairing_save_revisions',
    progressionRequired: true, persistenceRequired: true,
    testReferences: ['verify-smokecraft-hf5b1-pairing-engine.mjs (36/36)', 'scripts/validateSmokecraftPairingEngineAuthority.mjs (PASS)'],
    proofReferences: ['public/proof/smokecraft-post-humidor-audit/09-pairing-engine-audit.md'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Same real pairing engine as Session 11 — real generated compatibility reasoning, view-alternate/save-pairing actions confirmed.',
  },
  {
    sessionId: 'passport-stamp', sessionNumber: 23, phaseId: 6,
    route: '/smokecraft/passport-stamp', title: 'Passport Stamp Animation',
    learningObjective: 'Certify completion of the tasting journey with a real Passport stamp record.',
    requiredInteractionId: 'S23-STAMP-CERTIFICATION', requiredInteractionType: 'status-gated-certification',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/PassportStamp.jsx',
    canonicalApi: 'GET /api/smokecraft/passport-stamp/eligibility; POST /api/smokecraft/passport-stamp/claim; GET /api/smokecraft/passport-stamp/status/:sessionId; GET /api/smokecraft/passport-stamp/guest/me; POST /api/smokecraft/player-state/sessions/passport-stamp/complete',
    canonicalService: 'server/routes/smokecraftPassportStampRoutes.js (server-authoritative eligibility via playerStateService.getPlayerState); server/services/passport360/passport360SyncService.js#claimJourneyCompletionStamp/getStamps; server/services/smokecraft/playerStateService.js#completeSession (gated by hasPassportStampEvidence)',
    canonicalPersistence: 'passport_360_earned_stamps (stamp_id=smokecraft-journey-complete, real dedupe_key idempotency); smokecraft_session_completions (session_id=passport-stamp)',
    progressionRequired: true, persistenceRequired: true,
    testReferences: ['verify-smokecraft-required-interaction-package-e-api.mjs (28/28)', 'verify-smokecraft-required-interaction-package-e-browser.mjs (19/19)'],
    proofReferences: ['public/proof/smokecraft-required-interaction-package-e/'],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Required-Interaction Closure Package E (SC-D067): fixed a real backward/unreachable sequencing defect — REQUIRED_STEPS previously included Session 24 (final-review), which comes AFTER Session 23 in route order, making first-time eligibility impossible on a normal visit; removed. Fixed missing server authority — eligibility/claim previously trusted a client-submitted completedSteps array and scorecardId; now reads the caller\'s own real smokecraft_session_completions via playerStateService.getPlayerState, never a client-supplied value. The session\'s own generic completion is now additionally gated on real, server-recorded Passport stamp evidence (hasPassportStampEvidence, same additive pattern as Packages A/B/C) so it can never complete from a route visit alone. The silent auto-claim effect was replaced with an explicit "Claim Your Stamp" button requiring a real player click, disabled until server-verified eligible. Reuses the existing canonical Passport-360 stamp system (claimJourneyCompletionStamp/getStamps, real dedupe_key idempotency) — no second Passport/rewards system created. Verified end-to-end via API and real-browser tests, including cross-player denial, concurrency, duplicate-claim, and reload persistence.',
  },
  {
    sessionId: 'final-review', sessionNumber: 24, phaseId: 6,
    route: '/smokecraft/final-review', title: 'Completed Scorecard',
    learningObjective: 'Review a checklist-style recap of the completed journey.',
    requiredInteractionId: 'S24-RECAP-REVIEW', requiredInteractionType: 'checklist-review',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/FinalReview.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'A recap/summary session by design, not new teaching — Continue-only is the appropriate interaction for this role.',
  },
  {
    sessionId: 'rewards', sessionNumber: 25, phaseId: 6,
    route: '/smokecraft/rewards', title: 'Rewards and XP (serves Session 26 Achievements)',
    learningObjective: 'Review earned XP, rank milestones, and achievement criteria tied to real completed actions.',
    requiredInteractionId: 'S25-REWARD-REVIEW', requiredInteractionType: 'reward-display',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/Rewards.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_BUT_UNTESTED',
    gapClassification: 'COMPLETE_BUT_UNTESTED',
    notes: 'A review/claim session by design; Claim buttons and tab switching are real, but this pass did not independently verify that displayed totals are read from the live server player-state (vs. locally-computed constants via smokecraftRewards.js) — flagged for the next audit rather than asserted either way.',
  },
  {
    sessionId: 'session-complete', sessionNumber: 27, phaseId: 6,
    route: '/smokecraft/session-complete', title: 'Recommended Next Journey',
    learningObjective: 'Receive a real, data-driven recommendation for the next journey based on completed session data.',
    requiredInteractionId: 'S27-NEXT-JOURNEY-SELECTION', requiredInteractionType: 'final-recommendation-display',
    completionRequired: true, scoringRequired: false, mentorRequired: false,
    canonicalComponent: 'src/pages/smokecraft/SessionComplete.jsx',
    ...SHARED_COMPLETION,
    testReferences: [], proofReferences: [],
    implementationStatus: 'COMPLETE_AND_VERIFIED',
    gapClassification: 'COMPLETE_AND_VERIFIED',
    notes: 'Genuine personalization tied to real completed-session data (confirmed by prior captured-content audit); Start Journey/Select/Explore All Journeys are real navigation actions appropriate to this closing session.',
  },
])

export function getRequiredInteraction(sessionNumber) {
  return REQUIRED_INTERACTIONS.find(r => r.sessionNumber === sessionNumber) || null
}
