// CraftHub Onboarding Feature Flags — Phase C.6
// contains_secrets: false, stores_secrets: false — hardcoded; audit rows never hold secrets

export const DEFAULT_CRAFTHUB_ONBOARDING_FLAGS = {
  craftHubOnboardingEnabled: false,
  onboardingSessionsEnabled: false,
  onboardingStepsEnabled: false,
  stepProgressEnabled: false,
  checklistItemsEnabled: false,
  onboardingBlockersEnabled: false,
  activationRequirementsEnabled: false,
  organizationSetupEnabled: false,
  venueSetupEnabled: false,
  workspaceSetupEnabled: false,
  businessUnitsSetupEnabled: false,
  departmentsSetupEnabled: false,
  locationsSetupEnabled: false,
  roleSetupEnabled: false,
  staffInvitePlaceholdersEnabled: false,
  moduleSelectionEnabled: false,
  moduleSetupStatusEnabled: false,
  pos360SetupEnabled: false,
  smokecraftSetupEnabled: false,
  pourcraftSetupEnabled: false,
  eatSetupEnabled: false,
  passportConnectionsSetupEnabled: false,
  loyaltyRewardsSetupEnabled: false,
  inventorySetupEnabled: false,
  menuSetupEnabled: false,
  fulfillmentAreaSetupEnabled: false,
  tablePatioSetupEnabled: false,
  paymentProviderPlaceholdersEnabled: false,
  billingLicensePlaceholdersEnabled: false,
  securityPlaceholdersEnabled: false,
  demoLiveModeControlsEnabled: false,
  readinessScoresEnabled: false,
  launchReadinessRecordsEnabled: false,
  safeClaimRecordsEnabled: false,
  unsafeClaimRecordsEnabled: false,
  onboardingSnapshotsEnabled: false,
  onboardingAuditEnabled: false,
  premiumOnboardingUIEnabled: false,
  handheldOnboardingLayoutEnabled: false,
  tabletOnboardingLayoutEnabled: false,
  desktopOnboardingLayoutEnabled: false,
  noFakeOnboardingCompletionEnforced: true,
  noFakeWorkspaceProvisioningEnforced: true,
  noFakeVenueDeploymentEnforced: true,
  noFakeModuleInstallEnforced: true,
  noFakeModuleActivationEnforced: true,
  noFakeProviderConnectionEnforced: true,
  noFakeBillingConnectionEnforced: true,
  noFakeLicenseVerificationEnforced: true,
  noFakeStaffInviteDeliveryEnforced: true,
  noFakeMenuImportEnforced: true,
  noFakeInventorySyncEnforced: true,
  noFakeLiveModeEnforced: true,
  noSecretsStorageEnforced: true,
  platformAdminGuardRequired: true,
};

export function getCraftHubOnboardingFlags(overrides = {}) {
  return { ...DEFAULT_CRAFTHUB_ONBOARDING_FLAGS, ...overrides };
}
