// Phase E.6 — NOVEE OS Remote Module Distribution Feature Flags
// All live delivery, provisioning, invite, license, activation, and rollback flags default false

const NOVEE_OS_REMOTE_MODULE_DISTRIBUTION_FLAGS = {
  NOVEE_REMOTE_MODULE_DISTRIBUTION_ENABLED: true,
  NOVEE_REMOTE_MODULE_LIVE_DELIVERY_ENABLED: false,
  NOVEE_REMOTE_MODULE_CLIENT_PROVISIONING_ENABLED: false,
  NOVEE_REMOTE_MODULE_INVITE_LINKS_ENABLED: false,
  NOVEE_REMOTE_MODULE_LICENSE_VALIDATION_ENABLED: false,
  NOVEE_REMOTE_MODULE_REMOTE_ACTIVATION_ENABLED: false,
  NOVEE_REMOTE_MODULE_ROLLBACK_EXECUTION_ENABLED: false,
  NOVEE_REMOTE_MODULE_SECURITY_GATE_REQUIRED: true,
  NOVEE_REMOTE_MODULE_DEPLOYMENT_GATE_REQUIRED: true,
  NOVEE_REMOTE_MODULE_PILOT_GATE_REQUIRED: true,
  NOVEE_REMOTE_MODULE_FAKE_DELIVERY_CLAIMS_BLOCKED: true,
  NOVEE_REMOTE_MODULE_FAKE_LICENSE_CLAIMS_BLOCKED: true,
  NOVEE_REMOTE_MODULE_SECRET_EXPOSURE_BLOCKED: true,
  NOVEE_REMOTE_MODULE_FRONTEND_SAFE_CLAIMS_ENABLED: true,
  NOVEE_REMOTE_MODULE_AUDIT_LOGGING_ENABLED: true,
}

export function getNoveeOSRemoteModuleDistributionFlags(overrides = {}) {
  return { ...NOVEE_OS_REMOTE_MODULE_DISTRIBUTION_FLAGS, ...overrides }
}

export default NOVEE_OS_REMOTE_MODULE_DISTRIBUTION_FLAGS
