// Phase E.9 — NOVEE OS Documentation Portal Feature Flags
// Publication, export, and client-ready flags all default false

const NOVEE_OS_DOCUMENTATION_PORTAL_FLAGS = {
  NOVEE_DOCUMENTATION_PORTAL_ENABLED: true,
  NOVEE_DOCUMENTATION_SEEDED_CONTENT_ENABLED: true,
  NOVEE_DOCUMENTATION_PUBLICATION_ENABLED: false,
  NOVEE_DOCUMENTATION_CLIENT_READY_PUBLICATION_ENABLED: false,
  NOVEE_DOCUMENTATION_STAFF_READY_PUBLICATION_ENABLED: false,
  NOVEE_DOCUMENTATION_EXPORT_ENABLED: false,
  NOVEE_DOCUMENTATION_EMAIL_EXPORT_ENABLED: false,
  NOVEE_DOCUMENTATION_PDF_EXPORT_ENABLED: false,
  NOVEE_DOCUMENTATION_SAFE_CLAIMS_ENFORCED: true,
  NOVEE_DOCUMENTATION_FAKE_COMPLETION_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_FAKE_PUBLICATION_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_FAKE_CERTIFICATION_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_FAKE_REMOTE_DISTRIBUTION_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_FAKE_AMBI_HARDWARE_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_UNSAFE_SMOKECRAFT_PRODUCTION_READY_CLAIMS_BLOCKED: true,
  NOVEE_DOCUMENTATION_EMPTY_MANUALS_BLOCKED: true,
  NOVEE_DOCUMENTATION_SENSITIVE_DATA_EXPOSURE_BLOCKED: true,
  NOVEE_DOCUMENTATION_FRONTEND_SAFE_CLAIMS_ENABLED: true,
  NOVEE_DOCUMENTATION_AUDIT_LOGGING_ENABLED: true,
}

export function getNoveeOSDocumentationPortalFlags(overrides = {}) {
  return { ...NOVEE_OS_DOCUMENTATION_PORTAL_FLAGS, ...overrides }
}

export default NOVEE_OS_DOCUMENTATION_PORTAL_FLAGS
