// Phase C.7 — NOVEE OS Final Readiness Feature Flags
// contains_secrets: false, stores_secrets: false — hardcoded; audit rows never hold secrets

export const DEFAULT_NOVEE_OS_FINAL_READINESS_FLAGS = {
  finalReadinessEnabled: false,
  platformAuditEnabled: false,
  launchLockEnabled: false,
  marketplacePrepEnabled: false,
  providerActivationReadinessEnabled: false,
  deploymentReadinessEnabled: false,
  demoLiveReadinessEnabled: false,
  safeSalesClaimsEnabled: false,
  unsafeSalesClaimsEnabled: false,
  foundationLockRecordsEnabled: false,
  phaseCompletionRecordsEnabled: false,
  moduleReadinessMatrixEnabled: false,
  documentationReadinessEnabled: false,
  verificationReadinessEnabled: false,
  buildReadinessEnabled: false,
  routeReadinessEnabled: false,
  uiReadinessEnabled: false,
  governanceReadinessEnabled: false,
  securityReadinessEnabled: false,
  billingReadinessEnabled: false,
  integrationReadinessEnabled: false,
  launchSnapshotsEnabled: false,
  launchAuditEnabled: false,
  blockerTrackingEnabled: false,
  activationRequirementTrackingEnabled: false,
  marketplaceListingPlaceholdersEnabled: false,
  marketplacePurchaseReadinessEnabled: false,
  readinessScoringEnabled: false,
  readinessFilteringEnabled: false,
  readinessStatusBadgesEnabled: false,
  premiumLaunchLockUIEnabled: false,
  handheldLaunchLockLayoutEnabled: false,
  tabletLaunchLockLayoutEnabled: false,
  desktopLaunchLockLayoutEnabled: false,
  noFakeProductionLaunchEnforced: true,
  noFakeProviderActivationEnforced: true,
  noFakeMarketplacePurchaseEnforced: true,
  noFakeModuleInstallEnforced: true,
  noFakeModuleActivationEnforced: true,
  noFakeBillingConnectionEnforced: true,
  noFakeLicenseVerificationEnforced: true,
  noFakePaymentProcessingEnforced: true,
  noFakeDeploymentCompletionEnforced: true,
  noFakeLiveModeEnforced: true,
  noFakeComplianceCertificationEnforced: true,
  noFakePOSProviderSyncEnforced: true,
  noFakeSmokeCraftSyncEnforced: true,
  noFakeEATAutomationEnforced: true,
  noFakeInventorySyncEnforced: true,
  noFakeWhiteLabelDeploymentEnforced: true,
  noFakeCustomDomainActivationEnforced: true,
  noSecretsStorageEnforced: true,
  platformAdminGuardRequired: true,
  contains_secrets: false,
  stores_secrets: false,
  exposes_private_data: true,
};

export function getNoveeOSFinalReadinessFlags(overrides = {}) {
  return { ...DEFAULT_NOVEE_OS_FINAL_READINESS_FLAGS, ...overrides };
}
