// Phase C.4 / Module 4 of 7 — NOVEE OS Security Feature Flags

export const DEFAULT_NOVEE_OS_SECURITY_FLAGS = {
  platformSecurityEnabled:                    true,
  platformUsersEnabled:                       true,
  userProfilesEnabled:                        true,
  roleCatalogEnabled:                         true,
  permissionCatalogEnabled:                   true,
  permissionGroupsEnabled:                    true,
  rolePermissionAssignmentsEnabled:           true,
  userRoleAssignmentsEnabled:                 true,
  userAccessGrantsEnabled:                    true,
  modulePermissionRulesEnabled:               true,
  routePermissionRulesEnabled:                true,
  featurePermissionRulesEnabled:              true,
  adminApprovalRequestsEnabled:               true,
  sensitiveActionRequestsEnabled:             true,
  permissionDecisionRecordsEnabled:           true,
  accessDenialRecordsEnabled:                 true,
  sessionPolicyPlaceholdersEnabled:           true,
  mfaPolicyPlaceholdersEnabled:               true,
  ssoProviderPlaceholdersEnabled:             true,
  deviceTrustPlaceholdersEnabled:             true,
  ipAllowlistPlaceholdersEnabled:             true,
  securityEventRecordsEnabled:                true,
  governanceReviewRecordsEnabled:             true,
  platformSecuritySnapshotsEnabled:           true,
  platformSecurityAuditEnabled:               true,
  roleSearchEnabled:                          true,
  permissionSearchEnabled:                    true,
  userAccessSearchEnabled:                    true,
  securityStatusBadgesEnabled:                true,
  governanceReviewEnabled:                    true,
  safeSecurityClaimsEnabled:                  true,
  unsafeSecurityClaimsEnabled:                true,
  noFakeSSOConnectionEnforced:                true,
  noFakeMFAEnforcementEnforced:               true,
  noFakeDeviceTrustEnforced:                  true,
  noFakeIPAllowlistEnforced:                  true,
  noFakeComplianceCertificationEnforced:      true,
  noFakeSecurityProviderConnectionEnforced:   true,
  noFakeNotificationDeliveryEnforced:         true,
  noFakePermissionEnforcementEnforced:        true,
  noSecretsStorageEnforced:                   true,
  platformAdminGuardRequired:                 true,
};

export function getNoveeOSSecurityFlags(overrides = {}) {
  return { ...DEFAULT_NOVEE_OS_SECURITY_FLAGS, ...overrides };
}
