// Phase C.3 / Module 3 of 7 — NOVEE OS Billing Feature Flags

export const DEFAULT_NOVEE_OS_BILLING_FLAGS = {
  licensingBillingEnabled:                  true,
  planCatalogsEnabled:                      true,
  planTiersEnabled:                         true,
  planFeaturesEnabled:                      true,
  modulePlanGatesEnabled:                   true,
  featureAccessGatesEnabled:                true,
  trialPoliciesEnabled:                     true,
  trialInstancesEnabled:                    true,
  gracePeriodsEnabled:                      true,
  organizationLicensesEnabled:              true,
  venueLicensesEnabled:                     true,
  workspaceLicensesEnabled:                 true,
  userSeatAllocationsEnabled:               true,
  addonCatalogEnabled:                      true,
  addonAssignmentsEnabled:                  true,
  entitlementRecordsEnabled:                true,
  accessDecisionRecordsEnabled:             true,
  billingProviderProfilesEnabled:           true,
  billingCustomerMetadataEnabled:           true,
  subscriptionMetadataEnabled:              true,
  invoiceMetadataEnabled:                   true,
  paymentStatusPlaceholdersEnabled:         true,
  upgradeDowngradeRequestsEnabled:          true,
  cancellationRequestsEnabled:              true,
  renewalReminderRecordsEnabled:            true,
  marketplacePurchasePlaceholdersEnabled:   true,
  licenseHealthChecksEnabled:               true,
  billingGovernanceSnapshotsEnabled:        true,
  billingAuditEnabled:                      true,
  planSearchEnabled:                        true,
  planFilteringEnabled:                     true,
  planStatusBadgesEnabled:                  true,
  safeBillingClaimsEnabled:                 true,
  unsafeBillingClaimsEnabled:               true,
  noFakeBillingConnectionEnforced:          true,
  noFakePaymentProcessingEnforced:          true,
  noFakeSubscriptionActivationEnforced:     true,
  noFakeInvoicePaymentEnforced:             true,
  noFakeLicenseVerificationEnforced:        true,
  noFakeMarketplacePurchaseEnforced:        true,
  noFakeTrialConversionEnforced:            true,
  noFakeCancellationCompletionEnforced:     true,
  noFakeRenewalChargeEnforced:              true,
  noFakeEntitlementActivationEnforced:      true,
  noSecretsStorageEnforced:                 true,
  platformAdminGuardRequired:               true,
};

export function getNoveeOSBillingFlags(overrides = {}) {
  return { ...DEFAULT_NOVEE_OS_BILLING_FLAGS, ...overrides };
}
