// Phase E.8 — NOVEE OS AMBI Foundation Feature Flags
// All hardware, telemetry, control, pairing, and automation flags default false

const NOVEE_OS_AMBI_FOUNDATION_FLAGS = {
  NOVEE_AMBI_FOUNDATION_ENABLED: true,
  NOVEE_AMBI_HARDWARE_READY_ENABLED: false,
  NOVEE_AMBI_LIVE_DEVICE_CONNECTIONS_ENABLED: false,
  NOVEE_AMBI_LIVE_TELEMETRY_ENABLED: false,
  NOVEE_AMBI_LIVE_DEVICE_CONTROL_ENABLED: false,
  NOVEE_AMBI_LIVE_ENVIRONMENT_AUTOMATION_ENABLED: false,
  NOVEE_AMBI_LIVE_PAIRING_ENABLED: false,
  NOVEE_AMBI_LIVE_FIRMWARE_UPDATES_ENABLED: false,
  NOVEE_AMBI_FAKE_HARDWARE_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_FAKE_TELEMETRY_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_FAKE_PAIRING_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_MEDICAL_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_BIOMETRIC_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_EMOTION_DETECTION_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_SAFETY_MONITORING_CLAIMS_BLOCKED: true,
  NOVEE_AMBI_SECRET_EXPOSURE_BLOCKED: true,
  NOVEE_AMBI_PRIVACY_CONSENT_REQUIRED: true,
  NOVEE_AMBI_FRONTEND_SAFE_CLAIMS_ENABLED: true,
  NOVEE_AMBI_AUDIT_LOGGING_ENABLED: true,
}

export function getNoveeOSAMBIFoundationFlags(overrides = {}) {
  return { ...NOVEE_OS_AMBI_FOUNDATION_FLAGS, ...overrides }
}

export default NOVEE_OS_AMBI_FOUNDATION_FLAGS
