// Phase E.5 — NOVEE OS Live Pilot Readiness Feature Flags
// All live/approval/distribution flags are FALSE — build-only phase

const NOVEE_OS_LIVE_PILOT_READINESS_FLAGS = {
  NOVEE_PILOT_READINESS_ENABLED: true,
  NOVEE_LIVE_PILOT_APPROVAL_ENABLED: false,
  NOVEE_LIVE_PILOT_REMOTE_DISTRIBUTION_ENABLED: false,
  NOVEE_LIVE_PILOT_PUBLIC_GO_LIVE_ENABLED: false,
  NOVEE_PILOT_FAKE_APPROVAL_BLOCKED: true,
  NOVEE_PILOT_FAKE_GO_LIVE_BLOCKED: true,
  NOVEE_PILOT_SECRET_EXPOSURE_BLOCKED: true,
  NOVEE_PILOT_SECURITY_GATE_REQUIRED: true,
  NOVEE_PILOT_E3_BYPASS_BLOCKED: true,
  NOVEE_PILOT_E4_BYPASS_BLOCKED: true,
  NOVEE_PILOT_FRONTEND_SAFE_CLAIMS_ENABLED: true,
  NOVEE_PILOT_AUDIT_LOGGING_ENABLED: true,
}

export function getNoveeOSLivePilotReadinessFlags(overrides = {}) {
  return { ...NOVEE_OS_LIVE_PILOT_READINESS_FLAGS, ...overrides }
}

export default NOVEE_OS_LIVE_PILOT_READINESS_FLAGS
