// Phase E.7 — NOVEE OS Onboarding + Training Feature Flags
// All completion, publication, and distribution-unlock flags default false

const NOVEE_OS_ONBOARDING_TRAINING_FLAGS = {
  NOVEE_ONBOARDING_TRAINING_CENTER_ENABLED: true,
  NOVEE_ONBOARDING_MANUAL_PUBLICATION_ENABLED: false,
  NOVEE_ONBOARDING_CLIENT_COMPLETION_ENABLED: false,
  NOVEE_ONBOARDING_STAFF_COMPLETION_ENABLED: false,
  NOVEE_ONBOARDING_MANAGER_COMPLETION_ENABLED: false,
  NOVEE_ONBOARDING_GUEST_COMPLETION_ENABLED: false,
  NOVEE_ONBOARDING_REMOTE_DISTRIBUTION_UNLOCK_ENABLED: false,
  NOVEE_ONBOARDING_FAKE_COMPLETION_CLAIMS_BLOCKED: true,
  NOVEE_ONBOARDING_FAKE_PUBLICATION_CLAIMS_BLOCKED: true,
  NOVEE_ONBOARDING_SENSITIVE_DATA_EXPOSURE_BLOCKED: true,
  NOVEE_ONBOARDING_FRONTEND_SAFE_CLAIMS_ENABLED: true,
  NOVEE_ONBOARDING_AUDIT_LOGGING_ENABLED: true,
}

export function getNoveeOSOnboardingTrainingFlags(overrides = {}) {
  return { ...NOVEE_OS_ONBOARDING_TRAINING_FLAGS, ...overrides }
}

export default NOVEE_OS_ONBOARDING_TRAINING_FLAGS
