// contains_secrets: false, stores_secrets: false — feature flags only

export const DEFAULT_PHASE_D_EXTERNAL_POS_FLAGS = {
  // Master gate
  PHASE_D_EXTERNAL_POS_ENABLED: false,

  // Provider registry
  EXTERNAL_POS_PROVIDER_REGISTRY_ENABLED: false,

  // Activation modes — all off by default
  EXTERNAL_POS_COMPANION_MODE_ENABLED: false,
  EXTERNAL_POS_EXPORT_IMPORT_MODE_ENABLED: false,
  EXTERNAL_POS_API_CONTRACT_MODE_ENABLED: false,
  EXTERNAL_POS_MANUAL_MAPPING_MODE_ENABLED: false,
  EXTERNAL_POS_HYBRID_MODE_ENABLED: false,

  // Per-provider contracts — all off
  TOAST_POS_CONTRACT_ENABLED: false,
  CLOVER_POS_CONTRACT_ENABLED: false,
  SQUARE_POS_CONTRACT_ENABLED: false,
  LIGHTSPEED_POS_CONTRACT_ENABLED: false,
  SHOPIFY_POS_CONTRACT_ENABLED: false,
  SPOTON_POS_CONTRACT_ENABLED: false,
  TOUCHBISTRO_POS_CONTRACT_ENABLED: false,
  REVEL_POS_CONTRACT_ENABLED: false,
  GENERIC_CSV_IMPORT_ENABLED: false,
  MANUAL_POS_COMPANION_ENABLED: false,
  FUTURE_POS_PROVIDER_PLACEHOLDER_ENABLED: false,

  // Credential tracking
  EXTERNAL_POS_CREDENTIAL_STATUS_ENABLED: false,

  // Import system
  EXTERNAL_POS_IMPORT_PROFILE_ENABLED: false,
  EXTERNAL_POS_CSV_TEMPLATE_ENABLED: false,
  EXTERNAL_POS_IMPORT_BATCH_ENABLED: false,

  // Manual mapping
  EXTERNAL_POS_MANUAL_MAPPING_ENABLED: false,
  EXTERNAL_POS_MENU_MAPPING_ENABLED: false,
  EXTERNAL_POS_MODIFIER_MAPPING_ENABLED: false,
  EXTERNAL_POS_TAX_MAPPING_ENABLED: false,
  EXTERNAL_POS_TIP_MAPPING_ENABLED: false,
  EXTERNAL_POS_PAYMENT_TYPE_MAPPING_ENABLED: false,
  EXTERNAL_POS_STAFF_ROLE_MAPPING_ENABLED: false,
  EXTERNAL_POS_TABLE_SECTION_MAPPING_ENABLED: false,
  EXTERNAL_POS_REVENUE_CENTER_MAPPING_ENABLED: false,
  EXTERNAL_POS_DEPARTMENT_MAPPING_ENABLED: false,
  EXTERNAL_POS_INVENTORY_SIGNAL_MAPPING_ENABLED: false,
  EXTERNAL_POS_HUMIDOR_MAPPING_ENABLED: false,
  EXTERNAL_POS_BAR_MAPPING_ENABLED: false,
  EXTERNAL_POS_KITCHEN_MAPPING_ENABLED: false,
  EXTERNAL_POS_ORDER_FLOW_MAPPING_ENABLED: false,
  EXTERNAL_POS_TICKET_FLOW_MAPPING_ENABLED: false,
  EXTERNAL_POS_CLOSEOUT_MAPPING_ENABLED: false,
  EXTERNAL_POS_REPORT_MAPPING_ENABLED: false,

  // API contract and webhooks
  EXTERNAL_POS_API_CONTRACT_REGISTRY_ENABLED: false,
  EXTERNAL_POS_WEBHOOK_REGISTRY_ENABLED: false,
  EXTERNAL_POS_WEBHOOK_HEALTH_ENABLED: false,

  // Live mode lock
  EXTERNAL_POS_LIVE_MODE_LOCK_ENABLED: false,

  // Tenant and module mapping
  EXTERNAL_POS_TENANT_MAPPING_ENABLED: false,
  EXTERNAL_POS_MODULE_MAPPING_ENABLED: false,

  // Compliance and risk
  EXTERNAL_POS_COMPLIANCE_CHECKLIST_ENABLED: false,
  EXTERNAL_POS_RISK_FLAGS_ENABLED: false,
  EXTERNAL_POS_ACTIVATION_AUDIT_ENABLED: false,

  // Live sync processing — always false until real approval
  EXTERNAL_POS_API_SYNC_PROCESSING_ENABLED: false,
  EXTERNAL_POS_LIVE_INVENTORY_SYNC_ENABLED: false,
  EXTERNAL_POS_LIVE_MENU_SYNC_ENABLED: false,
  EXTERNAL_POS_LIVE_TICKET_SYNC_ENABLED: false,
  EXTERNAL_POS_LIVE_SALES_SYNC_ENABLED: false,
  EXTERNAL_POS_LIVE_CLOSEOUT_SYNC_ENABLED: false,
  EXTERNAL_POS_WEBHOOK_DELIVERY_ENABLED: false,

  // Enforcement flags — always TRUE; must never be overridden to false in production
  EXTERNAL_POS_NO_SECRET_STORAGE_ENFORCED: true,
  EXTERNAL_POS_NO_FAKE_CONNECTED_STATUS_ENFORCED: true,
  EXTERNAL_POS_NO_FAKE_SYNC_ENFORCED: true,
  EXTERNAL_POS_CAN_ACCESS_POS3_WRITE_REQUIRED: true,
  EXTERNAL_POS_ADMIN_ONLY_LIVE_REQUEST_REQUIRED: true,
  EXTERNAL_POS_IDEMPOTENCY_ENFORCED: true,
  EXTERNAL_POS_AUDIT_TRAIL_ENFORCED: true,
  EXTERNAL_POS_ENVIRONMENT_LOCK_ENFORCED: true,
};

export function getPhaseDExternalPOSFlags(overrides = {}) {
  return { ...DEFAULT_PHASE_D_EXTERNAL_POS_FLAGS, ...overrides };
}
