/**
 * SmokeCraft Pairing Provider Service
 * Abstraction layer for live AI/provider-backed pairing recommendations.
 * When no provider is configured, returns local_intelligence recommendations.
 * Never exposes API keys. Never requires a live provider in this build.
 * Future providers can be added via server-side environment variables only.
 */

const _lastProviderResults = new Map()

/**
 * Returns the current provider connection status.
 * Returns false unless a real provider is configured and verified.
 */
export function getPairingProviderStatus() {
  const providerName = process.env.SMOKECRAFT_PAIRING_PROVIDER ?? null
  const providerEndpoint = process.env.SMOKECRAFT_PAIRING_ENDPOINT ?? null
  const providerKeySet = !!(process.env.SMOKECRAFT_PAIRING_API_KEY)

  // Never claim connected without all three being set
  const connected = !!(providerName && providerEndpoint && providerKeySet)

  return {
    providerConnected: connected,
    aiBacked: connected,
    providerName: connected ? providerName : null,
    providerEndpointConfigured: !!providerEndpoint,
    providerKeyConfigured: providerKeySet,
    recommendationStatus: connected ? 'provider_connected' : 'local_intelligence',
    message: connected
      ? `Pairing provider '${providerName}' is connected.`
      : 'No live AI pairing provider is connected. Recommendation generated by local SmokeCraft intelligence rules.',
  }
}

export function isProviderConnected() {
  return getPairingProviderStatus().providerConnected
}

/**
 * Attempts to call the configured provider.
 * Returns local intelligence result if provider is not connected.
 */
export async function generateProviderRecommendation(payload) {
  const status = getPairingProviderStatus()
  if (!status.providerConnected) {
    return generateLocalRecommendation(payload)
  }

  try {
    const response = await fetch(process.env.SMOKECRAFT_PAIRING_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.SMOKECRAFT_PAIRING_API_KEY}`,
      },
      body: JSON.stringify(payload),
    })
    if (!response.ok) throw new Error(`Provider returned ${response.status}`)
    const data = await response.json()
    const normalized = normalizeProviderRecommendation(data)
    _lastProviderResults.set(payload.userId ?? 'anonymous', normalized)
    return normalized
  } catch (err) {
    // Provider failed — fall back to local intelligence honestly
    const local = generateLocalRecommendation(payload)
    local.providerAttempted = true
    local.providerError = err.message
    return local
  }
}

/**
 * Generates a local intelligence recommendation without any AI provider.
 * Marked clearly as local_intelligence — never claims AI backing.
 */
export function generateLocalRecommendation(payload) {
  const { cigarProfile, tasteProfile, sessionPhase, mentorId } = payload ?? {}

  const flavorNotes = [
    ...(cigarProfile?.flavorNotes ?? []),
    ...(tasteProfile?.dominantFlavorNotes ?? []),
  ].filter((v, i, a) => a.indexOf(v) === i)

  const drinkSuggestions = buildLocalDrinkSuggestions(cigarProfile?.strengthLevel, tasteProfile)
  const foodSuggestions = buildLocalFoodSuggestions(flavorNotes, tasteProfile)

  return {
    providerConnected: false,
    aiBacked: false,
    recommendationStatus: 'local_intelligence',
    providerAttempted: false,
    source: 'local_smokecraft_intelligence',
    message: 'No live AI pairing provider is connected. Recommendation generated by local SmokeCraft intelligence rules.',
    drinkSuggestions,
    foodSuggestions,
    sessionPhase: sessionPhase ?? null,
    mentorId: mentorId ?? null,
    flavorNotesUsed: flavorNotes,
    confidenceScore: tasteProfile ? Math.min(0.45 + tasteProfile.confidenceScore * 0.35, 0.80) : 0.35,
    createdAt: new Date().toISOString(),
  }
}

function buildLocalDrinkSuggestions(strength, tasteProfile) {
  const map = {
    mild: ['Light beer', 'Prosecco', 'Green tea', 'Sparkling water with citrus'],
    mild_medium: ['White wine', 'Rosé', 'Iced coffee', 'Light craft beer'],
    medium: ['Red wine', 'Craft IPA', 'Aged rum', 'Coffee'],
    medium_full: ['Bourbon', 'Aged rum', 'Dark stout', 'Espresso'],
    full: ['Cognac', 'Single malt Scotch', 'Añejo rum', 'Dark espresso'],
  }
  const base = map[strength ?? 'medium'] ?? map['medium']
  // Filter out anything in avoidance if profile available
  const avoid = tasteProfile?.avoidIngredients ?? []
  return base.filter(d => !avoid.some(a => d.toLowerCase().includes(a.toLowerCase())))
}

function buildLocalFoodSuggestions(flavorNotes, tasteProfile) {
  const suggestions = []
  const avoid = tasteProfile?.avoidIngredients ?? []

  if (flavorNotes.some(n => ['chocolate', 'dark_chocolate', 'coffee', 'caramel'].includes(n))) {
    suggestions.push('Dark chocolate', 'Salted caramel truffle')
  }
  if (flavorNotes.some(n => ['cedar', 'earth', 'leather', 'tobacco'].includes(n))) {
    suggestions.push('Aged cheese', 'Charcuterie board')
  }
  if (flavorNotes.some(n => ['nuts', 'cream', 'vanilla', 'honey'].includes(n))) {
    suggestions.push('Roasted mixed nuts', 'Crème brûlée')
  }
  if (flavorNotes.some(n => ['pepper', 'spice'].includes(n))) {
    suggestions.push('Spiced jerky', 'Sharp cheddar')
  }
  if (suggestions.length === 0) {
    suggestions.push('Mixed nuts', 'Mild cheese plate')
  }
  return suggestions.filter(s => !avoid.some(a => s.toLowerCase().includes(a.toLowerCase())))
}

/**
 * Normalizes a raw provider response into the SmokeCraft recommendation shape.
 * Used when a real provider is connected in the future.
 */
export function normalizeProviderRecommendation(raw) {
  return {
    providerConnected: true,
    aiBacked: true,
    recommendationStatus: 'provider_recommendation',
    source: 'live_ai_provider',
    drinkSuggestions: raw.drinks ?? raw.drinkSuggestions ?? [],
    foodSuggestions: raw.foods ?? raw.foodSuggestions ?? [],
    explanation: raw.explanation ?? raw.summary ?? null,
    confidenceScore: raw.confidence ?? raw.confidenceScore ?? 0.5,
    createdAt: new Date().toISOString(),
    raw,
  }
}

export function getLastProviderResult(userId) {
  return _lastProviderResults.get(userId ?? 'anonymous') ?? null
}
