// SmokeCraft 360 — Master Mentor roster.
// Approved roster uses cigar/tobacco-growing traditions only.
// Mentor cards must use realistic fictional portraits with culturally distinct styling.

export const MENTORS = [
  {
    id: 'dominican',
    country: 'Dominican Republic',
    countryCode: 'DO',
    flag: '🇩🇴',
    name: 'Don Alejandro',
    role: 'Master Blender Mentor',
    bio: 'Master of Dominican blending, Olor leaf character, fermentation, and balance.',
    tags: ['Blending', 'Olor', 'Balance'],
    image: '/mentors/don-alejandro.jpg',
    greeting: 'I am Don Alejandro. Dominican tobacco rewards patience, balance, and respect for the leaf. I will teach you how a master blend comes together.',
  },
  {
    id: 'cuba',
    country: 'Cuba',
    countryCode: 'CU',
    flag: '🇨🇺',
    name: 'Maestro Rafael',
    role: 'Tradition Mentor',
    bio: 'Keeper of classic Cuban-seed tradition, elegant draw discipline, and old-world rolling standards.',
    tags: ['Tradition', 'Balance', 'Rolling'],
    image: '/mentors/maestro-rafael.jpg',
    greeting: 'Maestro Rafael. Tradition is not nostalgia. It is a standard. I will teach you how balance becomes elegance.',
  },
  {
    id: 'nicaragua',
    country: 'Nicaragua',
    countryCode: 'NI',
    flag: '🇳🇮',
    name: 'Javier Estelí',
    role: 'Cultivation Mentor',
    bio: "Specialist in sun-grown Criollo '98 and the robust spice profiles of Estelí and Jalapa.",
    tags: ['Cultivation', 'Earth', 'Spice'],
    image: '/mentors/javier-esteli.jpg',
    greeting: 'Javier Estelí. Nicaragua demands boldness. I will teach you how soil, sun, and cultivation shape strength and spice.',
  },
  {
    id: 'honduras',
    country: 'Honduras',
    countryCode: 'HN',
    flag: '🇭🇳',
    name: 'Doña Jamastran',
    role: 'Leaf Craft Mentor',
    bio: 'Legacy grower of authentic Corojo seed and the intense, full-bodied traditions of Danlí and Jamastrán.',
    tags: ['Corojo', 'Leaf Craft', 'Cedar'],
    image: '/mentors/dona-jamastran.jpg',
    greeting: "I am Doña Jamastran. Honduras carries generations of Corojo craft. I will show you how leaf character is built from seed to curing barn.",
  },
  {
    id: 'mexico',
    country: 'Mexico',
    countryCode: 'MX',
    flag: '🇲🇽',
    name: 'Mateo San Andrés',
    role: 'Aging & Ritual Mentor',
    bio: "Guardian of Negro San Andrés leaf, Maduro aging, and the ritual that reveals a cigar's mature character.",
    tags: ['San Andrés', 'Maduro', 'Aging'],
    image: '/mentors/mateo-san-andres.jpg',
    greeting: 'Mateo San Andrés. Dark leaf rewards time. I will teach you how aging, fermentation, and ritual reveal depth without losing balance.',
  },
  {
    id: 'brazil',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    name: 'Dra. Camila Oliveira',
    role: 'Fermentation Mentor',
    bio: 'Mata Fina specialist focused on fermentation, natural sweetness, aromatic depth, and texture.',
    tags: ['Mata Fina', 'Fermentation', 'Sweetness'],
    image: '/mentors/paulo-oliveira.jpg',
    greeting: "I am Camila Oliveira. Brazil's leaf can be generous, sweet, and deeply aromatic. I will teach you how fermentation turns raw tobacco into character.",
  },
  {
    id: 'ecuador',
    country: 'Ecuador',
    countryCode: 'EC',
    flag: '🇪🇨',
    name: 'Mateo Andrade',
    role: 'Wrapper Specialist',
    bio: 'Specialist in Ecuadorian shade-grown wrapper, cloud-filtered cultivation, silkiness, and combustion.',
    tags: ['Wrapper', 'Shade Grown', 'Texture'],
    image: '/mentors/carlos-mendoza.jpg',
    greeting: 'Mateo Andrade. Ecuadorian cloud cover changes the leaf before it ever reaches the curing barn. I will teach you to read wrapper texture, elasticity, and burn.',
  },
  {
    id: 'cameroon',
    country: 'Cameroon',
    countryCode: 'CM',
    flag: '🇨🇲',
    name: 'Amara Njoya',
    role: 'Wrapper Leaf Mentor',
    bio: 'Cameroon wrapper specialist focused on tooth, aromatic spice, thin-vein structure, and elegant combustion.',
    tags: ['Cameroon Wrapper', 'Aromatic Spice', 'Tooth'],
    image: '/mentors/thomas-blackwell.jpg',
    greeting: 'I am Amara Njoya. Cameroon wrapper is prized for aroma, texture, and quiet complexity. I will teach you what the surface of the leaf tells you before the first light.',
  },
]

export const MAX_MENTOR_SELECTIONS = 2

export function getMentorById(id) {
  return MENTORS.find(m => m.id === id) || null
}
