// verifyPos360SettingsVenueAdmin.js — Phase B.14 Prompt AA
import { readFileSync } from 'fs'

const results = []
function check(name, pass) {
  results.push({ name, pass })
  if (!pass) console.log(`FAIL: ${name}`)
}

const sql  = readFileSync('server/db/migrations/044_pos360_system_settings_venue_admin.sql', 'utf8')
const con  = readFileSync('server/services/pos360/pos360SettingsContracts.js', 'utf8')
const flag = readFileSync('server/config/pos360SettingsFeatureFlags.js', 'utf8')
const loc  = readFileSync('src/locales/pos360Settings.js', 'utf8')
const svc  = readFileSync('server/services/pos360/pos360SettingsVenueAdminService.js', 'utf8')
const ctrl = readFileSync('server/controllers/pos360SettingsVenueAdminController.js', 'utf8')
const rts  = readFileSync('server/routes/pos360SettingsVenueAdminRoutes.js', 'utf8')
const ui   = readFileSync('src/pages/pos360/POS360SettingsVenueAdmin.jsx', 'utf8')

// ── MIGRATION ──────────────────────────────────────────────────────────────────
check('migration: file exists', sql.length > 0)
check('migration: pos360_venue_profiles table', sql.includes('pos360_venue_profiles'))
check('migration: pos360_venue_regional_settings table', sql.includes('pos360_venue_regional_settings'))
check('migration: pos360_venue_operating_rules table', sql.includes('pos360_venue_operating_rules'))
check('migration: pos360_venue_financial_policies table', sql.includes('pos360_venue_financial_policies'))
check('migration: pos360_venue_compliance_settings table', sql.includes('pos360_venue_compliance_settings'))
check('migration: pos360_venue_privacy_notices table', sql.includes('pos360_venue_privacy_notices'))
check('migration: pos360_white_label_profiles table', sql.includes('pos360_white_label_profiles'))
check('migration: pos360_white_label_theme_tokens table', sql.includes('pos360_white_label_theme_tokens'))
check('migration: pos360_module_registry table', sql.includes('pos360_module_registry'))
check('migration: pos360_module_governance_rules table', sql.includes('pos360_module_governance_rules'))
check('migration: pos360_feature_flag_overrides table', sql.includes('pos360_feature_flag_overrides'))
check('migration: pos360_integration_status_registry table', sql.includes('pos360_integration_status_registry'))
check('migration: pos360_provider_readiness_checks table', sql.includes('pos360_provider_readiness_checks'))
check('migration: pos360_admin_console_profiles table', sql.includes('pos360_admin_console_profiles'))
check('migration: pos360_admin_settings_views table', sql.includes('pos360_admin_settings_views'))
check('migration: pos360_settings_change_requests table', sql.includes('pos360_settings_change_requests'))
check('migration: pos360_settings_approval_requests table', sql.includes('pos360_settings_approval_requests'))
check('migration: pos360_settings_version_history table', sql.includes('pos360_settings_version_history'))
check('migration: pos360_settings_rollback_records table', sql.includes('pos360_settings_rollback_records'))
check('migration: pos360_settings_export_requests table', sql.includes('pos360_settings_export_requests'))
check('migration: pos360_settings_offline_queue table', sql.includes('pos360_settings_offline_queue'))
check('migration: pos360_settings_audit table', sql.includes('pos360_settings_audit'))
check('migration: no DROP TABLE', !sql.includes('DROP TABLE'))
check('migration: no destructive migration', !sql.includes('ALTER TABLE') || sql.includes('ADD COLUMN'))
check('migration: CREATE TABLE IF NOT EXISTS used', sql.includes('CREATE TABLE IF NOT EXISTS'))
check('migration: venue_id present', sql.includes('venue_id'))
check('migration: admin_user_id present', sql.includes('admin_user_id'))
check('migration: actor_user_id present', sql.includes('actor_user_id'))
check('migration: module_key present', sql.includes('module_key'))
check('migration: provider_key present', sql.includes('provider_key'))
check('migration: setting_key present', sql.includes('setting_key'))
check('migration: setting_group present', sql.includes('setting_group'))
check('migration: contains_secrets BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('contains_secrets') && sql.includes('FALSE'))
check('migration: stores_secrets BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('stores_secrets') && sql.includes('FALSE'))
check('migration: exposes_private_data BOOLEAN NOT NULL DEFAULT TRUE', sql.includes('exposes_private_data') && sql.includes('DEFAULT TRUE'))
check('migration: exposes_financial_data BOOLEAN NOT NULL DEFAULT TRUE', sql.includes('exposes_financial_data') && sql.includes('DEFAULT TRUE'))
check('migration: white_label_deployed BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('white_label_deployed') && sql.includes('DEFAULT FALSE'))
check('migration: integration_connected BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('integration_connected') && sql.includes('DEFAULT FALSE'))
check('migration: compliance_certified BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('compliance_certified') && sql.includes('DEFAULT FALSE'))
check('migration: export_completed BOOLEAN NOT NULL DEFAULT FALSE', sql.includes('export_completed') && sql.includes('DEFAULT FALSE'))
check('migration: idempotency_key UNIQUE on mutation tables', sql.includes('UNIQUE (idempotency_key, venue_id) WHERE idempotency_key IS NOT NULL'))
check('migration: indexes present', sql.includes('CREATE INDEX IF NOT EXISTS'))
check('migration: venue_type CHECK constraint', sql.includes("CHECK (venue_type IN ("))
check('migration: measurement_unit CHECK constraint', sql.includes("CHECK (measurement_unit IN ("))
check('migration: financial_policies calculation_enabled default false', sql.includes('calculation_enabled') && sql.includes('DEFAULT FALSE'))
check('migration: financial_policies external_accounting_connected default false', sql.includes('external_accounting_connected') && sql.includes('DEFAULT FALSE'))
check('migration: white_label_status CHECK constraint', sql.includes("CHECK (white_label_status IN ("))
check('migration: module_status CHECK constraint', sql.includes("CHECK (module_status IN ("))
check('migration: integration_status CHECK constraint', sql.includes("CHECK (integration_status IN ("))
check('migration: sync_status CHECK constraint on offline queue', sql.includes("CHECK (sync_status IN ("))
check('migration: rollback_available present', sql.includes('rollback_available'))

// ── CONTRACTS ─────────────────────────────────────────────────────────────────
check('contracts: file exists', con.length > 0)
check('contracts: VENUE_TYPES exported', con.includes('export const VENUE_TYPES'))
check('contracts: MEASUREMENT_UNITS exported', con.includes('export const MEASUREMENT_UNITS'))
check('contracts: OPERATING_RULE_GROUPS exported', con.includes('export const OPERATING_RULE_GROUPS'))
check('contracts: FINANCIAL_POLICY_GROUPS exported', con.includes('export const FINANCIAL_POLICY_GROUPS'))
check('contracts: COMPLIANCE_GROUPS exported', con.includes('export const COMPLIANCE_GROUPS'))
check('contracts: WHITE_LABEL_STATUSES exported', con.includes('export const WHITE_LABEL_STATUSES'))
check('contracts: CUSTOM_DOMAIN_STATUSES exported', con.includes('export const CUSTOM_DOMAIN_STATUSES'))
check('contracts: THEME_TOKEN_GROUPS exported', con.includes('export const THEME_TOKEN_GROUPS'))
check('contracts: MODULE_KEYS exported', con.includes('export const MODULE_KEYS'))
check('contracts: MODULE_STATUSES exported', con.includes('export const MODULE_STATUSES'))
check('contracts: OVERRIDE_STATUSES exported', con.includes('export const OVERRIDE_STATUSES'))
check('contracts: PROVIDER_TYPES exported', con.includes('export const PROVIDER_TYPES'))
check('contracts: INTEGRATION_STATUSES exported', con.includes('export const INTEGRATION_STATUSES'))
check('contracts: READINESS_TYPES exported', con.includes('export const READINESS_TYPES'))
check('contracts: READINESS_STATUSES exported', con.includes('export const READINESS_STATUSES'))
check('contracts: CHANGE_STATUSES exported', con.includes('export const CHANGE_STATUSES'))
check('contracts: PROTECTED_SETTING_TYPES exported', con.includes('export const PROTECTED_SETTING_TYPES'))
check('contracts: APPROVAL_STATUSES exported', con.includes('export const APPROVAL_STATUSES'))
check('contracts: ROLLBACK_STATUSES exported', con.includes('export const ROLLBACK_STATUSES'))
check('contracts: SETTINGS_EXPORT_TYPES exported', con.includes('export const SETTINGS_EXPORT_TYPES'))
check('contracts: SETTINGS_EXPORT_STATUSES exported', con.includes('export const SETTINGS_EXPORT_STATUSES'))
check('contracts: isValidVenueType exported', con.includes('export const isValidVenueType'))
check('contracts: isValidMeasurementUnit exported', con.includes('export const isValidMeasurementUnit'))
check('contracts: isValidOperatingRuleGroup exported', con.includes('export const isValidOperatingRuleGroup'))
check('contracts: isValidFinancialPolicyGroup exported', con.includes('export const isValidFinancialPolicyGroup'))
check('contracts: isValidComplianceGroup exported', con.includes('export const isValidComplianceGroup'))
check('contracts: isValidWhiteLabelStatus exported', con.includes('export const isValidWhiteLabelStatus'))
check('contracts: isValidCustomDomainStatus exported', con.includes('export const isValidCustomDomainStatus'))
check('contracts: isValidThemeTokenGroup exported', con.includes('export const isValidThemeTokenGroup'))
check('contracts: isValidModuleKey exported', con.includes('export const isValidModuleKey'))
check('contracts: isValidModuleStatus exported', con.includes('export const isValidModuleStatus'))
check('contracts: isValidOverrideStatus exported', con.includes('export const isValidOverrideStatus'))
check('contracts: isValidProviderType exported', con.includes('export const isValidProviderType'))
check('contracts: isValidIntegrationStatus exported', con.includes('export const isValidIntegrationStatus'))
check('contracts: isValidReadinessType exported', con.includes('export const isValidReadinessType'))
check('contracts: isValidReadinessStatus exported', con.includes('export const isValidReadinessStatus'))
check('contracts: isValidChangeStatus exported', con.includes('export const isValidChangeStatus'))
check('contracts: isValidProtectedSettingType exported', con.includes('export const isValidProtectedSettingType'))
check('contracts: isValidApprovalStatus exported', con.includes('export const isValidApprovalStatus'))
check('contracts: isValidRollbackStatus exported', con.includes('export const isValidRollbackStatus'))
check('contracts: isValidSettingsExportType exported', con.includes('export const isValidSettingsExportType'))
check('contracts: isValidSettingsExportStatus exported', con.includes('export const isValidSettingsExportStatus'))
check('contracts: cigar_lounge venue type present', con.includes('cigar_lounge'))
check('contracts: smokecraft module key present', con.includes('smokecraft'))
check('contracts: eat module key present', con.includes("'eat'"))
check('contracts: not_connected integration status present', con.includes('not_connected'))
check('contracts: external_accounting_export-related group present', con.includes('accounting'))

// ── FEATURE FLAGS ──────────────────────────────────────────────────────────────
check('flags: file exists', flag.length > 0)
check('flags: DEFAULT_POS360_SETTINGS_FLAGS exported', flag.includes('DEFAULT_POS360_SETTINGS_FLAGS'))
check('flags: getSettingsFlags exported', flag.includes('export function getSettingsFlags'))
check('flags: systemSettingsEnabled', flag.includes('systemSettingsEnabled'))
check('flags: venueProfilesEnabled', flag.includes('venueProfilesEnabled'))
check('flags: regionalSettingsEnabled', flag.includes('regionalSettingsEnabled'))
check('flags: operatingRulesEnabled', flag.includes('operatingRulesEnabled'))
check('flags: financialPoliciesEnabled', flag.includes('financialPoliciesEnabled'))
check('flags: complianceSettingsEnabled', flag.includes('complianceSettingsEnabled'))
check('flags: whiteLabelProfilesEnabled', flag.includes('whiteLabelProfilesEnabled'))
check('flags: moduleRegistryEnabled', flag.includes('moduleRegistryEnabled'))
check('flags: moduleGovernanceEnabled', flag.includes('moduleGovernanceEnabled'))
check('flags: featureFlagOverridesEnabled', flag.includes('featureFlagOverridesEnabled'))
check('flags: integrationStatusRegistryEnabled', flag.includes('integrationStatusRegistryEnabled'))
check('flags: providerReadinessChecksEnabled', flag.includes('providerReadinessChecksEnabled'))
check('flags: settingsChangeRequestsEnabled', flag.includes('settingsChangeRequestsEnabled'))
check('flags: settingsApprovalRequestsEnabled', flag.includes('settingsApprovalRequestsEnabled'))
check('flags: settingsVersionHistoryEnabled', flag.includes('settingsVersionHistoryEnabled'))
check('flags: settingsRollbackEnabled', flag.includes('settingsRollbackEnabled'))
check('flags: offlineSettingsQueueEnabled', flag.includes('offlineSettingsQueueEnabled'))
check('flags: noFakeWhiteLabelDeploymentEnforced', flag.includes('noFakeWhiteLabelDeploymentEnforced'))
check('flags: noFakeProviderConnectionEnforced', flag.includes('noFakeProviderConnectionEnforced'))
check('flags: noFakeComplianceCertificationEnforced', flag.includes('noFakeComplianceCertificationEnforced'))
check('flags: noFakeTaxCalculationEnforced', flag.includes('noFakeTaxCalculationEnforced'))
check('flags: noSecretsStorageEnforced', flag.includes('noSecretsStorageEnforced'))
check('flags: canAccessPOS3ProtectionRequired', flag.includes('canAccessPOS3ProtectionRequired'))
check('flags: managerApprovalForFinancialSettingsEnabled', flag.includes('managerApprovalForFinancialSettingsEnabled'))
check('flags: managerApprovalForModuleTogglesEnabled', flag.includes('managerApprovalForModuleTogglesEnabled'))
check('flags: managerApprovalForWhiteLabelEnabled', flag.includes('managerApprovalForWhiteLabelEnabled'))
check('flags: managerApprovalForProviderStatusEnabled', flag.includes('managerApprovalForProviderStatusEnabled'))
check('flags: managerApprovalForComplianceSettingsEnabled', flag.includes('managerApprovalForComplianceSettingsEnabled'))
check('flags: tenantVenueScopeProtectionEnabled', flag.includes('tenantVenueScopeProtectionEnabled'))
check('flags: privacyNoticesEnabled', flag.includes('privacyNoticesEnabled'))
check('flags: noFakeAccountingExportEnforced', flag.includes('noFakeAccountingExportEnforced'))
check('flags: 35+ flags present', (flag.match(/Enabled|Enforced|Required|Protected/g) || []).length >= 35)

// ── LOCALES ────────────────────────────────────────────────────────────────────
check('locales: file exists', loc.length > 0)
check('locales: 6 languages', ['en-US','es-DO','es','ht','de','pt'].every(l => loc.includes(`'${l}'`)))
check('locales: tSettings exported', loc.includes('export function tSettings'))
check('locales: getSupportedSettingsLanguages exported', loc.includes('export function getSupportedSettingsLanguages'))
check('locales: honest_empty label exists', loc.includes('honest_empty'))
check('locales: provider_not_connected label', loc.includes('provider_not_connected'))
check('locales: white_label_not_deployed label', loc.includes('white_label_not_deployed'))
check('locales: compliance_not_certified label', loc.includes('compliance_not_certified'))
check('locales: tax_calculation_not_enabled label', loc.includes('tax_calculation_not_enabled'))
check('locales: accounting_export_not_connected label', loc.includes('accounting_export_not_connected'))
check('locales: no_secrets_stored label', loc.includes('no_secrets_stored'))
check('locales: private_data_protected label', loc.includes('private_data_protected'))
check('locales: financial_data_protected label', loc.includes('financial_data_protected'))
check('locales: manager_approval_required label', loc.includes('manager_approval_required'))
check('locales: integration_not_connected label', loc.includes('integration_not_connected'))
check('locales: offline_queue_note label', loc.includes('offline_queue_note'))
check('locales: no_fake_white_label label', loc.includes('no_fake_white_label'))
check('locales: no_fake_provider label', loc.includes('no_fake_provider'))
check('locales: no_fake_compliance label', loc.includes('no_fake_compliance'))
check('locales: no_eat_ai label', loc.includes('no_eat_ai'))
check('locales: venue_scoped label', loc.includes('venue_scoped'))

// ── SERVICE ────────────────────────────────────────────────────────────────────
check('service: file exists', svc.length > 0)
check('service: JSDoc falls back gracefully', svc.includes('Falls back gracefully when no database connection is configured'))
check('service: Never prints or logs database connection string', svc.includes('Never prints or logs the database connection string'))
check('service: AREA constant', svc.includes("AREA = 'pos360-settings-venue-admin'"))
check('service: local fallback', svc.includes('localPreview: true') && svc.includes('database_not_configured'))
check('service: auditRecord function', svc.includes('async function auditRecord'))
check('service: contains_secrets=FALSE in audit', svc.includes('contains_secrets') && (svc.includes('false') || svc.includes('FALSE')))
check('service: stores_secrets=FALSE in audit', svc.includes('stores_secrets') && (svc.includes('false') || svc.includes('FALSE')))
check('service: createVenueProfile exists', svc.includes('export async function createVenueProfile'))
check('service: getVenueProfile exists', svc.includes('export async function getVenueProfile'))
check('service: updateVenueProfile exists', svc.includes('export async function updateVenueProfile'))
check('service: createRegionalSettings exists', svc.includes('export async function createRegionalSettings'))
check('service: getRegionalSettings exists', svc.includes('export async function getRegionalSettings'))
check('service: updateRegionalSettings exists', svc.includes('export async function updateRegionalSettings'))
check('service: createOperatingRule exists', svc.includes('export async function createOperatingRule'))
check('service: listOperatingRules exists', svc.includes('export async function listOperatingRules'))
check('service: updateOperatingRule exists', svc.includes('export async function updateOperatingRule'))
check('service: createFinancialPolicy exists', svc.includes('export async function createFinancialPolicy'))
check('service: listFinancialPolicies exists', svc.includes('export async function listFinancialPolicies'))
check('service: updateFinancialPolicy exists', svc.includes('export async function updateFinancialPolicy'))
check('service: createComplianceSetting exists', svc.includes('export async function createComplianceSetting'))
check('service: listComplianceSettings exists', svc.includes('export async function listComplianceSettings'))
check('service: updateComplianceSetting exists', svc.includes('export async function updateComplianceSetting'))
check('service: createPrivacyNotice exists', svc.includes('export async function createPrivacyNotice'))
check('service: listPrivacyNotices exists', svc.includes('export async function listPrivacyNotices'))
check('service: createWhiteLabelProfile exists', svc.includes('export async function createWhiteLabelProfile'))
check('service: getWhiteLabelProfile exists', svc.includes('export async function getWhiteLabelProfile'))
check('service: updateWhiteLabelProfile exists', svc.includes('export async function updateWhiteLabelProfile'))
check('service: createThemeToken exists', svc.includes('export async function createThemeToken'))
check('service: listThemeTokens exists', svc.includes('export async function listThemeTokens'))
check('service: updateThemeToken exists', svc.includes('export async function updateThemeToken'))
check('service: createModuleRegistryEntry exists', svc.includes('export async function createModuleRegistryEntry'))
check('service: listModuleRegistry exists', svc.includes('export async function listModuleRegistry'))
check('service: updateModuleStatus exists', svc.includes('export async function updateModuleStatus'))
check('service: createModuleGovernanceRule exists', svc.includes('export async function createModuleGovernanceRule'))
check('service: listModuleGovernanceRules exists', svc.includes('export async function listModuleGovernanceRules'))
check('service: createFeatureFlagOverride exists', svc.includes('export async function createFeatureFlagOverride'))
check('service: listFeatureFlagOverrides exists', svc.includes('export async function listFeatureFlagOverrides'))
check('service: updateFeatureFlagOverrideStatus exists', svc.includes('export async function updateFeatureFlagOverrideStatus'))
check('service: createIntegrationStatus exists', svc.includes('export async function createIntegrationStatus'))
check('service: listIntegrationStatuses exists', svc.includes('export async function listIntegrationStatuses'))
check('service: updateIntegrationStatus exists', svc.includes('export async function updateIntegrationStatus'))
check('service: createProviderReadinessCheck exists', svc.includes('export async function createProviderReadinessCheck'))
check('service: listProviderReadinessChecks exists', svc.includes('export async function listProviderReadinessChecks'))
check('service: updateProviderReadinessStatus exists', svc.includes('export async function updateProviderReadinessStatus'))
check('service: createAdminConsoleProfile exists', svc.includes('export async function createAdminConsoleProfile'))
check('service: listAdminConsoleProfiles exists', svc.includes('export async function listAdminConsoleProfiles'))
check('service: recordAdminSettingsView exists', svc.includes('export async function recordAdminSettingsView'))
check('service: createSettingsChangeRequest exists', svc.includes('export async function createSettingsChangeRequest'))
check('service: listSettingsChangeRequests exists', svc.includes('export async function listSettingsChangeRequests'))
check('service: applySettingsChangeRequest exists', svc.includes('export async function applySettingsChangeRequest'))
check('service: createSettingsApprovalRequest exists', svc.includes('export async function createSettingsApprovalRequest'))
check('service: listSettingsApprovalRequests exists', svc.includes('export async function listSettingsApprovalRequests'))
check('service: decideSettingsApprovalRequest exists', svc.includes('export async function decideSettingsApprovalRequest'))
check('service: createSettingsVersionHistory exists', svc.includes('export async function createSettingsVersionHistory'))
check('service: listSettingsVersionHistory exists', svc.includes('export async function listSettingsVersionHistory'))
check('service: createSettingsRollbackRecord exists', svc.includes('export async function createSettingsRollbackRecord'))
check('service: decideSettingsRollback exists', svc.includes('export async function decideSettingsRollback'))
check('service: createSettingsExportRequest exists', svc.includes('export async function createSettingsExportRequest'))
check('service: listSettingsExportRequests exists', svc.includes('export async function listSettingsExportRequests'))
check('service: markSettingsExportReadyPlaceholder exists', svc.includes('export async function markSettingsExportReadyPlaceholder'))
check('service: queueOfflineSettingsAction exists', svc.includes('export async function queueOfflineSettingsAction'))
check('service: listOfflineSettingsQueue exists', svc.includes('export async function listOfflineSettingsQueue'))
check('service: markOfflineSettingsActionSynced exists', svc.includes('export async function markOfflineSettingsActionSynced'))
check('service: idempotencyKey required on mutations', svc.includes('idempotencyKey required'))
check('service: no fake white-label deployment', svc.includes('white_label_deployed') && svc.includes('FALSE'))
check('service: no fake custom domain', svc.includes('not_configured') || svc.includes('custom_domain_status'))
check('service: no fake provider connection', svc.includes('integration_connected') && svc.includes('FALSE'))
check('service: no fake compliance certification', svc.includes('compliance_certified') && svc.includes('FALSE'))
check('service: no fake tax calculation', svc.includes('calculation_enabled') && svc.includes('FALSE'))
check('service: no fake accounting export', svc.includes('external_accounting_connected') && svc.includes('FALSE'))
check('service: no secrets storage', svc.includes('stores_secrets') && svc.includes('FALSE'))
check('service: no secrets in audit', svc.includes('contains_secrets') && (svc.includes('FALSE') || svc.includes('false')))
check('service: honest empty state response', svc.includes('honest_state') || svc.includes('localPreview'))
check('service: manager approval for protected settings', svc.includes('Manager approval required'))
check('service: honest note on white label', svc.includes('honest_note'))
check('service: honest note on integration', svc.includes('honest_note') && svc.includes('integration_connected'))
check('service: honest note on financial policy', svc.includes('calculation_enabled=FALSE'))
check('service: honest note on export', svc.includes('export_completed=FALSE'))
check('service: SmokeCraft reference present', svc.includes('SmokeCraft') || svc.includes('smokecraft'))
check('service: E.A.T. reference present', svc.includes('E.A.T.') || svc.includes('eat'))
check('service: isDbAvailable used', svc.includes('isDbAvailable'))

// ── CONTROLLER ────────────────────────────────────────────────────────────────
check('controller: file exists', ctrl.length > 0)
check('controller: ok500 pattern used', ctrl.includes('const ok500'))
check('controller: vid/actor/tid pattern used', ctrl.includes('const vid') && ctrl.includes('const actor') && ctrl.includes('const tid'))
check('controller: createVenueProfile exported', ctrl.includes('export const createVenueProfile'))
check('controller: getVenueProfile exported', ctrl.includes('export const getVenueProfile'))
check('controller: updateVenueProfile exported', ctrl.includes('export const updateVenueProfile'))
check('controller: createRegionalSettings exported', ctrl.includes('export const createRegionalSettings'))
check('controller: getRegionalSettings exported', ctrl.includes('export const getRegionalSettings'))
check('controller: updateRegionalSettings exported', ctrl.includes('export const updateRegionalSettings'))
check('controller: createOperatingRule exported', ctrl.includes('export const createOperatingRule'))
check('controller: listOperatingRules exported', ctrl.includes('export const listOperatingRules'))
check('controller: updateOperatingRule exported', ctrl.includes('export const updateOperatingRule'))
check('controller: createFinancialPolicy exported', ctrl.includes('export const createFinancialPolicy'))
check('controller: listFinancialPolicies exported', ctrl.includes('export const listFinancialPolicies'))
check('controller: updateFinancialPolicy exported', ctrl.includes('export const updateFinancialPolicy'))
check('controller: createComplianceSetting exported', ctrl.includes('export const createComplianceSetting'))
check('controller: listComplianceSettings exported', ctrl.includes('export const listComplianceSettings'))
check('controller: updateComplianceSetting exported', ctrl.includes('export const updateComplianceSetting'))
check('controller: createPrivacyNotice exported', ctrl.includes('export const createPrivacyNotice'))
check('controller: listPrivacyNotices exported', ctrl.includes('export const listPrivacyNotices'))
check('controller: createWhiteLabelProfile exported', ctrl.includes('export const createWhiteLabelProfile'))
check('controller: getWhiteLabelProfile exported', ctrl.includes('export const getWhiteLabelProfile'))
check('controller: updateWhiteLabelProfile exported', ctrl.includes('export const updateWhiteLabelProfile'))
check('controller: createThemeToken exported', ctrl.includes('export const createThemeToken'))
check('controller: listThemeTokens exported', ctrl.includes('export const listThemeTokens'))
check('controller: updateThemeToken exported', ctrl.includes('export const updateThemeToken'))
check('controller: createModuleRegistryEntry exported', ctrl.includes('export const createModuleRegistryEntry'))
check('controller: listModuleRegistry exported', ctrl.includes('export const listModuleRegistry'))
check('controller: updateModuleStatus exported', ctrl.includes('export const updateModuleStatus'))
check('controller: createModuleGovernanceRule exported', ctrl.includes('export const createModuleGovernanceRule'))
check('controller: listModuleGovernanceRules exported', ctrl.includes('export const listModuleGovernanceRules'))
check('controller: createFeatureFlagOverride exported', ctrl.includes('export const createFeatureFlagOverride'))
check('controller: listFeatureFlagOverrides exported', ctrl.includes('export const listFeatureFlagOverrides'))
check('controller: updateFeatureFlagOverrideStatus exported', ctrl.includes('export const updateFeatureFlagOverrideStatus'))
check('controller: createIntegrationStatus exported', ctrl.includes('export const createIntegrationStatus'))
check('controller: listIntegrationStatuses exported', ctrl.includes('export const listIntegrationStatuses'))
check('controller: updateIntegrationStatus exported', ctrl.includes('export const updateIntegrationStatus'))
check('controller: createProviderReadinessCheck exported', ctrl.includes('export const createProviderReadinessCheck'))
check('controller: listProviderReadinessChecks exported', ctrl.includes('export const listProviderReadinessChecks'))
check('controller: updateProviderReadinessStatus exported', ctrl.includes('export const updateProviderReadinessStatus'))
check('controller: createAdminConsoleProfile exported', ctrl.includes('export const createAdminConsoleProfile'))
check('controller: listAdminConsoleProfiles exported', ctrl.includes('export const listAdminConsoleProfiles'))
check('controller: recordAdminSettingsView exported', ctrl.includes('export const recordAdminSettingsView'))
check('controller: createSettingsChangeRequest exported', ctrl.includes('export const createSettingsChangeRequest'))
check('controller: listSettingsChangeRequests exported', ctrl.includes('export const listSettingsChangeRequests'))
check('controller: applySettingsChangeRequest exported', ctrl.includes('export const applySettingsChangeRequest'))
check('controller: createSettingsApprovalRequest exported', ctrl.includes('export const createSettingsApprovalRequest'))
check('controller: listSettingsApprovalRequests exported', ctrl.includes('export const listSettingsApprovalRequests'))
check('controller: decideSettingsApprovalRequest exported', ctrl.includes('export const decideSettingsApprovalRequest'))
check('controller: createSettingsVersionHistory exported', ctrl.includes('export const createSettingsVersionHistory'))
check('controller: listSettingsVersionHistory exported', ctrl.includes('export const listSettingsVersionHistory'))
check('controller: createSettingsRollbackRecord exported', ctrl.includes('export const createSettingsRollbackRecord'))
check('controller: decideSettingsRollback exported', ctrl.includes('export const decideSettingsRollback'))
check('controller: createSettingsExportRequest exported', ctrl.includes('export const createSettingsExportRequest'))
check('controller: listSettingsExportRequests exported', ctrl.includes('export const listSettingsExportRequests'))
check('controller: markSettingsExportReadyPlaceholder exported', ctrl.includes('export const markSettingsExportReadyPlaceholder'))
check('controller: queueOfflineSettingsAction exported', ctrl.includes('export const queueOfflineSettingsAction'))
check('controller: listOfflineSettingsQueue exported', ctrl.includes('export const listOfflineSettingsQueue'))
check('controller: markOfflineSettingsActionSynced exported', ctrl.includes('export const markOfflineSettingsActionSynced'))

// ── ROUTES ────────────────────────────────────────────────────────────────────
check('routes: file exists', rts.length > 0)
check('routes: import canAccessPOS3', rts.includes("from '../middleware/roleMiddleware.js'"))
check('routes: mounted comment', rts.includes('/api/pos360/settings'))
check('routes: venue-profile write route guarded', rts.includes("canAccessPOS3, ctrl.createVenueProfile"))
check('routes: regional write route guarded', rts.includes("canAccessPOS3, ctrl.createRegionalSettings"))
check('routes: operating-rules write route guarded', rts.includes("canAccessPOS3, ctrl.createOperatingRule"))
check('routes: financial-policies write route guarded', rts.includes("canAccessPOS3, ctrl.createFinancialPolicy"))
check('routes: compliance write route guarded', rts.includes("canAccessPOS3, ctrl.createComplianceSetting"))
check('routes: white-label write route guarded', rts.includes("canAccessPOS3, ctrl.createWhiteLabelProfile"))
check('routes: modules write route guarded', rts.includes("canAccessPOS3, ctrl.createModuleRegistryEntry"))
check('routes: integrations write route guarded', rts.includes("canAccessPOS3, ctrl.createIntegrationStatus"))
check('routes: change-requests write route guarded', rts.includes("canAccessPOS3, ctrl.createSettingsChangeRequest"))
check('routes: approval-requests write route guarded', rts.includes("canAccessPOS3, ctrl.createSettingsApprovalRequest"))
check('routes: version-history write route guarded', rts.includes("canAccessPOS3, ctrl.createSettingsVersionHistory"))
check('routes: rollback write route guarded', rts.includes("canAccessPOS3, ctrl.createSettingsRollbackRecord"))
check('routes: exports write route guarded', rts.includes("canAccessPOS3, ctrl.createSettingsExportRequest"))
check('routes: offline-queue write route guarded', rts.includes("canAccessPOS3, ctrl.queueOfflineSettingsAction"))
check('routes: admin-console write route guarded', rts.includes("canAccessPOS3, ctrl.createAdminConsoleProfile"))
check('routes: feature-flag-overrides write route guarded', rts.includes("canAccessPOS3, ctrl.createFeatureFlagOverride"))

// ── FRONTEND ──────────────────────────────────────────────────────────────────
check('frontend: file exists', ui.length > 0)
check('frontend: SettingsDashboard component', ui.includes('function SettingsDashboard'))
check('frontend: VenueProfilePanel component', ui.includes('function VenueProfilePanel'))
check('frontend: RegionalSettingsPanel component', ui.includes('function RegionalSettingsPanel'))
check('frontend: OperatingRulesPanel component', ui.includes('function OperatingRulesPanel'))
check('frontend: FinancialPoliciesPanel component', ui.includes('function FinancialPoliciesPanel'))
check('frontend: ComplianceSettingsPanel component', ui.includes('function ComplianceSettingsPanel'))
check('frontend: PrivacyNoticesPanel component', ui.includes('function PrivacyNoticesPanel'))
check('frontend: WhiteLabelProfilePanel component', ui.includes('function WhiteLabelProfilePanel'))
check('frontend: ThemeTokensPanel component', ui.includes('function ThemeTokensPanel'))
check('frontend: ModuleRegistryPanel component', ui.includes('function ModuleRegistryPanel'))
check('frontend: ModuleGovernancePanel component', ui.includes('function ModuleGovernancePanel'))
check('frontend: FeatureFlagOverridePanel component', ui.includes('function FeatureFlagOverridePanel'))
check('frontend: IntegrationStatusPanel component', ui.includes('function IntegrationStatusPanel'))
check('frontend: ProviderReadinessPanel component', ui.includes('function ProviderReadinessPanel'))
check('frontend: AdminConsoleProfilePanel component', ui.includes('function AdminConsoleProfilePanel'))
check('frontend: AdminSettingsViewPanel component', ui.includes('function AdminSettingsViewPanel'))
check('frontend: SettingsChangeRequestPanel component', ui.includes('function SettingsChangeRequestPanel'))
check('frontend: SettingsApprovalPanel component', ui.includes('function SettingsApprovalPanel'))
check('frontend: SettingsVersionHistoryPanel component', ui.includes('function SettingsVersionHistoryPanel'))
check('frontend: SettingsRollbackPanel component', ui.includes('function SettingsRollbackPanel'))
check('frontend: SettingsExportPanel component', ui.includes('function SettingsExportPanel'))
check('frontend: OfflineSettingsQueuePanel component', ui.includes('function OfflineSettingsQueuePanel'))
check('frontend: SettingsLanguageSelector component', ui.includes('function SettingsLanguageSelector'))
check('frontend: PrivateDataProtectionPanel component', ui.includes('function PrivateDataProtectionPanel'))
check('frontend: FinancialDataProtectionPanel component', ui.includes('function FinancialDataProtectionPanel'))
check('frontend: NoSecretsStoredPanel component', ui.includes('function NoSecretsStoredPanel'))
check('frontend: HonestWhiteLabelStatePanel component', ui.includes('function HonestWhiteLabelStatePanel'))
check('frontend: HonestIntegrationStatePanel component', ui.includes('function HonestIntegrationStatePanel'))
check('frontend: HonestComplianceStatePanel component', ui.includes('function HonestComplianceStatePanel'))
check('frontend: HonestEmptyStatePanel component', ui.includes('function HonestEmptyStatePanel'))
check('frontend: smokecraft-pos360.png reference x1', ui.includes('/smokecraft-pos360.png'))
check('frontend: smokecraft-pos360.png reference x2', (ui.match(/smokecraft-pos360\.png/g) || []).length >= 2)
check('frontend: Touchscreen header label', ui.includes('Touchscreen') && ui.includes('Handheld') && ui.includes('Tablet') && ui.includes('Desktop'))
check('frontend: API path /api/pos360/settings', ui.includes("'/api/pos360/settings'"))
check('frontend: no fake populated venue data', !ui.includes('fakeVenueName') && !ui.includes('testVenue123'))
check('frontend: integration-not-connected language', ui.includes('Not Connected') || ui.includes('not_connected'))
check('frontend: white-label not deployed language', ui.includes('not deployed') || ui.includes('white_label_deployed'))
check('frontend: compliance not certified language', ui.includes('not certified') || ui.includes('compliance_certified'))
check('frontend: tax calculation not enabled language', ui.includes('Calc Disabled') || ui.includes('tax calculation'))
check('frontend: no secrets stored language', ui.includes('No Secrets') || ui.includes('no_secrets'))
check('frontend: private data protected language', ui.includes('Private Data') || ui.includes('private_data'))
check('frontend: financial data protected language', ui.includes('Financial Data') || ui.includes('financial_data'))
check('frontend: manager approval language', ui.includes('Manager approval') || ui.includes('Mgr Approval') || ui.includes('Mgr Required'))
check('frontend: HonestNote component used', ui.includes('function HonestNote') || ui.includes('<HonestNote'))
check('frontend: LocalPreviewBanner used', ui.includes('function LocalPreviewBanner') || ui.includes('<LocalPreviewBanner'))
check('frontend: touchAction manipulation', ui.includes('touchAction'))

// ── SAFETY ────────────────────────────────────────────────────────────────────
check('safety: PII handling language in service', svc.includes('exposes_private_data'))
check('safety: financial data handling in service', svc.includes('exposes_financial_data'))
check('safety: contains_secrets false in audit', svc.includes('contains_secrets') && (svc.includes('FALSE') || svc.includes('false')))
check('safety: stores_secrets false in audit', svc.includes('stores_secrets') && (svc.includes('FALSE') || svc.includes('false')))
check('safety: white_label_deployed false enforced', svc.includes('white_label_deployed') && svc.includes('FALSE'))
check('safety: integration_connected false enforced', svc.includes('integration_connected') && svc.includes('FALSE'))
check('safety: compliance_certified false enforced', svc.includes('compliance_certified') && svc.includes('FALSE'))
check('safety: export_completed false enforced', svc.includes('export_completed') && svc.includes('FALSE'))
check('safety: offline queue honest note', svc.includes('queued for sync') || svc.includes('offline'))
check('safety: canAccessPOS3 in routes', rts.includes('canAccessPOS3'))
check('safety: white-label not deployed protection in routes', !rts.includes('deployWhiteLabel') && !rts.includes('connectDomain'))
check('safety: provider not connected protection in routes', !rts.includes('connectProvider') && !rts.includes('activateIntegration'))
check('safety: compliance not certified protection', !rts.includes('certifyCompliance') && !rts.includes('issueCertification'))
check('safety: tax calculation not enabled protection', !rts.includes('calculateTax') && !rts.includes('taxCalcLive'))
check('safety: accounting export not connected protection', !rts.includes('connectAccounting') && !rts.includes('exportLedger'))
check('safety: no SMS/email/printer provider route', !rts.includes('connectSMS') && !rts.includes('connectPrinter'))
check('safety: no fake E.A.T. AI route', !rts.includes('connectEatAI') && !rts.includes('activateAI'))
check('safety: prior module flag files not deleted', con.includes('smokecraft') && con.includes('loyalty'))
check('safety: venue-scoped settings protection', svc.includes('venueId required') || svc.includes('venue_id'))
check('safety: protected settings approval exists', svc.includes('decideSettingsApprovalRequest'))
check('safety: settings versioning exists', svc.includes('createSettingsVersionHistory'))
check('safety: settings rollback metadata exists', svc.includes('rollback_available'))
check('safety: no external sync claim', !svc.includes('syncExternalNow') && !svc.includes('deployLive'))
check('safety: no storage of secrets confirmed', svc.includes('stores_secrets') && svc.includes('FALSE'))
check('safety: SmokeCraft in service doc', svc.includes('SmokeCraft'))
check('safety: E.A.T. in service doc', svc.includes('E.A.T.'))
check('safety: prior no-fake protections referenced in flags', flag.includes('noFakeWhiteLabelDeploymentEnforced') && flag.includes('noFakeProviderConnectionEnforced'))
check('safety: build-safe JSX exports', ui.includes('export default function POS360SettingsVenueAdmin'))

// ── SUMMARY ────────────────────────────────────────────────────────────────────
const passed = results.filter(r => r.pass).length
const failed = results.filter(r => !r.pass).length
console.log(`\nPhase B.14 Verification: ${passed} passed, ${failed} failed`)
if (failed > 0) process.exit(1)
