import { readFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '../..')

let passed = 0
let failed = 0
const failures = []

function assert(condition, label) {
  if (condition) { passed++ } else { failed++; failures.push(label); console.error(`  FAIL: ${label}`) }
}

function fileExists(rel) { return existsSync(resolve(root, rel)) }
function readFile(rel) { const p = resolve(root, rel); return existsSync(p) ? readFileSync(p, 'utf8') : '' }

console.log('\n=== verifyExternalOperationsGateway — Phase 18 EOCG ===\n')

// ── Safe Credential Helper ───────────────────────────────────────────────────
const sc = readFile('server/utils/safeCredentialStatus.js')
assert(fileExists('server/utils/safeCredentialStatus.js'), 'safeCredentialStatus.js exists')
assert(sc.includes('redactSecret'), 'redactSecret exported')
assert(sc.includes('redactDatabaseUrl'), 'redactDatabaseUrl exported')
assert(sc.includes('redactCredential'), 'redactCredential exported')
assert(sc.includes('hasCredential'), 'hasCredential exported')
assert(sc.includes('validateCredentialShape'), 'validateCredentialShape exported')
assert(sc.includes('buildCredentialReadinessSummary'), 'buildCredentialReadinessSummary exported')
assert(sc.includes('assertNoSecretLeak'), 'assertNoSecretLeak exported')
assert(sc.includes('sk_live_') || sc.includes('sk_test_'), 'assertNoSecretLeak checks for secret patterns')
assert(sc.includes('present') && sc.includes('missing'), 'credential statuses present/missing')
assert(!sc.includes('process.env.STRIPE_SECRET_KEY'), 'no raw secret values returned')

// ── Live External Operations Readiness Service ───────────────────────────────
const leors = readFile('server/services/externalOps/liveExternalOperationsReadinessService.js')
assert(fileExists('server/services/externalOps/liveExternalOperationsReadinessService.js'), 'liveExternalOperationsReadinessService.js exists')
assert(leors.includes('EOCG_STATUSES'), 'EOCG_STATUSES defined')
assert(leors.includes('getLiveExternalOperationsReadiness'), 'getLiveExternalOperationsReadiness exported')
assert(leors.includes('getDatabaseGateForExternalOps'), 'getDatabaseGateForExternalOps exported')
assert(leors.includes('getExternalPOSCredentialStatus'), 'getExternalPOSCredentialStatus exported')
assert(leors.includes('getVendorCredentialStatus'), 'getVendorCredentialStatus exported')
assert(leors.includes('getDistributorCredentialStatus'), 'getDistributorCredentialStatus exported')
assert(leors.includes('getManufacturerCredentialStatus'), 'getManufacturerCredentialStatus exported')
assert(leors.includes('getWebhookCredentialStatus'), 'getWebhookCredentialStatus exported')
assert(leors.includes('getEmailChannelStatus'), 'getEmailChannelStatus exported')
assert(leors.includes('getPurchaseOrderSubmissionReadiness'), 'getPurchaseOrderSubmissionReadiness exported')
assert(leors.includes('getOperationalSyncConsumerReadiness'), 'getOperationalSyncConsumerReadiness exported')
assert(leors.includes('buildExternalOperationsBlockerReport'), 'buildExternalOperationsBlockerReport exported')
assert(leors.includes('buildExternalOperationsFallbackResponse'), 'buildExternalOperationsFallbackResponse exported')
assert(leors.includes('buildLOCCExternalOperationsSummary'), 'buildLOCCExternalOperationsSummary exported')
assert(leors.includes('external_sync_not_live'), 'external_sync_not_live in service')
assert(leors.includes('real_time_push_pending'), 'real_time_push_pending in service')
assert(leors.includes('external_pos_required'), 'external_pos_required in service')
assert(leors.includes('vendor_api_required'), 'vendor_api_required in service')
assert(leors.includes('distributor_connection_required'), 'distributor_connection_required in service')
assert(leors.includes('manufacturer_connection_required'), 'manufacturer_connection_required in service')
assert(leors.includes('purchase_order_not_submitted'), 'purchase_order_not_submitted in service')
assert(leors.includes('canSubmitLive: false'), 'canSubmitLive: false always')
assert(leors.includes('valueExposed: false'), 'credential values never exposed')
assert(leors.includes('DATABASE_URL') && !leors.includes("process.env.DATABASE_URL + '"), 'DATABASE_URL checked safely')

// ── External POS Connector Gateway ───────────────────────────────────────────
const epcg = readFile('server/services/externalPos/externalPOSConnectorGateway.js')
assert(fileExists('server/services/externalPos/externalPOSConnectorGateway.js'), 'externalPOSConnectorGateway.js exists')
assert(epcg.includes('SUPPORTED_POS_PROVIDERS'), 'SUPPORTED_POS_PROVIDERS defined')
assert(epcg.includes('square'), 'Square provider listed')
assert(epcg.includes('toast'), 'Toast provider listed')
assert(epcg.includes('clover'), 'Clover provider listed')
assert(epcg.includes('lightspeed'), 'Lightspeed provider listed')
assert(epcg.includes('shopify_pos'), 'Shopify POS provider listed')
assert(epcg.includes('stripe_terminal'), 'Stripe Terminal provider listed')
assert(epcg.includes('custom'), 'Custom POS provider listed')
assert(epcg.includes('POS_CONNECTION_STATUSES'), 'POS_CONNECTION_STATUSES defined')
assert(epcg.includes('POS_SYNC_DIRECTIONS'), 'POS_SYNC_DIRECTIONS defined')
assert(epcg.includes('getExternalPOSConnectionStatus'), 'getExternalPOSConnectionStatus exported')
assert(epcg.includes('validateExternalPOSCredentials'), 'validateExternalPOSCredentials exported')
assert(epcg.includes('listSupportedPOSProviders'), 'listSupportedPOSProviders exported')
assert(epcg.includes('getPOSProviderCapabilities'), 'getPOSProviderCapabilities exported')
assert(epcg.includes('pullInventoryFromPOSPreview'), 'pullInventoryFromPOSPreview exported')
assert(epcg.includes('pushAvailabilityToPOSPreview'), 'pushAvailabilityToPOSPreview exported')
assert(epcg.includes('syncMenuAvailabilityPreview'), 'syncMenuAvailabilityPreview exported')
assert(epcg.includes('processExternalPOSWebhookPreview'), 'processExternalPOSWebhookPreview exported')
assert(epcg.includes('mapExternalPOSProductToInventoryRecord'), 'mapExternalPOSProductToInventoryRecord exported')
assert(epcg.includes('mapInventoryRecordToExternalPOSProduct'), 'mapInventoryRecordToExternalPOSProduct exported')
assert(epcg.includes('buildExternalPOSRequiredResponse'), 'buildExternalPOSRequiredResponse exported')
assert(epcg.includes('buildExternalPOSSyncNotLiveResponse'), 'buildExternalPOSSyncNotLiveResponse exported')
assert(epcg.includes('external_sync_not_live'), 'external_sync_not_live in POS gateway')
assert(epcg.includes('preview_only'), 'preview_only in POS gateway')

// ── External POS Inventory Sync Service ──────────────────────────────────────
const episs = readFile('server/services/externalPos/externalPOSInventorySyncService.js')
assert(fileExists('server/services/externalPos/externalPOSInventorySyncService.js'), 'externalPOSInventorySyncService.js exists')
assert(episs.includes('getInventorySyncReadiness'), 'getInventorySyncReadiness exported')
assert(episs.includes('pullInventorySnapshot'), 'pullInventorySnapshot exported')
assert(episs.includes('pushInventoryUpdate'), 'pushInventoryUpdate exported')
assert(episs.includes('reconcileInventoryWithPOS'), 'reconcileInventoryWithPOS exported')
assert(episs.includes('buildInventorySyncNotLiveResponse'), 'buildInventorySyncNotLiveResponse exported')
assert(episs.includes('external_sync_not_live'), 'external_sync_not_live in inventory sync')

// ── External POS Menu Availability Service ────────────────────────────────────
const epmas = readFile('server/services/externalPos/externalPOSMenuAvailabilityService.js')
assert(fileExists('server/services/externalPos/externalPOSMenuAvailabilityService.js'), 'externalPOSMenuAvailabilityService.js exists')
assert(epmas.includes('getMenuSyncReadiness'), 'getMenuSyncReadiness exported')
assert(epmas.includes('syncMenuAvailabilityToPreview'), 'syncMenuAvailabilityToPreview exported')
assert(epmas.includes('getMenuAvailabilityFromPOSPreview'), 'getMenuAvailabilityFromPOSPreview exported')
assert(epmas.includes('buildMenuSyncNotLiveResponse'), 'buildMenuSyncNotLiveResponse exported')

// ── External POS Webhook Service ──────────────────────────────────────────────
const epws = readFile('server/services/externalPos/externalPOSWebhookService.js')
assert(fileExists('server/services/externalPos/externalPOSWebhookService.js'), 'externalPOSWebhookService.js exists')
assert(epws.includes('getWebhookReadiness'), 'getWebhookReadiness exported')
assert(epws.includes('processWebhookPreview'), 'processWebhookPreview exported')
assert(epws.includes('validateWebhookSignaturePreview'), 'validateWebhookSignaturePreview exported')
assert(epws.includes('buildWebhookNotLiveResponse'), 'buildWebhookNotLiveResponse exported')
assert(epws.includes('webhook_required'), 'webhook_required in webhook service')
assert(epws.includes('real_time_push_pending'), 'real_time_push_pending in webhook service')

// ── External POS Product Mapping Service ─────────────────────────────────────
const eppms = readFile('server/services/externalPos/externalPOSProductMappingService.js')
assert(fileExists('server/services/externalPos/externalPOSProductMappingService.js'), 'externalPOSProductMappingService.js exists')
assert(eppms.includes('MAPPING_STATUSES'), 'MAPPING_STATUSES defined')
assert(eppms.includes('createPOSProductMapping'), 'createPOSProductMapping exported')
assert(eppms.includes('getPOSProductMapping'), 'getPOSProductMapping exported')
assert(eppms.includes('getMappingsByVenue'), 'getMappingsByVenue exported')
assert(eppms.includes('getMappingsByProvider'), 'getMappingsByProvider exported')
assert(eppms.includes('validatePOSProductMapping'), 'validatePOSProductMapping exported')
assert(eppms.includes('detectUnmappedInventoryProducts'), 'detectUnmappedInventoryProducts exported')
assert(eppms.includes('detectUnmappedPOSProducts'), 'detectUnmappedPOSProducts exported')
assert(eppms.includes('detectMappingConflicts'), 'detectMappingConflicts exported')
assert(eppms.includes('buildMappingRequiredResponse'), 'buildMappingRequiredResponse exported')
assert(eppms.includes('pos_product_mapping_required'), 'pos_product_mapping_required in mapping service')

// ── Vendor Connector Gateway ──────────────────────────────────────────────────
const vcg = readFile('server/services/vendorGateway/vendorConnectorGateway.js')
assert(fileExists('server/services/vendorGateway/vendorConnectorGateway.js'), 'vendorConnectorGateway.js exists')
assert(vcg.includes('CONNECTOR_TYPES'), 'CONNECTOR_TYPES defined')
assert(vcg.includes('VENDOR_CONNECTION_STATUSES'), 'VENDOR_CONNECTION_STATUSES defined')
assert(vcg.includes('getVendorConnectorStatus'), 'getVendorConnectorStatus exported')
assert(vcg.includes('getDistributorConnectorStatus'), 'getDistributorConnectorStatus exported')
assert(vcg.includes('getManufacturerConnectorStatus'), 'getManufacturerConnectorStatus exported')
assert(vcg.includes('validateVendorCredentials'), 'validateVendorCredentials exported')
assert(vcg.includes('listSupportedVendorConnectorTypes'), 'listSupportedVendorConnectorTypes exported')
assert(vcg.includes('getVendorConnectorCapabilities'), 'getVendorConnectorCapabilities exported')
assert(vcg.includes('syncVendorCatalogPreview'), 'syncVendorCatalogPreview exported')
assert(vcg.includes('checkVendorProductAvailabilityPreview'), 'checkVendorProductAvailabilityPreview exported')
assert(vcg.includes('submitPurchaseOrderPreview'), 'submitPurchaseOrderPreview exported')
assert(vcg.includes('submitPurchaseOrderViaEmailPreview'), 'submitPurchaseOrderViaEmailPreview exported')
assert(vcg.includes('exportPurchaseOrderCSVPreview'), 'exportPurchaseOrderCSVPreview exported')
assert(vcg.includes('exportPurchaseOrderPDFPreview'), 'exportPurchaseOrderPDFPreview exported')
assert(vcg.includes('buildVendorAPIRequiredResponse'), 'buildVendorAPIRequiredResponse exported')
assert(vcg.includes('buildDistributorRequiredResponse'), 'buildDistributorRequiredResponse exported')
assert(vcg.includes('buildManufacturerRequiredResponse'), 'buildManufacturerRequiredResponse exported')
assert(vcg.includes('buildPurchaseOrderNotSubmittedResponse'), 'buildPurchaseOrderNotSubmittedResponse exported')
assert(vcg.includes('vendor_api_required'), 'vendor_api_required in gateway')
assert(vcg.includes('reorder_not_submitted'), 'reorder_not_submitted in gateway')
assert(vcg.includes('purchase_order_not_submitted'), 'purchase_order_not_submitted in gateway')
assert(vcg.includes('canSubmitLive: false'), 'canSubmitLive: false in gateway')
assert(vcg.includes('autoApprovalDisabled: true'), 'autoApprovalDisabled: true in gateway')
assert(vcg.includes('api'), 'api connector type')
assert(vcg.includes('email'), 'email connector type')
assert(vcg.includes('csv_export'), 'csv_export connector type')
assert(vcg.includes('pdf_export'), 'pdf_export connector type')

// ── Distributor Connector Service ─────────────────────────────────────────────
const dcs = readFile('server/services/vendorGateway/distributorConnectorService.js')
assert(fileExists('server/services/vendorGateway/distributorConnectorService.js'), 'distributorConnectorService.js exists')
assert(dcs.includes('getDistributorConnectorStatus'), 'getDistributorConnectorStatus exported')
assert(dcs.includes('getDistributorCatalogPreview'), 'getDistributorCatalogPreview exported')
assert(dcs.includes('submitOrderToDistributorPreview'), 'submitOrderToDistributorPreview exported')
assert(dcs.includes('buildDistributorConnectionRequiredResponse'), 'buildDistributorConnectionRequiredResponse exported')
assert(dcs.includes('distributor_connection_required'), 'distributor_connection_required in service')

// ── Manufacturer Connector Service ────────────────────────────────────────────
const mcs = readFile('server/services/vendorGateway/manufacturerConnectorService.js')
assert(fileExists('server/services/vendorGateway/manufacturerConnectorService.js'), 'manufacturerConnectorService.js exists')
assert(mcs.includes('getManufacturerConnectorStatus'), 'getManufacturerConnectorStatus exported')
assert(mcs.includes('getManufacturerCatalogPreview'), 'getManufacturerCatalogPreview exported')
assert(mcs.includes('submitOrderToManufacturerPreview'), 'submitOrderToManufacturerPreview exported')
assert(mcs.includes('buildManufacturerConnectionRequiredResponse'), 'buildManufacturerConnectionRequiredResponse exported')
assert(mcs.includes('manufacturer_connection_required'), 'manufacturer_connection_required in service')

// ── Vendor Catalog Sync Service ───────────────────────────────────────────────
const vcss = readFile('server/services/vendorGateway/vendorCatalogSyncService.js')
assert(fileExists('server/services/vendorGateway/vendorCatalogSyncService.js'), 'vendorCatalogSyncService.js exists')
assert(vcss.includes('getCatalogSyncReadiness'), 'getCatalogSyncReadiness exported')
assert(vcss.includes('syncVendorCatalogPreview'), 'syncVendorCatalogPreview exported')
assert(vcss.includes('checkVendorProductAvailabilityPreview'), 'checkVendorProductAvailabilityPreview exported')
assert(vcss.includes('buildCatalogSyncNotLiveResponse'), 'buildCatalogSyncNotLiveResponse exported')

// ── Vendor PO Submission Service ──────────────────────────────────────────────
const vposs = readFile('server/services/vendorGateway/vendorPurchaseOrderSubmissionService.js')
assert(fileExists('server/services/vendorGateway/vendorPurchaseOrderSubmissionService.js'), 'vendorPurchaseOrderSubmissionService.js exists')
assert(vposs.includes('getSubmissionReadiness'), 'getSubmissionReadiness exported')
assert(vposs.includes('submitViaAPIPreview'), 'submitViaAPIPreview exported')
assert(vposs.includes('submitViaEmailPreview'), 'submitViaEmailPreview exported')
assert(vposs.includes('exportOrderCSVPreview'), 'exportOrderCSVPreview exported')
assert(vposs.includes('exportOrderPDFPreview'), 'exportOrderPDFPreview exported')

// ── Purchase Order Submission Gateway ─────────────────────────────────────────
const posg = readFile('server/services/reorder/purchaseOrderSubmissionGateway.js')
assert(fileExists('server/services/reorder/purchaseOrderSubmissionGateway.js'), 'purchaseOrderSubmissionGateway.js exists')
assert(posg.includes('SUBMISSION_STATUSES'), 'SUBMISSION_STATUSES defined')
assert(posg.includes('validatePurchaseOrderForSubmission'), 'validatePurchaseOrderForSubmission exported')
assert(posg.includes('validatePurchaseOrderApprovalGate'), 'validatePurchaseOrderApprovalGate exported')
assert(posg.includes('validatePurchaseOrderActorRole'), 'validatePurchaseOrderActorRole exported')
assert(posg.includes('getPurchaseOrderSubmissionMethod'), 'getPurchaseOrderSubmissionMethod exported')
assert(posg.includes('getPurchaseOrderSubmissionReadiness'), 'getPurchaseOrderSubmissionReadiness exported')
assert(posg.includes('submitPurchaseOrderThroughGateway'), 'submitPurchaseOrderThroughGateway exported')
assert(posg.includes('submitPurchaseOrderPreviewOnly'), 'submitPurchaseOrderPreviewOnly exported')
assert(posg.includes('markPurchaseOrderSubmissionAttempt'), 'markPurchaseOrderSubmissionAttempt exported')
assert(posg.includes('markPurchaseOrderSubmissionBlocked'), 'markPurchaseOrderSubmissionBlocked exported')
assert(posg.includes('markPurchaseOrderSubmittedIfLive'), 'markPurchaseOrderSubmittedIfLive exported')
assert(posg.includes('buildPurchaseOrderSubmissionReadiness'), 'buildPurchaseOrderSubmissionReadiness exported')
assert(posg.includes('buildPurchaseOrderNotSubmittedResponse'), 'buildPurchaseOrderNotSubmittedResponse exported')
assert(posg.includes('buildLOCCPurchaseOrderSubmissionSummary'), 'buildLOCCPurchaseOrderSubmissionSummary exported')
// Role enforcement
assert(posg.includes("'manager'") && posg.includes("'owner'") && posg.includes("'admin'"), 'manager/owner/admin allowed for submission')
assert(posg.includes("'guest'"), 'guest blocked from submission')
assert(posg.includes("'customer'"), 'customer blocked from submission')
assert(posg.includes("'server'"), 'server blocked from submission')
assert(posg.includes("'bartender'"), 'bartender blocked from submission')
assert(posg.includes("'kitchen_staff'"), 'kitchen_staff blocked from submission')
assert(posg.includes("'humidor_staff'"), 'humidor_staff blocked from submission')
assert(posg.includes('canSubmitLive: false'), 'canSubmitLive: false in gateway')
assert(posg.includes('autoApprovalDisabled: true'), 'autoApprovalDisabled: true in gateway')
assert(posg.includes('approval_required') || posg.includes('approvalRequired'), 'approval required enforced')

// ── Operational Sync Event Consumer ──────────────────────────────────────────
const osec = readFile('server/services/sync/operationalSyncEventConsumer.js')
assert(fileExists('server/services/sync/operationalSyncEventConsumer.js'), 'operationalSyncEventConsumer.js exists')
assert(osec.includes('CONSUMER_STATUSES'), 'CONSUMER_STATUSES defined')
assert(osec.includes('consumer_preview_only'), 'consumer_preview_only status')
assert(osec.includes('real_time_push_pending'), 'real_time_push_pending status')
assert(osec.includes('webhook_consumer_pending'), 'webhook_consumer_pending status')
assert(osec.includes('getQueuedSyncEvents'), 'getQueuedSyncEvents exported')
assert(osec.includes('processNextSyncEventPreview'), 'processNextSyncEventPreview exported')
assert(osec.includes('processSyncEventBatchPreview'), 'processSyncEventBatchPreview exported')
assert(osec.includes('routeSyncEventToExternalPOS'), 'routeSyncEventToExternalPOS exported')
assert(osec.includes('routeSyncEventToVendorGateway'), 'routeSyncEventToVendorGateway exported')
assert(osec.includes('routeSyncEventToEAT'), 'routeSyncEventToEAT exported')
assert(osec.includes('routeSyncEventToPOS360'), 'routeSyncEventToPOS360 exported')
assert(osec.includes('routeSyncEventToNCIE'), 'routeSyncEventToNCIE exported')
assert(osec.includes('routeSyncEventToLOCC'), 'routeSyncEventToLOCC exported')
assert(osec.includes('markSyncEventProcessedPreview'), 'markSyncEventProcessedPreview exported')
assert(osec.includes('markSyncEventBlocked'), 'markSyncEventBlocked exported')
assert(osec.includes('buildSyncConsumerReadinessReport'), 'buildSyncConsumerReadinessReport exported')
assert(osec.includes('buildLOCCSyncConsumerSummary'), 'buildLOCCSyncConsumerSummary exported')
assert(osec.includes('sync_event_consumer_foundation_ready'), 'sync_event_consumer_foundation_ready in consumer')
assert(!osec.includes('liveConsumerReady: true'), 'liveConsumerReady never true')

// ── Availability Push Readiness Service ──────────────────────────────────────
const aprs = readFile('server/services/realtime/availabilityPushReadinessService.js')
assert(fileExists('server/services/realtime/availabilityPushReadinessService.js'), 'availabilityPushReadinessService.js exists')
assert(aprs.includes('PUSH_STATUSES'), 'PUSH_STATUSES defined')
assert(aprs.includes('getAvailabilityPushReadiness'), 'getAvailabilityPushReadiness exported')
assert(aprs.includes('buildAvailabilityUpdatePayload'), 'buildAvailabilityUpdatePayload exported')
assert(aprs.includes('buildInventoryAvailabilityBroadcastPreview'), 'buildInventoryAvailabilityBroadcastPreview exported')
assert(aprs.includes('buildPOS360AvailabilityPushPreview'), 'buildPOS360AvailabilityPushPreview exported')
assert(aprs.includes('buildEATAvailabilityPushPreview'), 'buildEATAvailabilityPushPreview exported')
assert(aprs.includes('buildKDSAvailabilityPushPreview'), 'buildKDSAvailabilityPushPreview exported')
assert(aprs.includes('buildNCIEAvailabilityPushPreview'), 'buildNCIEAvailabilityPushPreview exported')
assert(aprs.includes('buildLOCCAvailabilityPushPreview'), 'buildLOCCAvailabilityPushPreview exported')
assert(aprs.includes('buildRealtimePushPendingResponse'), 'buildRealtimePushPendingResponse exported')
assert(aprs.includes('real_time_push_pending'), 'real_time_push_pending in push service')
assert(aprs.includes('websocket_required'), 'websocket_required in push service')
assert(aprs.includes('sse_required'), 'sse_required in push service')

// ── External Ops Event Emission Service ──────────────────────────────────────
const eoees = readFile('server/services/externalOps/externalOpsEventEmissionService.js')
assert(fileExists('server/services/externalOps/externalOpsEventEmissionService.js'), 'externalOpsEventEmissionService.js exists')
assert(eoees.includes('emitCheckoutInventorySyncEventPreview'), 'checkout sync event emission exported')
assert(eoees.includes('emitStaffOrderInventorySyncEventPreview'), 'staff sync event emission exported')
assert(eoees.includes('emitKDSInventoryBlockedSyncEventPreview'), 'kds sync event emission exported')
assert(eoees.includes('emitNCIEDemandSignalSyncEventPreview'), 'ncie sync event emission exported')
assert(eoees.includes('emitPOS360AvailabilitySyncEventPreview'), 'pos360 sync event emission exported')
assert(eoees.includes('emitEATInventoryCommandSyncEventPreview'), 'eat sync event emission exported')
assert(eoees.includes('emitLOCCRetrySyncEventPreview'), 'locc sync event emission exported')
assert(eoees.includes('buildExternalOpsEventEmissionReport'), 'buildExternalOpsEventEmissionReport exported')
assert(eoees.includes('external_sync_not_live'), 'external_sync_not_live in emission service')
assert(eoees.includes('real_time_push_pending'), 'real_time_push_pending in emission service')
assert(!eoees.includes('emitted: true'), 'no fake live emission')

// ── LOCC External Ops Bridge ──────────────────────────────────────────────────
const leoeb = readFile('server/services/operations/loccExternalOpsBridgeService.js')
assert(fileExists('server/services/operations/loccExternalOpsBridgeService.js'), 'loccExternalOpsBridgeService.js exists')
assert(leoeb.includes('getLOCCExternalOpsSummary'), 'getLOCCExternalOpsSummary exported')
assert(leoeb.includes('getLOCCExternalPOSSummary'), 'getLOCCExternalPOSSummary exported')
assert(leoeb.includes('getLOCCVendorGatewaySummary'), 'getLOCCVendorGatewaySummary exported')
assert(leoeb.includes('getLOCCPurchaseOrderSubmissionSummary'), 'getLOCCPurchaseOrderSubmissionSummary exported')
assert(leoeb.includes('getLOCCSyncConsumerSummary'), 'getLOCCSyncConsumerSummary exported')
assert(leoeb.includes('getLOCCAvailabilityPushSummary'), 'getLOCCAvailabilityPushSummary exported')
assert(leoeb.includes('buildLOCCExternalOpsPanelData'), 'buildLOCCExternalOpsPanelData exported')

// ── POS360 External Ops Status ────────────────────────────────────────────────
const p360eos = readFile('server/services/pos360/pos360ExternalOpsStatusService.js')
assert(fileExists('server/services/pos360/pos360ExternalOpsStatusService.js'), 'pos360ExternalOpsStatusService.js exists')
assert(p360eos.includes('getPOS360ExternalOpsStatus'), 'getPOS360ExternalOpsStatus exported')
assert(p360eos.includes('getPOS360ExternalPOSStatus'), 'getPOS360ExternalPOSStatus exported')
assert(p360eos.includes('getPOS360ProductMappingStatus'), 'getPOS360ProductMappingStatus exported')
assert(p360eos.includes('getPOS360InventorySyncStatus'), 'getPOS360InventorySyncStatus exported')
assert(p360eos.includes('getPOS360MenuSyncStatus'), 'getPOS360MenuSyncStatus exported')
assert(p360eos.includes('getPOS360AvailabilityPushStatus'), 'getPOS360AvailabilityPushStatus exported')
assert(p360eos.includes('buildPOS360ExternalOpsReport'), 'buildPOS360ExternalOpsReport exported')
assert(p360eos.includes('external_pos_required'), 'external_pos_required in POS360 status')
assert(p360eos.includes('pos_product_mapping_required'), 'pos_product_mapping_required in POS360 status')

// ── ISPAE External Ops Bridge ─────────────────────────────────────────────────
const ieob = readFile('server/services/inventory/inventoryExternalOpsBridgeService.js')
assert(fileExists('server/services/inventory/inventoryExternalOpsBridgeService.js'), 'inventoryExternalOpsBridgeService.js exists')
assert(ieob.includes('getInventoryExternalOpsContext'), 'getInventoryExternalOpsContext exported')
assert(ieob.includes('getInventoryPOSMappingStatus'), 'getInventoryPOSMappingStatus exported')
assert(ieob.includes('getInventoryExternalSyncStatus'), 'getInventoryExternalSyncStatus exported')
assert(ieob.includes('getInventoryVendorReadinessStatus'), 'getInventoryVendorReadinessStatus exported')
assert(ieob.includes('getInventoryAvailabilityPushStatus'), 'getInventoryAvailabilityPushStatus exported')
assert(ieob.includes('buildInventoryExternalOpsContextReport'), 'buildInventoryExternalOpsContextReport exported')
assert(ieob.includes('externalPosMappingStatus'), 'externalPosMappingStatus in context')
assert(ieob.includes('vendorConnectorStatus'), 'vendorConnectorStatus in context')

// ── DMRC External Submission Bridge ──────────────────────────────────────────
const desb = readFile('server/services/reorder/reorderExternalSubmissionBridgeService.js')
assert(fileExists('server/services/reorder/reorderExternalSubmissionBridgeService.js'), 'reorderExternalSubmissionBridgeService.js exists')
assert(desb.includes('REORDER_SUBMISSION_STATUSES'), 'REORDER_SUBMISSION_STATUSES defined')
assert(desb.includes('submission_gateway_blocked'), 'submission_gateway_blocked in statuses')
assert(desb.includes('live_vendor_submission_unavailable'), 'live_vendor_submission_unavailable in statuses')
assert(desb.includes('getReorderExternalSubmissionContext'), 'getReorderExternalSubmissionContext exported')
assert(desb.includes('validateReorderSubmissionReadiness'), 'validateReorderSubmissionReadiness exported')
assert(desb.includes('routePurchaseOrderToSubmissionGateway'), 'routePurchaseOrderToSubmissionGateway exported')
assert(desb.includes('buildReorderSubmissionBlockedResponse'), 'buildReorderSubmissionBlockedResponse exported')
assert(desb.includes('buildReorderExternalSubmissionReport'), 'buildReorderExternalSubmissionReport exported')
assert(desb.includes('canSubmitLive: false'), 'canSubmitLive: false in DMRC bridge')
assert(desb.includes('reorder_not_submitted'), 'reorder_not_submitted in DMRC bridge')
assert(desb.includes('autoApprovalDisabled: true'), 'autoApprovalDisabled: true in DMRC bridge')

// ── Controllers ───────────────────────────────────────────────────────────────
assert(fileExists('server/controllers/externalPOSController.js'), 'externalPOSController.js exists')
assert(fileExists('server/controllers/vendorGatewayController.js'), 'vendorGatewayController.js exists')
assert(fileExists('server/controllers/operationalSyncController.js'), 'operationalSyncController.js exists')
assert(fileExists('server/controllers/liveExternalOpsController.js'), 'liveExternalOpsController.js exists')

const epCtrl = readFile('server/controllers/externalPOSController.js')
assert(epCtrl.includes('handleExternalPOSReadiness'), 'handleExternalPOSReadiness exported')
assert(epCtrl.includes('handleListPOSProviders'), 'handleListPOSProviders exported')
assert(epCtrl.includes('handleInventoryPullPreview'), 'handleInventoryPullPreview exported')
assert(epCtrl.includes('handleWebhookPreview'), 'handleWebhookPreview exported')

const vgCtrl = readFile('server/controllers/vendorGatewayController.js')
assert(vgCtrl.includes('handleVendorGatewayReadiness'), 'handleVendorGatewayReadiness exported')
assert(vgCtrl.includes('handlePurchaseOrderSubmitPreview'), 'handlePurchaseOrderSubmitPreview exported')
assert(vgCtrl.includes('handlePurchaseOrderExportCSVPreview'), 'handlePurchaseOrderExportCSVPreview exported')

const osCtrl = readFile('server/controllers/operationalSyncController.js')
assert(osCtrl.includes('handleSyncConsumerReadiness'), 'handleSyncConsumerReadiness exported')
assert(osCtrl.includes('handleProcessBatchPreview'), 'handleProcessBatchPreview exported')

const leoCtrl = readFile('server/controllers/liveExternalOpsController.js')
assert(leoCtrl.includes('handleLiveExternalOpsReadiness'), 'handleLiveExternalOpsReadiness exported')
assert(leoCtrl.includes('handleCredentialStatus'), 'handleCredentialStatus exported')
assert(leoCtrl.includes('handlePushReadiness'), 'handlePushReadiness exported')

// ── Routes ────────────────────────────────────────────────────────────────────
assert(fileExists('server/routes/externalPOSRoutes.js'), 'externalPOSRoutes.js exists')
assert(fileExists('server/routes/vendorGatewayRoutes.js'), 'vendorGatewayRoutes.js exists')
assert(fileExists('server/routes/operationalSyncRoutes.js'), 'operationalSyncRoutes.js exists')
assert(fileExists('server/routes/liveExternalOpsRoutes.js'), 'liveExternalOpsRoutes.js exists')

const epRoutes = readFile('server/routes/externalPOSRoutes.js')
assert(epRoutes.includes('/readiness'), 'external-pos readiness route')
assert(epRoutes.includes('/providers'), 'external-pos providers route')
assert(epRoutes.includes('/inventory/pull-preview'), 'inventory pull preview route')
assert(epRoutes.includes('/webhook/preview'), 'webhook preview route')

const vgRoutes = readFile('server/routes/vendorGatewayRoutes.js')
assert(vgRoutes.includes('/readiness'), 'vendor-gateway readiness route')
assert(vgRoutes.includes('/purchase-order/submit-preview'), 'purchase-order submit preview route')
assert(vgRoutes.includes('/purchase-order/export-csv-preview'), 'csv export preview route')

// ── Server Wiring ─────────────────────────────────────────────────────────────
const serverIndex = readFile('server/index.js')
assert(serverIndex.includes('externalPOSRoutes'), 'externalPOSRoutes imported in server/index.js')
assert(serverIndex.includes('vendorGatewayRoutes'), 'vendorGatewayRoutes imported')
assert(serverIndex.includes('operationalSyncRoutes'), 'operationalSyncRoutes imported')
assert(serverIndex.includes('liveExternalOpsRoutes'), 'liveExternalOpsRoutes imported')
assert(serverIndex.includes('/api/external-pos'), 'external-pos mounted')
assert(serverIndex.includes('/api/vendor-gateway'), 'vendor-gateway mounted')
assert(serverIndex.includes('/api/operational-sync'), 'operational-sync mounted')
assert(serverIndex.includes('/api/live-external-ops'), 'live-external-ops mounted')

// ── E.A.T. Hooks ──────────────────────────────────────────────────────────────
const eat = readFile('server/services/eatCommandHubContract.js')
assert(eat.includes('getLiveExternalOperationsReadinessHooks'), 'getLiveExternalOperationsReadinessHooks in E.A.T.')
assert(eat.includes('getExternalPOSConnectorReadinessHooks'), 'getExternalPOSConnectorReadinessHooks in E.A.T.')
assert(eat.includes('getExternalPOSMappingReadinessHooks'), 'getExternalPOSMappingReadinessHooks in E.A.T.')
assert(eat.includes('getExternalPOSInventorySyncReadinessHooks'), 'getExternalPOSInventorySyncReadinessHooks in E.A.T.')
assert(eat.includes('getVendorConnectorReadinessHooks'), 'getVendorConnectorReadinessHooks in E.A.T.')
assert(eat.includes('getDistributorConnectorReadinessHooks'), 'getDistributorConnectorReadinessHooks in E.A.T.')
assert(eat.includes('getManufacturerConnectorReadinessHooks'), 'getManufacturerConnectorReadinessHooks in E.A.T.')
assert(eat.includes('getVendorCatalogSyncReadinessHooks'), 'getVendorCatalogSyncReadinessHooks in E.A.T.')
assert(eat.includes('getPurchaseOrderSubmissionGatewayReadinessHooks'), 'getPurchaseOrderSubmissionGatewayReadinessHooks in E.A.T.')
assert(eat.includes('getOperationalSyncConsumerReadinessHooks'), 'getOperationalSyncConsumerReadinessHooks in E.A.T.')
assert(eat.includes('getAvailabilityPushReadinessHooks'), 'getAvailabilityPushReadinessHooks in E.A.T.')
assert(eat.includes('getLOCCExternalOpsReadinessHooks'), 'getLOCCExternalOpsReadinessHooks in E.A.T.')

// ── UI Components ─────────────────────────────────────────────────────────────
const compDir = 'src/components/externalops'
assert(fileExists(`${compDir}/LiveExternalOpsReadinessPanel.jsx`), 'LiveExternalOpsReadinessPanel.jsx exists')
assert(fileExists(`${compDir}/ExternalPOSReadinessPanel.jsx`), 'ExternalPOSReadinessPanel.jsx exists')
assert(fileExists(`${compDir}/ExternalPOSMappingPanel.jsx`), 'ExternalPOSMappingPanel.jsx exists')
assert(fileExists(`${compDir}/ExternalPOSSyncStatusBadge.jsx`), 'ExternalPOSSyncStatusBadge.jsx exists')
assert(fileExists(`${compDir}/VendorGatewayReadinessPanel.jsx`), 'VendorGatewayReadinessPanel.jsx exists')
assert(fileExists(`${compDir}/DistributorConnectorStatusPanel.jsx`), 'DistributorConnectorStatusPanel.jsx exists')
assert(fileExists(`${compDir}/ManufacturerConnectorStatusPanel.jsx`), 'ManufacturerConnectorStatusPanel.jsx exists')
assert(fileExists(`${compDir}/PurchaseOrderSubmissionGatewayPanel.jsx`), 'PurchaseOrderSubmissionGatewayPanel.jsx exists')
assert(fileExists(`${compDir}/OperationalSyncConsumerPanel.jsx`), 'OperationalSyncConsumerPanel.jsx exists')
assert(fileExists(`${compDir}/AvailabilityPushReadinessPanel.jsx`), 'AvailabilityPushReadinessPanel.jsx exists')
assert(fileExists(`${compDir}/CredentialRequiredNotice.jsx`), 'CredentialRequiredNotice.jsx exists')
assert(fileExists(`${compDir}/PurchaseOrderNotSubmittedNotice.jsx`), 'PurchaseOrderNotSubmittedNotice.jsx exists')
assert(fileExists(`${compDir}/ExternalSyncPendingNotice.jsx`), 'ExternalSyncPendingNotice.jsx exists')
assert(fileExists(`${compDir}/VendorCatalogSyncPreviewPanel.jsx`), 'VendorCatalogSyncPreviewPanel.jsx exists')
assert(fileExists(`${compDir}/POSProviderCapabilitiesPanel.jsx`), 'POSProviderCapabilitiesPanel.jsx exists')
assert(fileExists(`${compDir}/LOCCExternalOpsPanel.jsx`), 'LOCCExternalOpsPanel.jsx exists')

// UI vocabulary check
const credNotice = readFile(`${compDir}/CredentialRequiredNotice.jsx`)
assert(credNotice.includes('never returned') || credNotice.includes('never exposed') || credNotice.includes('never'), 'CredentialRequiredNotice states values never returned')
assert(credNotice.includes('credentials_required'), 'CredentialRequiredNotice shows credentials_required')

const poNotice = readFile(`${compDir}/PurchaseOrderNotSubmittedNotice.jsx`)
assert(poNotice.includes('purchase_order_not_submitted'), 'PurchaseOrderNotSubmittedNotice shows purchase_order_not_submitted')
assert(poNotice.includes('approval'), 'PurchaseOrderNotSubmittedNotice mentions approval')
assert(poNotice.includes('No auto'), 'PurchaseOrderNotSubmittedNotice says no auto purchasing')

const syncNotice = readFile(`${compDir}/ExternalSyncPendingNotice.jsx`)
assert(syncNotice.includes('external_sync_not_live'), 'ExternalSyncPendingNotice shows external_sync_not_live')
assert(syncNotice.includes('real_time_push_pending'), 'ExternalSyncPendingNotice shows real_time_push_pending')

const poSubmitPanel = readFile(`${compDir}/PurchaseOrderSubmissionGatewayPanel.jsx`)
assert(poSubmitPanel.includes('purchase_order_not_submitted'), 'POSubmissionGatewayPanel shows purchase_order_not_submitted')
assert(poSubmitPanel.includes('canSubmitLive: false'), 'POSubmissionGatewayPanel shows canSubmitLive: false')

const vendorPanel = readFile(`${compDir}/VendorGatewayReadinessPanel.jsx`)
assert(vendorPanel.includes('vendor_api_required'), 'VendorGatewayPanel shows vendor_api_required')
assert(vendorPanel.includes('No auto'), 'VendorGatewayPanel shows no auto-submission')

// ── Demo Page ─────────────────────────────────────────────────────────────────
assert(fileExists('src/pages/ExternalOperationsGatewayDemo.jsx'), 'ExternalOperationsGatewayDemo.jsx exists')
const demoPage = readFile('src/pages/ExternalOperationsGatewayDemo.jsx')
assert(demoPage.includes('external_sync_not_live'), 'demo page shows external_sync_not_live')
assert(demoPage.includes('real_time_push_pending'), 'demo page shows real_time_push_pending')
assert(demoPage.includes('purchase_order_not_submitted'), 'demo page shows purchase_order_not_submitted')
assert(demoPage.includes('canSubmitLive: false'), 'demo page shows canSubmitLive: false')
assert(demoPage.includes('database_required'), 'demo page shows database_required')
assert(demoPage.includes('vendor_api_required'), 'demo page shows vendor_api_required')
assert(demoPage.includes('external_pos_required'), 'demo page shows external_pos_required')
assert(demoPage.includes('Not final E.A.T. UI') || demoPage.includes('Component proof page') || demoPage.includes('proof'), 'demo page not claimed as final UI')
assert(demoPage.includes('autoApprovalDisabled: true'), 'demo page shows autoApprovalDisabled: true')

// ── Documentation ─────────────────────────────────────────────────────────────
assert(fileExists('docs/EXTERNAL_POS_VENDOR_GATEWAY_AND_LIVE_OPERATIONS.md'), 'EXTERNAL_POS_VENDOR_GATEWAY_AND_LIVE_OPERATIONS.md exists')
const doc = readFile('docs/EXTERNAL_POS_VENDOR_GATEWAY_AND_LIVE_OPERATIONS.md')
assert(doc.includes('EOCG'), 'doc mentions EOCG')
assert(doc.includes('external_sync_not_live'), 'doc describes external sync not live')
assert(doc.includes('real_time_push_pending'), 'doc describes real time push pending')
assert(doc.includes('approval'), 'doc describes approval requirement')
assert(doc.includes('purchase_order_not_submitted'), 'doc describes PO not submitted')
assert(doc.includes('Phase 19'), 'doc mentions what Phase 19 should handle')

// ── Package.json script ───────────────────────────────────────────────────────
const pkg = readFile('package.json')
assert(pkg.includes('verify:external-operations-gateway'), 'verify:external-operations-gateway in package.json')
assert(pkg.includes('verifyExternalOperationsGateway'), 'verifyExternalOperationsGateway.js referenced')

// ── No Fake Claims ────────────────────────────────────────────────────────────
const allServiceText = [leors, epcg, vcg, posg, osec, desb].join('\n')
assert(!allServiceText.includes('POS synced'), 'no fake POS synced claim')
assert(!allServiceText.includes('payment captured'), 'no fake payment captured claim')
assert(!allServiceText.includes('vendor order submitted successfully'), 'no fake vendor submission claim')
assert(!allServiceText.includes('canSubmitLive: true'), 'canSubmitLive never true in services')
assert(!allServiceText.includes('autoApprovalDisabled: false'), 'autoApprovalDisabled never false')

// ── Honest Missing-Credential Responses ──────────────────────────────────────
assert(leors.includes('external_pos_credentials_required'), 'external_pos_credentials_required on missing POS creds')
assert(leors.includes('vendor_credentials_required'), 'vendor_credentials_required on missing vendor creds')
assert(leors.includes('distributor_connection_required'), 'distributor_connection_required on missing distributor')
assert(leors.includes('manufacturer_connection_required'), 'manufacturer_connection_required on missing manufacturer')
assert(leors.includes('in_memory_only'), 'in_memory_only on missing DATABASE_URL')

// ── Phase 15/16/17 Integrity ──────────────────────────────────────────────────
assert(fileExists('server/services/reorder/receivingPersistenceService.js'), 'Phase 15 receivingPersistenceService intact')
assert(fileExists('server/services/environment/environmentReadinessService.js'), 'Phase 16 environmentReadinessService intact')
assert(fileExists('server/services/persistence/persistenceModeService.js'), 'Phase 16 persistenceModeService intact')
assert(fileExists('server/services/operations/roleSafetyGateway.js'), 'Phase 17 roleSafetyGateway intact')
assert(fileExists('server/services/operations/operationsDashboardService.js'), 'Phase 17 operationsDashboardService intact')
assert(fileExists('server/services/operations/syncCommandCenterService.js'), 'Phase 17 syncCommandCenterService intact')

// ── Protected Files ───────────────────────────────────────────────────────────
assert(fileExists('src/components/smokecraft/SmokeCraftAssetScreen.jsx'), 'SmokeCraftAssetScreen.jsx untouched')
assert(fileExists('src/components/smokecraft/SmokeCraftHotspotLayer.jsx'), 'SmokeCraftHotspotLayer.jsx untouched')
assert(fileExists('src/constants/session.js'), 'session.js untouched')
const sessionJs = readFile('src/constants/session.js')
assert(sessionJs.includes('VISIT_STRUCTURE'), 'VISIT_STRUCTURE in session.js')
assert(fileExists('src/utils/passportProgress.js'), 'passportProgress.js untouched')
assert(fileExists('src/utils/passportEntry.js'), 'passportEntry.js untouched')
assert(fileExists('src/constants/smokecraftJourney.js'), 'smokecraftJourney.js untouched')

// ── Summary ───────────────────────────────────────────────────────────────────
console.log(`\n  Passed: ${passed}`)
console.log(`  Failed: ${failed}`)
if (failures.length > 0) {
  console.log('\n  Failed assertions:')
  failures.forEach(f => console.log(`    - ${f}`))
  process.exit(1)
} else {
  console.log('\n  All assertions passed. Phase 18 EOCG verified.\n')
}
