import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..', '..')

let passed = 0
let failed = 0
const failures = []

function check(label, condition) {
  if (condition) { passed++ } else { failed++; failures.push(label); console.error(`  FAIL: ${label}`) }
}
function readFile(rel) {
  const abs = join(ROOT, rel)
  return existsSync(abs) ? readFileSync(abs, 'utf8') : ''
}
function fileExists(rel) { return existsSync(join(ROOT, rel)) }

console.log('\n=== EPRL Phase 16 Environment Readiness Verification ===\n')

// ─── Core Service Files ───
console.log('[ Core Service Files ]')
check('environmentReadinessService.js exists', fileExists('server/services/environment/environmentReadinessService.js'))
check('databaseConnectionManager.js exists',   fileExists('server/db/databaseConnectionManager.js'))
check('migrationReadinessService.js exists',   fileExists('server/db/migrationReadinessService.js'))
check('schemaReadinessService.js exists',      fileExists('server/db/schemaReadinessService.js'))
check('persistenceModeService.js exists',      fileExists('server/services/persistence/persistenceModeService.js'))
check('deploymentReadinessService.js exists',  fileExists('server/services/deployment/deploymentReadinessService.js'))
check('safeEnvironmentLogger.js exists',       fileExists('server/utils/safeEnvironmentLogger.js'))
check('eprlHealthController.js exists',        fileExists('server/controllers/eprlHealthController.js'))
check('eprlHealthRoutes.js exists',            fileExists('server/routes/eprlHealthRoutes.js'))

// ─── environmentReadinessService ───
console.log('\n[ environmentReadinessService ]')
const ers = readFile('server/services/environment/environmentReadinessService.js')
check('exports getEnvironmentMode',            ers.includes('export function getEnvironmentMode'))
check('exports getDatabaseUrlStatus',          ers.includes('export function getDatabaseUrlStatus'))
check('exports validateDatabaseUrlShape',      ers.includes('export function validateDatabaseUrlShape'))
check('exports detectDeploymentProvider',      ers.includes('export function detectDeploymentProvider'))
check('exports detectRuntimeMode',             ers.includes('export function detectRuntimeMode'))
check('exports buildEnvironmentReadinessReport', ers.includes('export function buildEnvironmentReadinessReport'))
check('exports buildDatabaseReadinessReport',  ers.includes('export function buildDatabaseReadinessReport'))
check('exports buildPersistenceModeReport',    ers.includes('export function buildPersistenceModeReport'))
check('exports buildSafeFallbackReport',       ers.includes('export function buildSafeFallbackReport'))
check('detects local_demo mode',               ers.includes('local_demo'))
check('detects local_database mode',           ers.includes('local_database'))
check('detects staging_database mode',         ers.includes('staging_database'))
check('detects production_database mode',      ers.includes('production_database'))
check('detects test_mode',                     ers.includes('test_mode'))
check('detects database_missing',              ers.includes('database_missing'))
check('detects database_invalid_url',          ers.includes('database_invalid_url'))
check('detects degraded_mode',                 ers.includes('degraded_mode'))
check('checks DATABASE_URL presence',          ers.includes('DATABASE_URL'))
check('checks postgres:// protocol',           ers.includes('postgres://'))
check('detects Railway provider',              ers.includes('railway'))
check('detects Render provider',               ers.includes('render'))
check('detects Vercel provider',               ers.includes('vercel'))
check('degradedMode false when DB present',    ers.includes('degradedMode'))
check('persistenceMode in_memory_only when no DB', ers.includes('in_memory_only'))
check('externalSyncNotLive in fallback',       ers.includes('externalSyncNotLive'))
check('vendorSyncNotLive in fallback',         ers.includes('vendorSyncNotLive'))
check('realTimePushPending in fallback',       ers.includes('realTimePushPending'))

// ─── databaseConnectionManager ───
console.log('\n[ databaseConnectionManager ]')
const dcm = readFile('server/db/databaseConnectionManager.js')
check('exports hasDatabaseUrl',                dcm.includes('export function hasDatabaseUrl'))
check('exports getDatabaseUrlRedacted',        dcm.includes('export function getDatabaseUrlRedacted'))
check('exports validateDatabaseConnection',    dcm.includes('export async function validateDatabaseConnection'))
check('exports testDatabaseConnection',        dcm.includes('export async function testDatabaseConnection'))
check('exports getDatabaseConnectionStatus',   dcm.includes('export function getDatabaseConnectionStatus'))
check('exports getDatabasePoolStatus',         dcm.includes('export function getDatabasePoolStatus'))
check('exports closeDatabaseConnection',       dcm.includes('export async function closeDatabaseConnection'))
check('exports buildDatabaseUnavailableResponse', dcm.includes('export function buildDatabaseUnavailableResponse'))
check('exports buildDatabaseRequiredResponse', dcm.includes('export function buildDatabaseRequiredResponse'))
check('missing_database_url status',           dcm.includes('missing_database_url'))
check('invalid_database_url status',           dcm.includes('invalid_database_url'))
check('connection_failed status',              dcm.includes('connection_failed'))
check('degradedMode in responses',             dcm.includes('degradedMode'))
check('databaseRequired in responses',         dcm.includes('databaseRequired'))
check('never exposes raw URL (uses redact)',   dcm.includes('redactDatabaseUrl'))
check('assertNoSecretLeak called',             dcm.includes('assertNoSecretLeak'))
check('pool_ready status',                     dcm.includes('pool_ready'))
check('pool_error status',                     dcm.includes('pool_error'))

// ─── migrationReadinessService ───
console.log('\n[ migrationReadinessService ]')
const mrs = readFile('server/db/migrationReadinessService.js')
check('exports getExpectedMigrations',         mrs.includes('export function getExpectedMigrations'))
check('exports getAppliedMigrations',          mrs.includes('export async function getAppliedMigrations'))
check('exports getLatestExpectedMigration',    mrs.includes('export function getLatestExpectedMigration'))
check('exports getLatestAppliedMigration',     mrs.includes('export async function getLatestAppliedMigration'))
check('exports detectPendingMigrations',       mrs.includes('export async function detectPendingMigrations'))
check('exports detectMigrationMismatch',       mrs.includes('export async function detectMigrationMismatch'))
check('exports validateRequiredTables',        mrs.includes('export async function validateRequiredTables'))
check('exports validateRequiredIndexes',       mrs.includes('export async function validateRequiredIndexes'))
check('exports buildMigrationReadinessReport', mrs.includes('export async function buildMigrationReadinessReport'))
check('exports buildMigrationPendingResponse', mrs.includes('export function buildMigrationPendingResponse'))
check('exports buildMigrationMismatchResponse', mrs.includes('export function buildMigrationMismatchResponse'))
check('migrations_ready status',              mrs.includes('migrations_ready'))
check('migrations_pending status',            mrs.includes('migrations_pending'))
check('migration_mismatch status',            mrs.includes('migration_mismatch'))
check('migration_table_missing status',       mrs.includes('migration_table_missing'))
check('required_tables_missing status',       mrs.includes('required_tables_missing'))
check('database_required fallback',           mrs.includes('database_required'))
check('reads migrations directory',           mrs.includes('MIGRATIONS_DIR') || mrs.includes('migrations'))
check('checks inventory_records table',       mrs.includes('inventory_records'))
check('checks operational_sync_events table', mrs.includes('operational_sync_events'))

// ─── schemaReadinessService ───
console.log('\n[ schemaReadinessService ]')
const srs = readFile('server/db/schemaReadinessService.js')
check('exports validateInventorySchema',       srs.includes('export async function validateInventorySchema'))
check('exports validateReorderSchema',         srs.includes('export async function validateReorderSchema'))
check('exports validateReceivingSchema',       srs.includes('export async function validateReceivingSchema'))
check('exports validateOperationalSyncSchema', srs.includes('export async function validateOperationalSyncSchema'))
check('exports validateVendorSchema',          srs.includes('export async function validateVendorSchema'))
check('exports validatePaymentSchema',         srs.includes('export async function validatePaymentSchema'))
check('exports validatePOS360Schema',          srs.includes('export async function validatePOS360Schema'))
check('exports buildSchemaReadinessReport',    srs.includes('export async function buildSchemaReadinessReport'))
check('schema_ready status',                   srs.includes('schema_ready'))
check('table_missing status',                  srs.includes('table_missing'))
check('database_required fallback',            srs.includes('database_required'))
check('checks inventory_records',              srs.includes('inventory_records'))
check('checks inventory_adjustments',          srs.includes('inventory_adjustments'))
check('checks reorder_approvals',              srs.includes('reorder_approvals'))
check('checks operational_sync_events',        srs.includes('operational_sync_events'))

// ─── persistenceModeService ───
console.log('\n[ persistenceModeService ]')
const pms = readFile('server/services/persistence/persistenceModeService.js')
check('exports getPersistenceMode',            pms.includes('export function getPersistenceMode'))
check('exports shouldUseDatabasePersistence',  pms.includes('export function shouldUseDatabasePersistence'))
check('exports shouldUseInMemoryFallback',     pms.includes('export function shouldUseInMemoryFallback'))
check('exports shouldAllowWritePersistence',   pms.includes('export function shouldAllowWritePersistence'))
check('exports shouldAllowReadPersistence',    pms.includes('export function shouldAllowReadPersistence'))
check('exports shouldBlockUnsafePersistenceClaim', pms.includes('export function shouldBlockUnsafePersistenceClaim'))
check('exports buildPersistenceModeResponse',  pms.includes('export function buildPersistenceModeResponse'))
check('exports assertNoFakePersistenceClaim',  pms.includes('export function assertNoFakePersistenceClaim'))
check('real_database mode',                    pms.includes('real_database'))
check('in_memory_only mode',                   pms.includes('in_memory_only'))
check('preview_only mode',                     pms.includes('preview_only'))
check('degraded_mode mode',                    pms.includes('degraded_mode'))
check('test_mode mode',                        pms.includes('test_mode'))
check('database_required mode',               pms.includes('database_required'))
check('checks DATABASE_URL for mode switch',  pms.includes('DATABASE_URL'))
check('assertNoFakePersistenceClaim throws',  pms.includes('throw new Error'))

// ─── deploymentReadinessService ───
console.log('\n[ deploymentReadinessService ]')
const drs = readFile('server/services/deployment/deploymentReadinessService.js')
check('exports buildDeploymentReadinessReport', drs.includes('export function buildDeploymentReadinessReport'))
check('exports getRequiredEnvironmentVariables', drs.includes('export function getRequiredEnvironmentVariables'))
check('exports getMissingEnvironmentVariables', drs.includes('export function getMissingEnvironmentVariables'))
check('exports getOptionalEnvironmentVariables', drs.includes('export function getOptionalEnvironmentVariables'))
check('exports getProductionBlockers',          drs.includes('export function getProductionBlockers'))
check('exports getStagingWarnings',             drs.includes('export function getStagingWarnings'))
check('exports buildRailwayReadinessChecklist', drs.includes('export function buildRailwayReadinessChecklist'))
check('exports buildPostgresReadinessChecklist', drs.includes('export function buildPostgresReadinessChecklist'))
check('checks DATABASE_URL in blockers',        drs.includes('DATABASE_URL'))
check('checks STRIPE_SECRET_KEY',              drs.includes('STRIPE_SECRET_KEY'))
check('checks STRIPE_WEBHOOK_SECRET',          drs.includes('STRIPE_WEBHOOK_SECRET'))
check('Railway provider in checklist',         drs.includes('railway'))
check('externalSyncNotLive: true in report',   drs.includes('externalSyncNotLive'))
check('vendorSyncNotLive: true in report',     drs.includes('vendorSyncNotLive'))
check('reorderNotSubmitted: true in report',   drs.includes('reorderNotSubmitted'))
check('distributorConnectionRequired: true',   drs.includes('distributorConnectionRequired'))

// ─── safeEnvironmentLogger ───
console.log('\n[ safeEnvironmentLogger ]')
const sel = readFile('server/utils/safeEnvironmentLogger.js')
check('exports redactSecret',                  sel.includes('export function redactSecret'))
check('exports redactDatabaseUrl',             sel.includes('export function redactDatabaseUrl'))
check('exports redactEnvValue',                sel.includes('export function redactEnvValue'))
check('exports buildSafeEnvSummary',           sel.includes('export function buildSafeEnvSummary'))
check('exports assertNoSecretLeak',            sel.includes('export function assertNoSecretLeak'))
check('redacts sk_live_ pattern',              sel.includes('sk_live_'))
check('redacts sk_test_ pattern',              sel.includes('sk_test_'))
check('redacts whsec_ pattern',                sel.includes('whsec_'))
check('redacts DATABASE_URL credentials',      sel.includes('DATABASE_URL') && sel.includes('redact'))
check('assertNoSecretLeak throws on leak',     sel.includes('throw new Error') || sel.includes('Secret leak'))
check('never logs raw secrets',                !sel.includes('console.log(process.env'))

// ─── Health Routes ───
console.log('\n[ Health Routes ]')
const hr = readFile('server/routes/eprlHealthRoutes.js')
check('has /environment route',  hr.includes('/environment'))
check('has /database route',     hr.includes('/database'))
check('has /migrations route',   hr.includes('/migrations'))
check('has /schema route',       hr.includes('/schema'))
check('has /persistence route',  hr.includes('/persistence'))
check('has /inventory route',    hr.includes('/inventory'))
check('has /reorder route',      hr.includes('/reorder'))
check('has /eat route',          hr.includes('/eat'))
check('has /pos360 route',       hr.includes('/pos360'))
check('has /ncie route',         hr.includes('/ncie'))
check('has /deployment route',   hr.includes('/deployment'))

// ─── Health Controller ───
console.log('\n[ Health Controller ]')
const hc = readFile('server/controllers/eprlHealthController.js')
check('handleEPRLEnvironment exported',    hc.includes('handleEPRLEnvironment'))
check('handleEPRLDatabase exported',       hc.includes('handleEPRLDatabase'))
check('handleEPRLMigrations exported',     hc.includes('handleEPRLMigrations'))
check('handleEPRLSchema exported',         hc.includes('handleEPRLSchema'))
check('handleEPRLPersistence exported',    hc.includes('handleEPRLPersistence'))
check('handleEPRLInventory exported',      hc.includes('handleEPRLInventory'))
check('handleEPRLReorder exported',        hc.includes('handleEPRLReorder'))
check('handleEPRLEAT exported',            hc.includes('handleEPRLEAT'))
check('handleEPRLPOS360 exported',         hc.includes('handleEPRLPOS360'))
check('handleEPRLNCIE exported',           hc.includes('handleEPRLNCIE'))
check('handleDeploymentReadiness exported', hc.includes('handleDeploymentReadiness'))
check('never exposes raw DATABASE_URL',    !hc.includes('process.env.DATABASE_URL // expose') && hc.includes('DATABASE_URL') === (hc.includes('DATABASE_URL')))
check('externalSyncNotLive in POS360 response', hc.includes('externalSyncNotLive'))
check('externalPOSRequired in POS360 response', hc.includes('externalPOSRequired'))

// ─── E.A.T. Hooks ───
console.log('\n[ E.A.T. EPRL Hooks ]')
const eat = readFile('server/services/eatCommandHubContract.js')
check('getEnvironmentReadinessHooks exported',        eat.includes('getEnvironmentReadinessHooks'))
check('getDatabaseConnectionReadinessHooks exported', eat.includes('getDatabaseConnectionReadinessHooks'))
check('getMigrationReadinessHooks exported',          eat.includes('getMigrationReadinessHooks'))
check('getSchemaReadinessHooks exported',             eat.includes('getSchemaReadinessHooks'))
check('getPersistenceModeReadinessHooks exported',    eat.includes('getPersistenceModeReadinessHooks'))
check('getDeploymentReadinessHooks exported',         eat.includes('getDeploymentReadinessHooks'))
check('getProductionBlockerReadinessHooks exported',  eat.includes('getProductionBlockerReadinessHooks'))
check('getRailwayPostgresReadinessHooks exported',    eat.includes('getRailwayPostgresReadinessHooks'))
check('EPRL hooks use try/catch',                     (eat.match(/try\s*\{/g) || []).length >= 14)
check('EPRL hooks return preview_fallback on error',  eat.includes('preview_fallback'))
check('EPRL hooks include hookId',                    eat.includes("hookId: '"))
check('EPRL hooks include system: eprl',              eat.includes("system: 'eprl'"))
check('EPRL hooks include degradedMode',              eat.includes('degradedMode'))
check('EPRL hooks include nextRequiredAction',        eat.includes('nextRequiredAction'))

// ─── UI Components ───
console.log('\n[ UI Components ]')
check('EnvironmentModeBadge.jsx exists',        fileExists('src/components/environment/EnvironmentModeBadge.jsx'))
check('DatabaseConnectionStatusPanel.jsx exists', fileExists('src/components/environment/DatabaseConnectionStatusPanel.jsx'))
check('MigrationReadinessPanel.jsx exists',     fileExists('src/components/environment/MigrationReadinessPanel.jsx'))
check('SchemaReadinessPanel.jsx exists',        fileExists('src/components/environment/SchemaReadinessPanel.jsx'))
check('PersistenceModePanel.jsx exists',        fileExists('src/components/environment/PersistenceModePanel.jsx'))
check('DeploymentReadinessPanel.jsx exists',    fileExists('src/components/environment/DeploymentReadinessPanel.jsx'))
check('ProductionBlockersPanel.jsx exists',     fileExists('src/components/environment/ProductionBlockersPanel.jsx'))
check('MissingEnvVarsPanel.jsx exists',         fileExists('src/components/environment/MissingEnvVarsPanel.jsx'))
check('DegradedModeNotice.jsx exists',          fileExists('src/components/environment/DegradedModeNotice.jsx'))
check('ExternalSyncPendingNotice.jsx exists',   fileExists('src/components/environment/ExternalSyncPendingNotice.jsx'))

const emb = readFile('src/components/environment/EnvironmentModeBadge.jsx')
check('EnvironmentModeBadge shows local_demo',         emb.includes('local_demo'))
check('EnvironmentModeBadge shows production_database', emb.includes('production_database'))
check('EnvironmentModeBadge shows database_missing',   emb.includes('database_missing'))

const dcsP = readFile('src/components/environment/DatabaseConnectionStatusPanel.jsx')
check('DatabaseConnectionStatusPanel shows database_required', dcsP.includes('database_required') || dcsP.includes('degradedMode'))

const dmn = readFile('src/components/environment/DegradedModeNotice.jsx')
check('DegradedModeNotice shows degraded_mode',       dmn.includes('degraded_mode'))
check('DegradedModeNotice shows in_memory_only',      dmn.includes('in_memory_only'))
check('DegradedModeNotice shows database_required',   dmn.includes('database_required'))

const esp = readFile('src/components/environment/ExternalSyncPendingNotice.jsx')
check('ExternalSyncPendingNotice shows external_sync_not_live',       esp.includes('external_sync_not_live'))
check('ExternalSyncPendingNotice shows vendor_sync_not_live',         esp.includes('vendor_sync_not_live'))
check('ExternalSyncPendingNotice shows distributor_connection_required', esp.includes('distributor_connection_required'))
check('ExternalSyncPendingNotice shows reorder_not_submitted',        esp.includes('reorder_not_submitted'))

// ─── Documentation ───
console.log('\n[ Documentation ]')
const doc = readFile('docs/LIVE_DATABASE_ENVIRONMENT_READINESS.md')
check('LIVE_DATABASE_ENVIRONMENT_READINESS.md exists', fileExists('docs/LIVE_DATABASE_ENVIRONMENT_READINESS.md'))
check('docs mention EPRL',                  doc.includes('EPRL'))
check('docs mention DATABASE_URL',          doc.includes('DATABASE_URL'))
check('docs mention degraded mode',         doc.includes('degraded'))
check('docs mention Railway',               doc.includes('Railway'))
check('docs mention Postgres',              doc.includes('Postgres') || doc.includes('postgres'))
check('docs mention migration readiness',   doc.includes('migration'))
check('docs mention schema readiness',      doc.includes('schema'))
check('docs mention health routes',         doc.includes('/api/health'))
check('docs mention external_pos_required', doc.includes('external_pos_required'))
check('docs mention vendor_sync_not_live',  doc.includes('vendor_sync_not_live'))
check('docs mention reorder_not_submitted', doc.includes('reorder_not_submitted'))
check('docs cover Phase 17 next steps',     doc.includes('Phase 17'))

// ─── No Secret Exposure ───
console.log('\n[ No Secret Exposure ]')
const allFiles = [ers, dcm, mrs, srs, pms, drs, sel, hc]
check('no raw sk_live_ leaked in non-logger files', [ers, dcm, mrs, srs, pms, drs, hc].every(f => !f.includes("sk_live_")))
check('no process.env.STRIPE_SECRET_KEY logged', allFiles.every(f => !f.includes('console.log(process.env.STRIPE_SECRET_KEY')))
check('no full DATABASE_URL in responses',  hc.includes('getDatabaseUrlRedacted') || hc.includes('redacted'))
check('assertNoSecretLeak used',            dcm.includes('assertNoSecretLeak'))

// ─── Phase 15 Not Broken ───
console.log('\n[ Phase 15 Integrity ]')
check('inventoryPersistenceService.js still exists',      fileExists('server/services/inventory/inventoryPersistenceService.js'))
check('inventoryAdjustmentPersistenceService.js exists',  fileExists('server/services/inventory/inventoryAdjustmentPersistenceService.js'))
check('receivingPersistenceService.js still exists',      fileExists('server/services/reorder/receivingPersistenceService.js'))
check('operationalSyncEventService.js still exists',      fileExists('server/services/sync/operationalSyncEventService.js'))
check('purchaseOrderPersistenceService.js still exists',  fileExists('server/services/reorder/purchaseOrderPersistenceService.js'))
check('migration 028 still exists', fileExists('server/db/migrations/028_operational_inventory_persistence_and_sync.sql'))

// ─── Protected Files ───
console.log('\n[ Protected File Integrity ]')
const smk = readFile('src/components/smokecraft/SmokeCraftAssetScreen.jsx')
check('SmokeCraftAssetScreen.jsx intact', smk.length > 100)
const sess = readFile('src/constants/session.js')
check('session.js VISIT_STRUCTURE intact', sess.includes('VISIT_STRUCTURE'))

// ─── server/index.js wired ───
console.log('\n[ Server Wiring ]')
const idx = readFile('server/index.js')
check('eprlHealthRoutes imported in index.js',  idx.includes('eprlHealthRoutes'))
check('/api/health mounted for EPRL routes',     idx.includes("'/api/health'") || idx.includes('"/api/health"'))

// ─── Summary ───
console.log(`\n=== Results: ${passed} passed, ${failed} failed ===`)
if (failures.length > 0) {
  console.log('\nFailed checks:')
  failures.forEach(f => console.log(`  - ${f}`))
  process.exit(1)
} else {
  console.log('\nAll Phase 16 EPRL checks passed.')
}
