// Phase E.9 Verification — NOVEE OS Documentation Portal
import { readFileSync } from 'fs'
import { resolve } from 'path'

let passed = 0
let failed = 0
const failures = []

function check(label, condition) {
  if (condition) {
    passed++
    console.log(`  ✓ ${label}`)
  } else {
    failed++
    failures.push(label)
    console.log(`  ✗ FAIL: ${label}`)
  }
}

function read(rel) {
  try { return readFileSync(resolve(process.cwd(), rel), 'utf8') } catch { return '' }
}

console.log('\n=== Phase E.9 — NOVEE OS Documentation Portal Verification ===\n')

// --- Migration ---
console.log('[ Migration: 067_novee_os_documentation_portal.sql ]')
const migration = read('server/db/migrations/067_novee_os_documentation_portal.sql')
check('Migration file exists', migration.length > 100)
check('novee_os_documentation_library_registry table', migration.includes('novee_os_documentation_library_registry'))
check('novee_os_documentation_article_registry table', migration.includes('novee_os_documentation_article_registry'))
check('novee_os_documentation_content_block_registry table', migration.includes('novee_os_documentation_content_block_registry'))
check('novee_os_documentation_search_index table', migration.includes('novee_os_documentation_search_index'))
check('novee_os_documentation_review_registry table', migration.includes('novee_os_documentation_review_registry'))
check('novee_os_documentation_export_registry table', migration.includes('novee_os_documentation_export_registry'))
check('novee_os_documentation_safe_claims_registry table', migration.includes('novee_os_documentation_safe_claims_registry'))
check('novee_os_documentation_seeded_manual_content_registry table', migration.includes('novee_os_documentation_seeded_manual_content_registry'))
check('novee_os_documentation_audit_log table', migration.includes('novee_os_documentation_audit_log'))
check('published DEFAULT FALSE in library', migration.includes("published BOOLEAN NOT NULL DEFAULT FALSE"))
check('client_ready DEFAULT FALSE', migration.includes('client_ready BOOLEAN NOT NULL DEFAULT FALSE'))
check('staff_ready DEFAULT FALSE', migration.includes('staff_ready BOOLEAN NOT NULL DEFAULT FALSE'))
check('approved DEFAULT FALSE', migration.includes('approved BOOLEAN NOT NULL DEFAULT FALSE'))
check('approved_for_client DEFAULT FALSE', migration.includes('approved_for_client BOOLEAN NOT NULL DEFAULT FALSE'))
check('approved_for_export DEFAULT FALSE', migration.includes('approved_for_export BOOLEAN NOT NULL DEFAULT FALSE'))
check('needs_human_review DEFAULT TRUE', migration.includes('needs_human_review BOOLEAN NOT NULL DEFAULT TRUE'))
check('full_content_required DEFAULT TRUE', migration.includes('full_content_required BOOLEAN NOT NULL DEFAULT TRUE'))
check('review_required DEFAULT TRUE', migration.includes('review_required BOOLEAN NOT NULL DEFAULT TRUE'))
check('evidence_present DEFAULT FALSE', migration.includes('evidence_present BOOLEAN NOT NULL DEFAULT FALSE'))
check('investor_ready_draft DEFAULT FALSE', migration.includes('investor_ready_draft BOOLEAN NOT NULL DEFAULT FALSE'))
check('No DROP TABLE statements', !migration.includes('DROP TABLE'))

// --- Feature Flags ---
console.log('\n[ Feature Flags: noveeOSDocumentationPortalFeatureFlags.js ]')
const flags = read('server/config/noveeOSDocumentationPortalFeatureFlags.js')
check('Flags file exists', flags.length > 100)
check('NOVEE_DOCUMENTATION_PORTAL_ENABLED: true', flags.includes('NOVEE_DOCUMENTATION_PORTAL_ENABLED: true'))
check('NOVEE_DOCUMENTATION_SEEDED_CONTENT_ENABLED: true', flags.includes('NOVEE_DOCUMENTATION_SEEDED_CONTENT_ENABLED: true'))
check('NOVEE_DOCUMENTATION_PUBLICATION_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_PUBLICATION_ENABLED: false'))
check('NOVEE_DOCUMENTATION_CLIENT_READY_PUBLICATION_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_CLIENT_READY_PUBLICATION_ENABLED: false'))
check('NOVEE_DOCUMENTATION_STAFF_READY_PUBLICATION_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_STAFF_READY_PUBLICATION_ENABLED: false'))
check('NOVEE_DOCUMENTATION_EXPORT_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_EXPORT_ENABLED: false'))
check('NOVEE_DOCUMENTATION_EMAIL_EXPORT_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_EMAIL_EXPORT_ENABLED: false'))
check('NOVEE_DOCUMENTATION_PDF_EXPORT_ENABLED: false', flags.includes('NOVEE_DOCUMENTATION_PDF_EXPORT_ENABLED: false'))
check('NOVEE_DOCUMENTATION_SAFE_CLAIMS_ENFORCED: true', flags.includes('NOVEE_DOCUMENTATION_SAFE_CLAIMS_ENFORCED: true'))
check('NOVEE_DOCUMENTATION_FAKE_COMPLETION_CLAIMS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_FAKE_COMPLETION_CLAIMS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_FAKE_PUBLICATION_CLAIMS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_FAKE_PUBLICATION_CLAIMS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_FAKE_CERTIFICATION_CLAIMS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_FAKE_CERTIFICATION_CLAIMS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_FAKE_AMBI_HARDWARE_CLAIMS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_FAKE_AMBI_HARDWARE_CLAIMS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_UNSAFE_SMOKECRAFT_PRODUCTION_READY_CLAIMS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_UNSAFE_SMOKECRAFT_PRODUCTION_READY_CLAIMS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_EMPTY_MANUALS_BLOCKED: true', flags.includes('NOVEE_DOCUMENTATION_EMPTY_MANUALS_BLOCKED: true'))
check('NOVEE_DOCUMENTATION_AUDIT_LOGGING_ENABLED: true', flags.includes('NOVEE_DOCUMENTATION_AUDIT_LOGGING_ENABLED: true'))
check('getNoveeOSDocumentationPortalFlags exported', flags.includes('export function getNoveeOSDocumentationPortalFlags'))
check('export default NOVEE_OS_DOCUMENTATION_PORTAL_FLAGS', flags.includes('export default NOVEE_OS_DOCUMENTATION_PORTAL_FLAGS'))

// --- Contracts ---
console.log('\n[ Contracts: noveeOSDocumentationPortalContracts.js ]')
const contracts = read('server/services/noveeOS/noveeOSDocumentationPortalContracts.js')
check('Contracts file exists', contracts.length > 500)
check('DEFAULT_DOCUMENTATION_LIBRARY exported', contracts.includes('export const DEFAULT_DOCUMENTATION_LIBRARY'))
check('DEFAULT_SEEDED_MANUAL_CONTENT exported', contracts.includes('export const DEFAULT_SEEDED_MANUAL_CONTENT'))
check('DEFAULT_SAFE_CLAIMS exported', contracts.includes('export const DEFAULT_SAFE_CLAIMS'))
check('21+ library records', (contracts.match(/doc_key:/g) || []).length >= 21)
check('smokecraft_360_venue_guide in library', contracts.includes('smokecraft_360_venue_guide'))
check('smokecraft_360_staff_guide in library', contracts.includes('smokecraft_360_staff_guide'))
check('smokecraft_360_guest_flow_guide in library', contracts.includes('smokecraft_360_guest_flow_guide'))
check('smokecraft_360_pilot_readiness_guide in library', contracts.includes('smokecraft_360_pilot_readiness_guide'))
check('passport_360_connection_guide in library', contracts.includes('passport_360_connection_guide'))
check('pos360_staff_guide in library', contracts.includes('pos360_staff_guide'))
check('eat360_manager_guide in library', contracts.includes('eat360_manager_guide'))
check('Seeded content for smokecraft venue guide', contracts.includes('sc_venue_'))
check('Seeded content for smokecraft staff guide', contracts.includes('sc_staff_'))
check('Seeded content for smokecraft guest guide', contracts.includes('sc_guest_'))
check('Seeded content for smokecraft pilot guide', contracts.includes('sc_pilot_'))
check('Seeded content for passport guide', contracts.includes('passport_overview'))
check('Seeded content for pos360 guide', contracts.includes('pos360_overview'))
check('Seeded content for eat manager guide', contracts.includes('eat_manager_overview'))
check('Seeded content for safe claims guide', contracts.includes('safe_claims_overview'))
check('Seeded content for troubleshooting guide', contracts.includes('trouble_overview'))
check('safe_claim block type in seeded content', contracts.includes("block_type: 'safe_claim'"))
check('unsafe_claim block type in seeded content', contracts.includes("block_type: 'unsafe_claim'"))
check('setup_instruction block type in seeded content', contracts.includes("block_type: 'setup_instruction'"))
check('readiness_checklist block type in seeded content', contracts.includes("block_type: 'readiness_checklist'"))
check('assertNoFakeManualCompletionClaims exported', contracts.includes('export function assertNoFakeManualCompletionClaims'))
check('assertNoFakeDocumentationPublicationClaims exported', contracts.includes('export function assertNoFakeDocumentationPublicationClaims'))
check('assertNoFakeCertificationDocumentationClaims exported', contracts.includes('export function assertNoFakeCertificationDocumentationClaims'))
check('assertNoUnsafeSmokeCraftProductionReadyClaims exported', contracts.includes('export function assertNoUnsafeSmokeCraftProductionReadyClaims'))
check('assertNoSensitiveDocumentationData exported', contracts.includes('export function assertNoSensitiveDocumentationData'))
check('assertNoEmptyManualRecords exported', contracts.includes('export function assertNoEmptyManualRecords'))
check('assertRequiredManualsHaveSeededContent exported', contracts.includes('export function assertRequiredManualsHaveSeededContent'))
check('validateDocumentationLibraryPayload exported', contracts.includes('export function validateDocumentationLibraryPayload'))
check('validateDocumentationArticlePayload exported', contracts.includes('export function validateDocumentationArticlePayload'))
check('validateDocumentationContentBlockPayload exported', contracts.includes('export function validateDocumentationContentBlockPayload'))
check('validateDocumentationReviewPayload exported', contracts.includes('export function validateDocumentationReviewPayload'))
check('validateDocumentationExportPayload exported', contracts.includes('export function validateDocumentationExportPayload'))
check('validateDocumentationSafeClaimPayload exported', contracts.includes('export function validateDocumentationSafeClaimPayload'))
check('validateSeededManualContentPayload exported', contracts.includes('export function validateSeededManualContentPayload'))

// --- Service ---
console.log('\n[ Service: noveeOSDocumentationPortalService.js ]')
const service = read('server/services/noveeOS/noveeOSDocumentationPortalService.js')
check('Service file exists', service.length > 500)
check('getDocumentationPortalSummary exported', service.includes('export async function getDocumentationPortalSummary'))
check('listDocumentationLibrary exported', service.includes('export async function listDocumentationLibrary'))
check('getDocumentationLibraryItem exported', service.includes('export async function getDocumentationLibraryItem'))
check('createDocumentationLibraryItemPreview exported', service.includes('export async function createDocumentationLibraryItemPreview'))
check('updateDocumentationLibraryStatusPreview exported', service.includes('export async function updateDocumentationLibraryStatusPreview'))
check('listDocumentationArticles exported', service.includes('export async function listDocumentationArticles'))
check('getDocumentationArticle exported', service.includes('export async function getDocumentationArticle'))
check('createDocumentationArticlePreview exported', service.includes('export async function createDocumentationArticlePreview'))
check('updateDocumentationArticleStatusPreview exported', service.includes('export async function updateDocumentationArticleStatusPreview'))
check('listDocumentationContentBlocks exported', service.includes('export async function listDocumentationContentBlocks'))
check('getDocumentationContentBlock exported', service.includes('export async function getDocumentationContentBlock'))
check('createDocumentationContentBlockPreview exported', service.includes('export async function createDocumentationContentBlockPreview'))
check('updateDocumentationContentBlockStatusPreview exported', service.includes('export async function updateDocumentationContentBlockStatusPreview'))
check('listSeededManualContent exported', service.includes('export async function listSeededManualContent'))
check('getSeededManualContent exported', service.includes('export async function getSeededManualContent'))
check('createSeededManualContentPreview exported', service.includes('export async function createSeededManualContentPreview'))
check('updateSeededManualContentStatusPreview exported', service.includes('export async function updateSeededManualContentStatusPreview'))
check('listDocumentationSearchIndex exported', service.includes('export async function listDocumentationSearchIndex'))
check('searchDocumentation exported', service.includes('export async function searchDocumentation'))
check('listDocumentationReviews exported', service.includes('export async function listDocumentationReviews'))
check('getDocumentationReview exported', service.includes('export async function getDocumentationReview'))
check('createDocumentationReviewPreview exported', service.includes('export async function createDocumentationReviewPreview'))
check('updateDocumentationReviewStatusPreview exported', service.includes('export async function updateDocumentationReviewStatusPreview'))
check('listDocumentationExports exported', service.includes('export async function listDocumentationExports'))
check('getDocumentationExport exported', service.includes('export async function getDocumentationExport'))
check('createDocumentationExportPreview exported', service.includes('export async function createDocumentationExportPreview'))
check('updateDocumentationExportStatusPreview exported', service.includes('export async function updateDocumentationExportStatusPreview'))
check('listDocumentationSafeClaims exported', service.includes('export async function listDocumentationSafeClaims'))
check('getDocumentationSafeClaim exported', service.includes('export async function getDocumentationSafeClaim'))
check('createDocumentationSafeClaimPreview exported', service.includes('export async function createDocumentationSafeClaimPreview'))
check('updateDocumentationSafeClaimStatusPreview exported', service.includes('export async function updateDocumentationSafeClaimStatusPreview'))
check('getDocumentationReadinessScore exported', service.includes('export async function getDocumentationReadinessScore'))
check('getDocumentationBlockers exported', service.includes('export async function getDocumentationBlockers'))
check('getSafeDocumentationClaims exported', service.includes('export async function getSafeDocumentationClaims'))
check('getManualContentCompletenessSummary exported', service.includes('export async function getManualContentCompletenessSummary'))
check('writeDocumentationAuditEvent exported', service.includes('export async function writeDocumentationAuditEvent'))
check('getDocumentationAuditLog exported', service.includes('export async function getDocumentationAuditLog'))
check('getDocumentationFeatureFlagSnapshot exported', service.includes('export async function getDocumentationFeatureFlagSnapshot'))
check('validateDocumentationPortalReadiness exported', service.includes('export async function validateDocumentationPortalReadiness'))
check('published: false hardcoded in service', service.includes('published: false'))
check('client_ready: false hardcoded in service', service.includes('client_ready: false'))
check('documentation_ready: false hardcoded in service', service.includes('documentation_ready: false'))
check('BUILD_ONLY_DOCUMENTATION_NOT_PUBLISHED status', service.includes('BUILD_ONLY_DOCUMENTATION_NOT_PUBLISHED'))
check('localFallback defined', service.includes('const localFallback'))
check('isDbAvailable defined', service.includes('async function isDbAvailable'))

// --- Controller ---
console.log('\n[ Controller: noveeOSDocumentationPortalController.js ]')
const controller = read('server/controllers/noveeOSDocumentationPortalController.js')
check('Controller file exists', controller.length > 200)
check('getPortalSummary exported', controller.includes('export async function getPortalSummary'))
check('listLibrary exported', controller.includes('export async function listLibrary'))
check('getLibraryItem exported', controller.includes('export async function getLibraryItem'))
check('createLibraryItemPreview exported', controller.includes('export async function createLibraryItemPreview'))
check('listArticles exported', controller.includes('export async function listArticles'))
check('listSeededManualContent exported', controller.includes('export async function listSeededManualContent'))
check('searchDocumentation exported', controller.includes('export async function searchDocumentation'))
check('listReviews exported', controller.includes('export async function listReviews'))
check('listExports exported', controller.includes('export async function listExports'))
check('listSafeClaims exported', controller.includes('export async function listSafeClaims'))
check('getReadinessScore exported', controller.includes('export async function getReadinessScore'))
check('getBlockers exported', controller.includes('export async function getBlockers'))
check('getManualContentCompletenessSummary exported', controller.includes('export async function getManualContentCompletenessSummary'))
check('getAuditLog exported', controller.includes('export async function getAuditLog'))
check('getFeatureFlagSnapshot exported', controller.includes('export async function getFeatureFlagSnapshot'))
check('validatePortalReadiness exported', controller.includes('export async function validatePortalReadiness'))
check('wrap helper present', controller.includes('const wrap ='))
check('safeClaim in wrap', controller.includes("safeClaim: 'documentation_portal_exists'"))
check('published: false in wrap', controller.includes('published: false'))
check('clientReady: false in wrap', controller.includes('clientReady: false'))
check('documentationReady: false in wrap', controller.includes('documentationReady: false'))
check('ok500 helper present', controller.includes('const ok500 ='))
check('actorId helper present', controller.includes('const actorId ='))
check('tenantId helper present', controller.includes('const tenantId ='))

// --- Routes ---
console.log('\n[ Routes: noveeOSDocumentationPortalRoutes.js ]')
const routes = read('server/routes/noveeOSDocumentationPortalRoutes.js')
check('Routes file exists', routes.length > 100)
check('/summary route', routes.includes("'/summary'"))
check('/library route', routes.includes("'/library'"))
check('/articles route', routes.includes("'/articles'"))
check('/content-blocks route', routes.includes("'/content-blocks'"))
check('/seeded-manual-content route', routes.includes("'/seeded-manual-content'"))
check('/search-index route', routes.includes("'/search-index'"))
check('/search route', routes.includes("'/search'"))
check('/reviews route', routes.includes("'/reviews'"))
check('/exports route', routes.includes("'/exports'"))
check('/safe-claims route', routes.includes("'/safe-claims'"))
check('/manual-content-completeness route', routes.includes("'/manual-content-completeness'"))
check('/readiness-score route', routes.includes("'/readiness-score'"))
check('/blockers route', routes.includes("'/blockers'"))
check('/audit-log route', routes.includes("'/audit-log'"))
check('/feature-flags route', routes.includes("'/feature-flags'"))
check('/validate-readiness route', routes.includes("'/validate-readiness'"))
check('canAccessPOS3 on POST /library', routes.includes('canAccessPOS3, ctrl.createLibraryItemPreview'))
check('canAccessPOS3 on POST /articles', routes.includes('canAccessPOS3, ctrl.createArticlePreview'))
check('canAccessPOS3 on POST /seeded-manual-content', routes.includes('canAccessPOS3, ctrl.createSeededManualContentPreview'))
check('export default router', routes.includes('export default router'))

// --- Frontend ---
console.log('\n[ Frontend: DocumentationPortal.jsx ]')
const frontend = read('src/pages/noveeOS/DocumentationPortal.jsx')
check('Frontend file exists', frontend.length > 500)
check('export default function DocumentationPortal', frontend.includes('export default function DocumentationPortal'))
check('Panel A — Summary', frontend.includes("'A'"))
check('Panel B — Library', frontend.includes("'B'"))
check('Panel C — Articles', frontend.includes("'C'"))
check('Panel D — Seeded Content', frontend.includes("'D'"))
check('Panel E — Content Blocks', frontend.includes("'E'"))
check('Panel F — Search', frontend.includes("'F'"))
check('Panel G — Reviews', frontend.includes("'G'"))
check('Panel H — Exports', frontend.includes("'H'"))
check('Panel I — Safe Claims', frontend.includes("'I'"))
check('Panel J — Completeness', frontend.includes("'J'"))
check('Panel K — Blockers', frontend.includes("'K'"))
check('Panel L — Safe Panel', frontend.includes("'L'"))
check('Panel M — Audit + Flags', frontend.includes("'M'"))
check('BUILD PHASE banner present', frontend.includes('BUILD PHASE'))
check('Publication NOT enabled in frontend', frontend.includes('Publication is NOT enabled'))
check('Export NOT enabled in frontend', frontend.includes('Export is NOT enabled'))
check('Human review required in frontend', frontend.includes('human review'))
check('Seeded content ready label', frontend.includes('seededContentReady'))
check('/api/novee-os/documentation-portal base URL', frontend.includes('/api/novee-os/documentation-portal'))
check('No fake published: true in frontend', !frontend.includes('published: true'))
check('No fake clientReady: true in frontend', !frontend.includes('clientReady: true'))

// --- server/index.js wiring ---
console.log('\n[ Wiring: server/index.js ]')
const serverIndex = read('server/index.js')
check('noveeOSDocumentationPortalRoutes imported', serverIndex.includes('noveeOSDocumentationPortalRoutes'))
check('Mounted at /api/novee-os/documentation-portal', serverIndex.includes('/api/novee-os/documentation-portal'))

// --- src/App.jsx wiring ---
console.log('\n[ Wiring: src/App.jsx ]')
const appJsx = read('src/App.jsx')
check('DocumentationPortal imported in App.jsx', appJsx.includes('DocumentationPortal'))
check('novee-os/documentation-portal route in App.jsx', appJsx.includes('novee-os/documentation-portal'))

// --- NoveeOSCommandCenter.jsx ---
console.log('\n[ Wiring: NoveeOSCommandCenter.jsx ]')
const commandCenter = read('src/pages/noveeOS/NoveeOSCommandCenter.jsx')
check('E.9 listed in NoveeOSCommandCenter', commandCenter.includes('E.9'))
check('documentation-portal route in NoveeOSCommandCenter', commandCenter.includes('documentation-portal'))

// --- NoveeHome.jsx ---
console.log('\n[ Wiring: src/pages/NoveeHome.jsx ]')
const noveeHome = read('src/pages/NoveeHome.jsx')
check('documentation-portal link in NoveeHome.jsx', noveeHome.includes('documentation-portal'))

// --- package.json ---
console.log('\n[ package.json ]')
const pkg = read('package.json')
check('verify:phase-e9-documentation-portal script', pkg.includes('verify:phase-e9-documentation-portal'))

// --- Docs ---
console.log('\n[ Docs: PHASE_E_9_DOCUMENTATION_PORTAL.md ]')
const docs = read('docs/PHASE_E_9_DOCUMENTATION_PORTAL.md')
check('Docs file exists', docs.length > 100)
check('Phase E.9 mentioned in docs', docs.includes('E.9'))

// --- Summary ---
console.log(`\n=== RESULT: ${passed} passed / ${passed + failed} total ===`)
if (failures.length > 0) {
  console.log('\nFailed checks:')
  failures.forEach(f => console.log(`  ✗ ${f}`))
  process.exit(1)
} else {
  console.log('\nAll checks passed. Phase E.9 verification complete.')
  process.exit(0)
}
