import { readFileSync } from 'fs';
import { resolve } from 'path';

const root = resolve(process.cwd());
let passed = 0;
let failed = 0;

function check(label, condition) {
  if (condition) {
    console.log(`  PASSED  ${label}`);
    passed++;
  } else {
    console.log(`  FAILED  ${label}`);
    failed++;
  }
}

const mig = readFileSync(`${root}/server/db/migrations/052_crafthub_dashboard_module_launcher_shell.sql`, 'utf8');
const contracts = readFileSync(`${root}/server/services/crafthub/craftHubDashboardContracts.js`, 'utf8');
const flags = readFileSync(`${root}/server/config/craftHubDashboardFeatureFlags.js`, 'utf8');
const locales = readFileSync(`${root}/src/locales/craftHubDashboard.js`, 'utf8');
const service = readFileSync(`${root}/server/services/crafthub/craftHubDashboardService.js`, 'utf8');
const controller = readFileSync(`${root}/server/controllers/craftHubDashboardController.js`, 'utf8');
const routes = readFileSync(`${root}/server/routes/craftHubDashboardRoutes.js`, 'utf8');
const ui = readFileSync(`${root}/src/pages/crafthub/CraftHubDashboard.jsx`, 'utf8');
const serverIndex = readFileSync(`${root}/server/index.js`, 'utf8');
const appJsx = readFileSync(`${root}/src/App.jsx`, 'utf8');
const pkgJson = readFileSync(`${root}/package.json`, 'utf8');

// ── MIGRATION ──────────────────────────────────────────────────────────────────
console.log('\n── Migration 052 ──');
check('migration: file exists', mig.length > 100);
check('migration: no DROP TABLE', !mig.includes('DROP TABLE'));
check('migration: no TRUNCATE', !mig.includes('TRUNCATE'));
check('migration: safe migration comment', mig.includes('Safe migration: no destructive DDL, no truncation'));
check('migration: crafthub_dashboard_sessions table', mig.includes('crafthub_dashboard_sessions'));
check('migration: crafthub_module_launcher_registry table', mig.includes('crafthub_module_launcher_registry'));
check('migration: crafthub_navigation_shell_config table', mig.includes('crafthub_navigation_shell_config'));
check('migration: crafthub_premium_experience_hub table', mig.includes('crafthub_premium_experience_hub'));
check('migration: crafthub_dashboard_widgets table', mig.includes('crafthub_dashboard_widgets'));
check('migration: crafthub_module_roadmap table', mig.includes('crafthub_module_roadmap'));
check('migration: crafthub_marketplace_catalog table', mig.includes('crafthub_marketplace_catalog'));
check('migration: crafthub_marketplace_purchases table', mig.includes('crafthub_marketplace_purchases'));
check('migration: crafthub_quick_actions table', mig.includes('crafthub_quick_actions'));
check('migration: crafthub_activity_feed table', mig.includes('crafthub_activity_feed'));
check('migration: crafthub_notification_center table', mig.includes('crafthub_notification_center'));
check('migration: crafthub_search_index table', mig.includes('crafthub_search_index'));
check('migration: crafthub_onboarding_checklist table', mig.includes('crafthub_onboarding_checklist'));
check('migration: crafthub_announcements table', mig.includes('crafthub_announcements'));
check('migration: crafthub_module_health_checks table', mig.includes('crafthub_module_health_checks'));
check('migration: crafthub_feature_flags_overrides table', mig.includes('crafthub_feature_flags_overrides'));
check('migration: crafthub_user_preferences table', mig.includes('crafthub_user_preferences'));
check('migration: crafthub_module_entitlements table', mig.includes('crafthub_module_entitlements'));
check('migration: crafthub_audit_log table', mig.includes('crafthub_audit_log'));
check('migration: crafthub_api_keys table', mig.includes('crafthub_api_keys'));
check('migration: crafthub_integration_connectors table', mig.includes('crafthub_integration_connectors'));
check('migration: crafthub_platform_health_status table', mig.includes('crafthub_platform_health_status'));
check('migration: 22 CREATE TABLE statements', (mig.match(/CREATE TABLE IF NOT EXISTS/g) || []).length >= 22);
check('migration: UUID primary keys', mig.includes('UUID PRIMARY KEY DEFAULT gen_random_uuid()'));
check('migration: idempotency_key UNIQUE', mig.includes('idempotency_key TEXT UNIQUE'));
check('migration: exposes_private_data columns', (mig.match(/exposes_private_data/g) || []).length >= 10);
check('migration: live_mode_enabled columns', mig.includes('live_mode_enabled BOOLEAN DEFAULT FALSE'));
check('migration: activation_required columns', mig.includes('activation_required BOOLEAN DEFAULT TRUE'));
check('migration: placeholder_mode columns', mig.includes('placeholder_mode BOOLEAN DEFAULT TRUE'));
check('migration: module_installed default false', mig.includes('is_installed BOOLEAN DEFAULT FALSE'));
check('migration: module_activated default false', mig.includes('is_activated BOOLEAN DEFAULT FALSE'));
check('migration: marketplace_purchase_completed default false', mig.includes('marketplace_purchase_completed BOOLEAN DEFAULT FALSE'));
check('migration: billing_connected default false', mig.includes('billing_connected BOOLEAN DEFAULT FALSE'));
check('migration: license_verified default false', mig.includes('license_verified BOOLEAN DEFAULT FALSE'));
check('migration: launch_allowed default false', mig.includes('launch_allowed BOOLEAN DEFAULT FALSE'));
check('migration: unique index on module launcher', mig.includes('uidx_crafthub_module_launcher_tenant_key'));
check('migration: unique index on entitlements', mig.includes('uidx_crafthub_module_entitlements_tenant_module'));
check('migration: unique index on feature flags', mig.includes('uidx_crafthub_feature_flags_tenant_key'));
check('migration: created_at timestamp', mig.includes('created_at TIMESTAMPTZ DEFAULT NOW()'));
check('migration: updated_at timestamp', mig.includes('updated_at TIMESTAMPTZ DEFAULT NOW()'));

// ── CONTRACTS ──────────────────────────────────────────────────────────────────
console.log('\n── Contracts ──');
check('contracts: file exists', contracts.length > 100);
check('contracts: contains_secrets: false comment', contracts.includes('contains_secrets: false'));
check('contracts: CRAFTHUB_MODULE_KEYS export', contracts.includes('export const CRAFTHUB_MODULE_KEYS'));
check('contracts: 15 module keys', (contracts.match(/novee_os_module_registry|novee_os_tenant_governance|novee_os_billing_governance|novee_os_security_governance|pos360_platform|smokecraft_experience|pourcraft_beverage|eat_ai_system|passport_connections|loyalty_rewards|venue_admin|inventory_management|reports_analytics|external_integrations|future_module_placeholder/g) || []).length >= 15);
check('contracts: CRAFTHUB_MODULE_CATEGORIES export', contracts.includes('export const CRAFTHUB_MODULE_CATEGORIES'));
check('contracts: CRAFTHUB_MODULE_STATUSES export', contracts.includes('export const CRAFTHUB_MODULE_STATUSES'));
check('contracts: local_preview status', contracts.includes('local_preview'));
check('contracts: activation_required status', contracts.includes('activation_required'));
check('contracts: placeholder status', contracts.includes('placeholder'));
check('contracts: CRAFTHUB_HUB_TIERS export', contracts.includes('export const CRAFTHUB_HUB_TIERS'));
check('contracts: CRAFTHUB_WIDGET_TYPES export', contracts.includes('export const CRAFTHUB_WIDGET_TYPES'));
check('contracts: CRAFTHUB_ROADMAP_PHASES export', contracts.includes('export const CRAFTHUB_ROADMAP_PHASES'));
check('contracts: C1-C5 roadmap phases', contracts.includes("key: 'C1'") && contracts.includes("key: 'C5'"));
check('contracts: complete/current/next/pending roadmap statuses', contracts.includes("'complete'") && contracts.includes("'current'") && contracts.includes("'next'") && contracts.includes("'pending'"));
check('contracts: CRAFTHUB_LOCALES export', contracts.includes('export const CRAFTHUB_LOCALES'));
check('contracts: 6 locales', contracts.includes('en-US') && contracts.includes('es-DO') && contracts.includes('ht') && contracts.includes('de') && contracts.includes('pt'));
check('contracts: CRAFTHUB_AUDIT_ACTIONS export', contracts.includes('export const CRAFTHUB_AUDIT_ACTIONS'));
check('contracts: CRAFTHUB_CONNECTOR_KEYS export', contracts.includes('export const CRAFTHUB_CONNECTOR_KEYS'));
check('contracts: pos360_sync connector', contracts.includes('pos360_sync'));
check('contracts: smokecraft_sync connector', contracts.includes('smokecraft_sync'));
check('contracts: eat_ai_automation connector', contracts.includes('eat_ai_automation'));
check('contracts: validateModuleKey export', contracts.includes('export function validateModuleKey'));
check('contracts: validateModuleCategory export', contracts.includes('export function validateModuleCategory'));
check('contracts: validateModuleStatus export', contracts.includes('export function validateModuleStatus'));
check('contracts: validateHubTier export', contracts.includes('export function validateHubTier'));
check('contracts: validateWidgetType export', contracts.includes('export function validateWidgetType'));
check('contracts: validateLocale export', contracts.includes('export function validateLocale'));
check('contracts: validateConnectorKey export', contracts.includes('export function validateConnectorKey'));
check('contracts: validateAuditAction export', contracts.includes('export function validateAuditAction'));
check('contracts: isLiveModeBlocked export', contracts.includes('export function isLiveModeBlocked'));
check('contracts: CRAFTHUB_PLATFORM_COMPONENTS export', contracts.includes('export const CRAFTHUB_PLATFORM_COMPONENTS'));

// ── FEATURE FLAGS ──────────────────────────────────────────────────────────────
console.log('\n── Feature Flags ──');
check('flags: file exists', flags.length > 100);
check('flags: contains_secrets: false comment', flags.includes('contains_secrets: false'));
check('flags: DEFAULT_CRAFTHUB_DASHBOARD_FLAGS export', flags.includes('export const DEFAULT_CRAFTHUB_DASHBOARD_FLAGS'));
check('flags: getCraftHubDashboardFlags export', flags.includes('export function getCraftHubDashboardFlags'));
check('flags: module_installed: false', flags.includes('module_installed: false'));
check('flags: module_activated: false', flags.includes('module_activated: false'));
check('flags: marketplace_purchase_completed: false', flags.includes('marketplace_purchase_completed: false'));
check('flags: billing_connected: false', flags.includes('billing_connected: false'));
check('flags: license_verified: false', flags.includes('license_verified: false'));
check('flags: provider_connected: false', flags.includes('provider_connected: false'));
check('flags: launch_allowed: false', flags.includes('launch_allowed: false'));
check('flags: live_mode_enabled: false', flags.includes('live_mode_enabled: false'));
check('flags: exposes_private_data: true', flags.includes('exposes_private_data: true'));
check('flags: contains_secrets: false in flags', flags.includes('contains_secrets: false,'));
check('flags: stores_secrets: false', flags.includes('stores_secrets: false'));
check('flags: 40+ flags present', (flags.match(/false[,\s]/g) || []).length >= 40);
check('flags: pos360_live: false', flags.includes('pos360_live: false'));
check('flags: smokecraft_live: false', flags.includes('smokecraft_live: false'));
check('flags: marketplace_enabled: false', flags.includes('marketplace_enabled: false'));
check('flags: sidebar_enabled: false', flags.includes('sidebar_enabled: false'));
check('flags: premium_hub_enabled: false', flags.includes('premium_hub_enabled: false'));
check('flags: api_key_creation_enabled: false', flags.includes('api_key_creation_enabled: false'));
check('flags: overrides spread', flags.includes('...overrides'));

// ── LOCALES ────────────────────────────────────────────────────────────────────
console.log('\n── Locales ──');
check('locales: file exists', locales.length > 100);
check('locales: en-US present', locales.includes("'en-US'"));
check('locales: es-DO present', locales.includes("'es-DO'"));
check('locales: es present', locales.includes("'es'"));
check('locales: ht present', locales.includes("'ht'"));
check('locales: de present', locales.includes("'de'"));
check('locales: pt present', locales.includes("'pt'"));
check('locales: title key', locales.includes("title:"));
check('locales: modules key', locales.includes("modules:"));
check('locales: marketplace key', locales.includes("marketplace:"));
check('locales: roadmap key', locales.includes("roadmap:"));
check('locales: launch key', locales.includes("launch:"));
check('locales: activation_required key', locales.includes("activation_required:"));
check('locales: local_preview key', locales.includes("local_preview:"));
check('locales: live_mode_disabled key', locales.includes("live_mode_disabled:"));
check('locales: default export', locales.includes('export default'));

// ── SERVICE ────────────────────────────────────────────────────────────────────
console.log('\n── Service ──');
check('service: file exists', service.length > 100);
check('service: JSDoc Falls back gracefully', service.includes('Falls back gracefully when no database connection is configured.'));
check('service: JSDoc Never prints connection string', service.includes('Never prints or logs the database connection string.'));
check('service: contains_secrets: false comment', service.includes('contains_secrets: false'));
check('service: isDbAvailable import', service.includes('isDbAvailable'));
check('service: localFallback helper', service.includes('localFallback'));
check('service: area: crafthub_dashboard', service.includes("area: AREA") || service.includes("area: 'crafthub_dashboard'"));
check('service: AREA constant', service.includes("const AREA = 'crafthub_dashboard'"));
check('service: idempotency_key_required guard', service.includes("'idempotency_key_required'"));
check('service: getDefaultCraftHubDashboard export', service.includes('export async function getDefaultCraftHubDashboard'));
check('service: buildLocalModuleCards function', service.includes('buildLocalModuleCards'));
check('service: 15 module keys in default cards', service.includes('novee_os_module_registry') && service.includes('future_module_placeholder'));
check('service: module_installed: false in defaults', service.includes('module_installed: false'));
check('service: live_mode_enabled: false in defaults', service.includes('live_mode_enabled: false'));
check('service: activation_required: true in defaults', service.includes('activation_required: true'));
check('service: placeholder_mode in defaults', service.includes('placeholder_mode:'));
check('service: getDashboardSessions export', service.includes('export async function getDashboardSessions'));
check('service: createDashboardSession export', service.includes('export async function createDashboardSession'));
check('service: getModuleLauncherRegistry export', service.includes('export async function getModuleLauncherRegistry'));
check('service: requestModuleInstall export', service.includes('export async function requestModuleInstall'));
check('service: requestModuleInstall returns activation_required', service.includes("error: 'activation_required'") && service.includes("module_installed: false"));
check('service: requestModuleActivation export', service.includes('export async function requestModuleActivation'));
check('service: getNavigationShellConfig export', service.includes('export async function getNavigationShellConfig'));
check('service: updateNavigationShellConfig export', service.includes('export async function updateNavigationShellConfig'));
check('service: getPremiumExperienceHub export', service.includes('export async function getPremiumExperienceHub'));
check('service: getDashboardWidgets export', service.includes('export async function getDashboardWidgets'));
check('service: addDashboardWidget export', service.includes('export async function addDashboardWidget'));
check('service: removeWidget export', service.includes('export async function removeWidget'));
check('service: getModuleRoadmap export', service.includes('export async function getModuleRoadmap'));
check('service: getMarketplaceCatalog export', service.includes('export async function getMarketplaceCatalog'));
check('service: initiateMarketplacePurchase export', service.includes('export async function initiateMarketplacePurchase'));
check('service: initiateMarketplacePurchase returns activation_required', service.includes('live_purchase_enabled: false') && service.includes('payment_completed: false'));
check('service: getMarketplacePurchases export', service.includes('export async function getMarketplacePurchases'));
check('service: getQuickActions export', service.includes('export async function getQuickActions'));
check('service: triggerQuickAction export', service.includes('export async function triggerQuickAction'));
check('service: getActivityFeed export', service.includes('export async function getActivityFeed'));
check('service: getNotifications export', service.includes('export async function getNotifications'));
check('service: dismissNotification export', service.includes('export async function dismissNotification'));
check('service: getOnboardingChecklist export', service.includes('export async function getOnboardingChecklist'));
check('service: completeOnboardingStep export', service.includes('export async function completeOnboardingStep'));
check('service: getAnnouncements export', service.includes('export async function getAnnouncements'));
check('service: getModuleHealthChecks export', service.includes('export async function getModuleHealthChecks'));
check('service: getFeatureFlagOverrides export', service.includes('export async function getFeatureFlagOverrides'));
check('service: setFeatureFlagOverride export', service.includes('export async function setFeatureFlagOverride'));
check('service: getUserPreferences export', service.includes('export async function getUserPreferences'));
check('service: updateUserPreferences export', service.includes('export async function updateUserPreferences'));
check('service: getModuleEntitlements export', service.includes('export async function getModuleEntitlements'));
check('service: grantModuleEntitlement export', service.includes('export async function grantModuleEntitlement'));
check('service: getAuditLog export', service.includes('export async function getAuditLog'));
check('service: createApiKey export', service.includes('export async function createApiKey'));
check('service: createApiKey returns activation_required', service.includes("error: 'activation_required'") && service.includes('live_mode_enabled: false'));
check('service: getApiKeys export', service.includes('export async function getApiKeys'));
check('service: revokeApiKey export', service.includes('export async function revokeApiKey'));
check('service: getIntegrationConnectors export', service.includes('export async function getIntegrationConnectors'));
check('service: connectIntegration export', service.includes('export async function connectIntegration'));
check('service: connectIntegration returns activation_required', service.includes("provider_connected: false"));
check('service: disconnectIntegration export', service.includes('export async function disconnectIntegration'));
check('service: getPlatformHealthStatus export', service.includes('export async function getPlatformHealthStatus'));
check('service: getSearchResults export', service.includes('export async function getSearchResults'));
check('service: getDashboardStats export', service.includes('export async function getDashboardStats'));
check('service: ON CONFLICT idempotency', service.includes('ON CONFLICT (idempotency_key) DO NOTHING'));
check('service: insertAudit helper', service.includes('async function insertAudit'));
check('service: CRAFTHUB_ROADMAP_PHASES used', service.includes('CRAFTHUB_ROADMAP_PHASES'));
check('service: CRAFTHUB_PLATFORM_COMPONENTS used', service.includes('CRAFTHUB_PLATFORM_COMPONENTS'));

// ── CONTROLLER ──────────────────────────────────────────────────────────────────
console.log('\n── Controller ──');
check('controller: file exists', controller.length > 100);
check('controller: contains_secrets: false comment', controller.includes('contains_secrets: false'));
check('controller: ok500 pattern', controller.includes('const ok500 = (res, fn) => fn().catch(e => res.status(500).json({ ok: false, error: e.message }))'));
check('controller: actorUserId pattern', controller.includes('const actorUserId = req =>'));
check('controller: ikey pattern', controller.includes('const ikey = req =>'));
check('controller: getDashboard export', controller.includes('export const getDashboard'));
check('controller: getDashboardStats export', controller.includes('export const getDashboardStats'));
check('controller: getDashboardSessions export', controller.includes('export const getDashboardSessions'));
check('controller: createDashboardSession export', controller.includes('export const createDashboardSession'));
check('controller: getModuleLauncher export', controller.includes('export const getModuleLauncher'));
check('controller: installModule export', controller.includes('export const installModule'));
check('controller: activateModule export', controller.includes('export const activateModule'));
check('controller: getNavShellConfig export', controller.includes('export const getNavShellConfig'));
check('controller: updateNavShellConfig export', controller.includes('export const updateNavShellConfig'));
check('controller: getPremiumHub export', controller.includes('export const getPremiumHub'));
check('controller: getWidgets export', controller.includes('export const getWidgets'));
check('controller: addWidget export', controller.includes('export const addWidget'));
check('controller: removeWidget export', controller.includes('export const removeWidget'));
check('controller: getRoadmap export', controller.includes('export const getRoadmap'));
check('controller: getMarketplace export', controller.includes('export const getMarketplace'));
check('controller: initiatePurchase export', controller.includes('export const initiatePurchase'));
check('controller: getPurchases export', controller.includes('export const getPurchases'));
check('controller: getQuickActions export', controller.includes('export const getQuickActions'));
check('controller: triggerQuickAction export', controller.includes('export const triggerQuickAction'));
check('controller: getActivityFeed export', controller.includes('export const getActivityFeed'));
check('controller: getNotifications export', controller.includes('export const getNotifications'));
check('controller: dismissNotification export', controller.includes('export const dismissNotification'));
check('controller: getOnboarding export', controller.includes('export const getOnboarding'));
check('controller: completeOnboardingStep export', controller.includes('export const completeOnboardingStep'));
check('controller: getAnnouncements export', controller.includes('export const getAnnouncements'));
check('controller: getHealthChecks export', controller.includes('export const getHealthChecks'));
check('controller: getFeatureFlagOverrides export', controller.includes('export const getFeatureFlagOverrides'));
check('controller: setFeatureFlagOverride export', controller.includes('export const setFeatureFlagOverride'));
check('controller: getUserPreferences export', controller.includes('export const getUserPreferences'));
check('controller: updateUserPreferences export', controller.includes('export const updateUserPreferences'));
check('controller: getEntitlements export', controller.includes('export const getEntitlements'));
check('controller: grantEntitlement export', controller.includes('export const grantEntitlement'));
check('controller: getAuditLog export', controller.includes('export const getAuditLog'));
check('controller: createApiKey export', controller.includes('export const createApiKey'));
check('controller: getApiKeys export', controller.includes('export const getApiKeys'));
check('controller: revokeApiKey export', controller.includes('export const revokeApiKey'));
check('controller: getConnectors export', controller.includes('export const getConnectors'));
check('controller: connectIntegration export', controller.includes('export const connectIntegration'));
check('controller: disconnectIntegration export', controller.includes('export const disconnectIntegration'));
check('controller: getPlatformHealth export', controller.includes('export const getPlatformHealth'));
check('controller: getSearchResults export', controller.includes('export const getSearchResults'));

// ── ROUTES ──────────────────────────────────────────────────────────────────────
console.log('\n── Routes ──');
check('routes: file exists', routes.length > 100);
check('routes: platformAdminGuardRequired comment', routes.includes('platformAdminGuardRequired = true'));
check('routes: canAccessPOS3 import', routes.includes('canAccessPOS3'));
check('routes: canAccessPOS3 on install', routes.includes("canAccessPOS3,   ctrl.installModule"));
check('routes: canAccessPOS3 on activate', routes.includes("canAccessPOS3,   ctrl.activateModule"));
check('routes: canAccessPOS3 on purchase', routes.includes("canAccessPOS3,   ctrl.initiatePurchase"));
check('routes: canAccessPOS3 on audit log', routes.includes("canAccessPOS3,   ctrl.getAuditLog"));
check('routes: canAccessPOS3 on feature flags write', routes.includes("canAccessPOS3,   ctrl.setFeatureFlagOverride"));
check('routes: canAccessPOS3 on entitlement grant', routes.includes("canAccessPOS3,   ctrl.grantEntitlement"));
check('routes: canAccessPOS3 on api key create', routes.includes("canAccessPOS3,   ctrl.createApiKey"));
check('routes: canAccessPOS3 on api key revoke', routes.includes("canAccessPOS3,   ctrl.revokeApiKey"));
check('routes: canAccessPOS3 on connector connect', routes.includes("canAccessPOS3,   ctrl.connectIntegration"));
check('routes: GET /overview', routes.includes("router.get('/overview'"));
check('routes: GET /modules/:tenantId', routes.includes("router.get('/modules/:tenantId'"));
check('routes: POST /modules/:tenantId/install', routes.includes("router.post('/modules/:tenantId/install'"));
check('routes: GET /shell/:tenantId', routes.includes("router.get('/shell/:tenantId'"));
check('routes: GET /premium/:tenantId', routes.includes("router.get('/premium/:tenantId'"));
check('routes: GET /widgets', routes.includes("router.get('/widgets/"));
check('routes: GET /roadmap', routes.includes("router.get('/roadmap'"));
check('routes: GET /marketplace', routes.includes("router.get('/marketplace'"));
check('routes: POST marketplace purchase', routes.includes("router.post('/marketplace/:tenantId/purchase'"));
check('routes: GET /quick-actions', routes.includes("router.get('/quick-actions/"));
check('routes: GET /activity', routes.includes("router.get('/activity/"));
check('routes: GET /notifications', routes.includes("router.get('/notifications/"));
check('routes: GET /onboarding', routes.includes("router.get('/onboarding/"));
check('routes: GET /announcements', routes.includes("router.get('/announcements'"));
check('routes: GET /health-checks', routes.includes("router.get('/health-checks/"));
check('routes: GET /feature-flags', routes.includes("router.get('/feature-flags/"));
check('routes: GET /preferences', routes.includes("router.get('/preferences/"));
check('routes: GET /entitlements', routes.includes("router.get('/entitlements/"));
check('routes: GET /audit', routes.includes("router.get('/audit/"));
check('routes: GET /api-keys', routes.includes("router.get('/api-keys/"));
check('routes: GET /connectors', routes.includes("router.get('/connectors/"));
check('routes: GET /platform-health', routes.includes("router.get('/platform-health'"));
check('routes: GET /search', routes.includes("router.get('/search/"));
check('routes: export default router', routes.includes('export default router'));

// ── UI COMPONENT ────────────────────────────────────────────────────────────────
console.log('\n── UI Component ──');
check('ui: file exists', ui.length > 100);
check('ui: DEVICE_LINE constant', ui.includes("const DEVICE_LINE = 'Touchscreen · Handheld · Tablet · Desktop'"));
check('ui: NAVY color token', ui.includes("const NAVY     = '#0a0d14'"));
check('ui: CHARCOAL color token', ui.includes("const CHARCOAL = '#111520'"));
check('ui: CARD color token', ui.includes("const CARD     = '#161b27'"));
check('ui: LINE color token', ui.includes("const LINE     = '#252d3f'"));
check('ui: GOLD color token', ui.includes("const GOLD     = '#c9952c'"));
check('ui: GOLD2 color token', ui.includes("const GOLD2    = '#e8b84b'"));
check('ui: TEXT color token', ui.includes("const TEXT     = '#e8e4d8'"));
check('ui: MUTE color token', ui.includes("const MUTE     = '#7a8299'"));
check('ui: RED color token', ui.includes("const RED      = '#c0392b'"));
check('ui: GREEN color token', ui.includes("const GREEN    = '#27ae60'"));
check('ui: BLUE color token', ui.includes("const BLUE     = '#2980b9'"));
check('ui: AMBER color token', ui.includes("const AMBER    = '#e67e22'"));
check('ui: PURPLE color token', ui.includes("const PURPLE   = '#8e44ad'"));
check('ui: useState import', ui.includes("import { useState }"));
check('ui: TABS array with 16 tabs', (ui.match(/TABS\s*=/)).length >= 1 && ui.includes("'Overview'") && ui.includes("'Modules'") && ui.includes("'Marketplace'") && ui.includes("'Roadmap'"));
check('ui: MODULES array with 15 modules', ui.includes('novee_os_module_registry') && ui.includes('future_module_placeholder'));
check('ui: ROADMAP array', ui.includes('const ROADMAP'));
check('ui: CONNECTORS array', ui.includes('const CONNECTORS'));
check('ui: FLAGS object', ui.includes('const FLAGS'));
check('ui: OverviewPanel function', ui.includes('function OverviewPanel'));
check('ui: ModulesPanel function', ui.includes('function ModulesPanel'));
check('ui: MarketplacePanel function', ui.includes('function MarketplacePanel'));
check('ui: RoadmapPanel function', ui.includes('function RoadmapPanel'));
check('ui: ConnectorsPanel function', ui.includes('function ConnectorsPanel'));
check('ui: WidgetsPanel function', ui.includes('function WidgetsPanel'));
check('ui: ActivityPanel function', ui.includes('function ActivityPanel'));
check('ui: NotificationsPanel function', ui.includes('function NotificationsPanel'));
check('ui: OnboardingPanel function', ui.includes('function OnboardingPanel'));
check('ui: FeatureFlagsPanel function', ui.includes('function FeatureFlagsPanel'));
check('ui: ApiKeysPanel function', ui.includes('function ApiKeysPanel'));
check('ui: PreferencesPanel function', ui.includes('function PreferencesPanel'));
check('ui: EntitlementsPanel function', ui.includes('function EntitlementsPanel'));
check('ui: AuditPanel function', ui.includes('function AuditPanel'));
check('ui: PlatformHealthPanel function', ui.includes('function PlatformHealthPanel'));
check('ui: SearchPanel function', ui.includes('function SearchPanel'));
check('ui: CraftHubDashboard main component', ui.includes('function CraftHubDashboard'));
check('ui: export default CraftHubDashboard', ui.includes('export default CraftHubDashboard'));
check('ui: activeTab useState', ui.includes("useState('Overview')"));
check('ui: tab bar rendered', ui.includes('TABS.map'));
check('ui: PANELS dispatch object', ui.includes('const PANELS'));
check('ui: module cards grid', ui.includes('MODULES.map'));
check('ui: roadmap rendered', ui.includes('ROADMAP.map'));
check('ui: connectors rendered', ui.includes('CONNECTORS.map'));
check('ui: Lock component for live gates', ui.includes('Lock') && ui.includes('activation_required'));
check('ui: Badge component', ui.includes('Badge') && ui.includes('label'));
check('ui: Card component', ui.includes('Card') && ui.includes('children'));
check('ui: SectionTitle component', ui.includes('SectionTitle'));
check('ui: live_mode: false in top bar', ui.includes('live_mode: false'));
check('ui: local_preview badge', ui.includes("'local_preview'"));
check('ui: activation_required gates', ui.includes('activation_required'));
check('ui: contains_secrets: false in footer', ui.includes('contains_secrets: false'));
check('ui: local_preview: true in footer', ui.includes('local_preview: true'));
check('ui: Phase C5 badge', ui.includes('Phase C5') || ui.includes('Phase C.5'));
check('ui: module_installed: false displayed', ui.includes('module_installed: false'));
check('ui: DEVICE_LINE in footer', ui.includes('{DEVICE_LINE}'));
check('ui: 16 panels in PANELS object', (ui.match(/Panel,?$/gm) || []).length >= 10);
check('ui: locales string mentioned', ui.includes('en-US · es-DO · es · ht · de · pt'));
check('ui: not live warning', ui.includes('not live'));
check('ui: provider_connected: false', ui.includes('provider_connected: false'));
check('ui: payment_completed: false', ui.includes('payment_completed: false'));

// ── SERVER WIRING ────────────────────────────────────────────────────────────────
console.log('\n── Server Wiring ──');
check('server: craftHubDashboardRoutes import', serverIndex.includes('craftHubDashboardRoutes'));
check('server: /api/crafthub/dashboard mount', serverIndex.includes("'/api/crafthub/dashboard'"));

// ── APP.JSX WIRING ────────────────────────────────────────────────────────────────
console.log('\n── App.jsx Wiring ──');
check('app: CraftHubDashboard import', appJsx.includes('CraftHubDashboard'));
check('app: crafthub/dashboard route', appJsx.includes('crafthub/dashboard'));

// ── PACKAGE.JSON WIRING ────────────────────────────────────────────────────────────────
console.log('\n── Package.json Wiring ──');
check('package: verify:crafthub-dashboard script', pkgJson.includes('"verify:crafthub-dashboard"'));
check('package: verifyCraftHubDashboard.js', pkgJson.includes('verifyCraftHubDashboard.js'));

// ── NO FAKE OPERATIONS ─────────────────────────────────────────────────────────
console.log('\n── No Fake Operations ──');
check('no-fake: module install blocked', service.includes("error: 'activation_required'") && service.includes('module_installed: false'));
check('no-fake: module activate blocked', service.includes('module_activated: false'));
check('no-fake: marketplace purchase blocked', service.includes('live_purchase_enabled: false') && service.includes('payment_completed: false'));
check('no-fake: connector connect blocked', service.includes('provider_connected: false'));
check('no-fake: api key creation blocked', service.includes("error: 'activation_required'") && service.includes('live_mode_enabled: false'));
check('no-fake: pos360 sync not live', flags.includes('pos360_sync_enabled: false'));
check('no-fake: smokecraft sync not live', flags.includes('smokecraft_sync_enabled: false'));
check('no-fake: eat ai automation not live', flags.includes('eat_ai_automation_enabled: false'));
check('no-fake: white_label not live', flags.includes('white_label_enabled: false'));
check('no-fake: custom_domain not live', flags.includes('custom_domain_enabled: false'));
check('no-fake: live_mode_enabled: false on connectors in UI', ui.includes('provider_connected: false'));
check('no-fake: activation_required in connector Lock', ui.includes('activation_required — not live'));

// ── SUMMARY ────────────────────────────────────────────────────────────────────
console.log(`\n────────────────────────────────────────`);
console.log(`  PASSED: ${passed}`);
console.log(`  FAILED: ${failed}`);
console.log(`  TOTAL:  ${passed + failed}`);
console.log(`────────────────────────────────────────`);
if (failed > 0) process.exit(1);
