/**
 * verifyPos360PaymentsCloseout.js — Phase B.11 Prompt X
 * Verification: 155+ checks. Exits 1 on failure.
 */

import { readFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..', '..')

let passed = 0
let failed = 0

function check(label, condition) {
  if (condition) {
    passed++
  } else {
    failed++
    console.error(`FAIL: ${label}`)
  }
}

const read = (...parts) => {
  try { return readFileSync(join(root, ...parts), 'utf8') } catch { return '' }
}

// ── Migration ─────────────────────────────────────────────────────────────────
const sql = read('server', 'db', 'migrations', '041_pos360_payments_tips_closeout.sql')
check('migration exists', sql.length > 0)
check('CREATE TABLE pos360_payment_provider_profiles', sql.includes('pos360_payment_provider_profiles'))
check('CREATE TABLE pos360_payment_terminal_profiles', sql.includes('pos360_payment_terminal_profiles'))
check('CREATE TABLE pos360_payment_intents', sql.includes('pos360_payment_intents'))
check('CREATE TABLE pos360_split_tender_groups', sql.includes('pos360_split_tender_groups'))
check('CREATE TABLE pos360_payment_records', sql.includes('pos360_payment_records'))
check('CREATE TABLE pos360_payment_tenders', sql.includes('pos360_payment_tenders'))
check('CREATE TABLE pos360_payment_status_history', sql.includes('pos360_payment_status_history'))
check('CREATE TABLE pos360_tip_records', sql.includes('pos360_tip_records'))
check('CREATE TABLE pos360_tip_adjustments', sql.includes('pos360_tip_adjustments'))
check('CREATE TABLE pos360_signature_records', sql.includes('pos360_signature_records'))
check('CREATE TABLE pos360_receipt_records', sql.includes('pos360_receipt_records'))
check('CREATE TABLE pos360_receipt_delivery_attempts', sql.includes('pos360_receipt_delivery_attempts'))
check('CREATE TABLE pos360_refund_requests', sql.includes('pos360_refund_requests'))
check('CREATE TABLE pos360_void_requests', sql.includes('pos360_void_requests'))
check('CREATE TABLE pos360_cash_drawers', sql.includes('pos360_cash_drawers'))
check('CREATE TABLE pos360_cash_drawer_events', sql.includes('pos360_cash_drawer_events'))
check('CREATE TABLE pos360_server_closeouts', sql.includes('pos360_server_closeouts'))
check('CREATE TABLE pos360_shift_closeouts', sql.includes('pos360_shift_closeouts'))
check('CREATE TABLE pos360_daily_closeouts', sql.includes('pos360_daily_closeouts'))
check('CREATE TABLE pos360_payment_risk_flags', sql.includes('pos360_payment_risk_flags'))
check('CREATE TABLE pos360_payment_revenue_insights', sql.includes('pos360_payment_revenue_insights'))
check('CREATE TABLE pos360_payment_offline_queue', sql.includes('pos360_payment_offline_queue'))
check('CREATE TABLE pos360_payment_audit', sql.includes('pos360_payment_audit'))
check('uses CREATE TABLE IF NOT EXISTS', sql.includes('CREATE TABLE IF NOT EXISTS'))
check('no DROP TABLE', !sql.split('\n').filter(l => !l.trim().startsWith('--')).join('\n').toUpperCase().includes('DROP TABLE'))
check('stores_card_data on provider_profiles', sql.includes('stores_card_data') && sql.includes('pos360_payment_provider_profiles'))
check('stores_card_data DEFAULT FALSE', sql.includes('stores_card_data') && sql.includes('DEFAULT FALSE'))
check('stores_raw_signature DEFAULT FALSE', sql.includes('stores_raw_signature') && sql.includes('DEFAULT FALSE'))
check('sent_externally DEFAULT FALSE on receipts', sql.includes('sent_externally') && sql.includes('DEFAULT FALSE'))
check('exposes_financial_data on payment_intents', sql.includes('exposes_financial_data'))
check('exposes_financial_data DEFAULT TRUE', sql.includes('exposes_financial_data') && sql.includes('DEFAULT TRUE'))
check('exposes_private_data on receipts', sql.includes('exposes_private_data'))
check('contains_secrets FALSE on audit', sql.includes('contains_secrets') && sql.includes('DEFAULT FALSE'))
check('tender_type CHECK includes cash', sql.includes("'cash'"))
check('tender_type CHECK includes card_external', sql.includes("'card_external'"))
check('tender_type CHECK includes comp', sql.includes("'comp'"))
check('tender_type CHECK includes house_account', sql.includes("'house_account'"))
check('payment_status CHECK pending', sql.includes("'pending'"))
check('payment_status CHECK marked_paid_external', sql.includes("'marked_paid_external'"))
check('payment_status CHECK voided_external', sql.includes("'voided_external'"))
check('payment_intent_status CHECK unavailable', sql.includes("'unavailable'"))
check('intent_status CHECK draft', sql.includes("'draft'"))
check('intent_status CHECK pending_external', sql.includes("'pending_external'"))
check('closeout_status CHECK approved or manager_approved', sql.includes("'approved'") || sql.includes("'manager_approved'"))
check('closeout_status CHECK closed or discrepancy', sql.includes("'closed'") || sql.includes("'discrepancy'"))
check('cash_drawer_events type CHECK open or opening_cash', sql.includes("'open'") || sql.includes("'opening_cash'"))
check('tip type CHECK preset or preset_percent', sql.includes("'preset'") || sql.includes("'preset_percent'"))
check('tip type CHECK no_tip', sql.includes("'no_tip'"))
check('tip type or pool metadata present', sql.includes("'pool'") || sql.includes("tip_pool"))
check('receipt delivery preference or format CHECK print', sql.includes("'print'"))
check('receipt delivery preference CHECK qr', sql.includes("'qr'"))
check('receipt_status CHECK generated', sql.includes("'generated'"))
check('receipt_status CHECK sent_external', sql.includes("'sent_external'"))
check('refund_status CHECK approved or marked_refunded_external', sql.includes("'approved'"))
check('void_status CHECK approved or marked_voided_external', sql.includes("'approved'"))
check('risk flags have risk_type or flag_type', sql.includes('risk_type') || sql.includes('flag_type'))
check('risk flags have critical or large_void type', sql.includes("'large_void'") || sql.includes("'excessive_voids'") || sql.includes("'drawer_over_short'"))
check('payment_intents has order_id', sql.includes('order_id'))
check('payment_intents has reservation_id', sql.includes('reservation_id'))
check('payment_intents has private_event_id', sql.includes('private_event_id'))
check('payment_intents has package_selection_id', sql.includes('package_selection_id'))
check('payment_intents has deposit_record_id', sql.includes('deposit_record_id'))
check('payment_intents has minimum_spend_progress_id', sql.includes('minimum_spend_progress_id'))
check('idempotency_key on payment_intents', sql.includes('idempotency_key'))
check('unique idempotency index on payment_intents', sql.includes('idx_pmt_intents_idem') || (sql.includes('idempotency_key') && sql.includes('UNIQUE')))
check('manager_approved_by on server_closeouts', sql.includes('manager_approved_by'))
check('manager_approved_at on server_closeouts', sql.includes('manager_approved_at'))
check('over_short_amount on daily_closeouts', sql.includes('over_short_amount'))
check('terminal_type in terminal_profiles', sql.includes('terminal_type'))
check('terminal_status in terminal_profiles', sql.includes('terminal_status'))
check('provider_name or provider_type in provider_profiles', sql.includes('provider_name') || sql.includes('provider_type'))
check('server_user_id or shift_label in closeouts', sql.includes('server_user_id') || sql.includes('shift_label'))
check('server_user_id in server_closeouts', sql.includes('server_user_id'))
check('signature_provider or signature_method in signature_records', sql.includes('signature_provider') || sql.includes('signature_method'))
check('delivery_method or delivery_channel in receipt_delivery_attempts', sql.includes('delivery_method') || sql.includes('delivery_channel'))
check('attempt_status in receipt_delivery_attempts', sql.includes('attempt_status'))
check('flag_type or risk_type in risk_flags', sql.includes('flag_type') || sql.includes('risk_type'))
check('flag_level or risk_status in risk_flags', sql.includes('flag_level') || sql.includes('risk_status'))
check('synced_at in offline_queue', sql.includes('synced_at'))
check('queue_status or sync_status in offline_queue', sql.includes('queue_status') || sql.includes('sync_status'))

// ── Contracts ─────────────────────────────────────────────────────────────────
const contracts = read('server', 'services', 'pos360', 'pos360PaymentContracts.js')
check('contracts file exists', contracts.length > 0)
check('PAYMENT_PROVIDER_TYPES exported', contracts.includes('PAYMENT_PROVIDER_TYPES'))
check('stripe in providers', contracts.includes("'stripe'"))
check('square in providers', contracts.includes("'square'"))
check('clover in providers', contracts.includes("'clover'"))
check('toast in providers', contracts.includes("'toast'"))
check('adyen in providers', contracts.includes("'adyen'"))
check('authorize_net in providers', contracts.includes("'authorize_net'"))
check('worldpay in providers', contracts.includes("'worldpay'"))
check('TERMINAL_TYPES exported', contracts.includes('TERMINAL_TYPES'))
check('handheld in terminal types', contracts.includes("'handheld'"))
check('tablet in terminal types', contracts.includes("'tablet'"))
check('kiosk in terminal types', contracts.includes("'kiosk'"))
check('counter in terminal types', contracts.includes("'counter'"))
check('external in terminal types', contracts.includes("'external'"))
check('TENDER_TYPES exported', contracts.includes('TENDER_TYPES'))
check('PAYMENT_STATUSES exported', contracts.includes('PAYMENT_STATUSES'))
check('TIP_SELECTION_TYPES exported', contracts.includes('TIP_SELECTION_TYPES'))
check('RECEIPT_FORMATS exported', contracts.includes('RECEIPT_FORMATS'))
check('RECEIPT_STATUSES exported', contracts.includes('RECEIPT_STATUSES'))
check('REFUND_STATUSES exported', contracts.includes('REFUND_STATUSES'))
check('VOID_STATUSES exported', contracts.includes('VOID_STATUSES'))
check('CASH_DRAWER_STATUSES exported', contracts.includes('CASH_DRAWER_STATUSES'))
check('CLOSEOUT_STATUSES exported', contracts.includes('CLOSEOUT_STATUSES'))
check('RISK_FLAG_LEVELS exported', contracts.includes('RISK_FLAG_LEVELS'))
check('RISK_FLAG_TYPES exported', contracts.includes('RISK_FLAG_TYPES'))
check('isValidProviderType exported', contracts.includes('isValidProviderType'))
check('isValidTenderType exported', contracts.includes('isValidTenderType'))
check('isValidCloseoutStatus exported', contracts.includes('isValidCloseoutStatus'))
check('isValidRiskFlagLevel exported', contracts.includes('isValidRiskFlagLevel'))

// ── Feature flags ─────────────────────────────────────────────────────────────
const flags = read('server', 'config', 'pos360PaymentFeatureFlags.js')
check('feature flags file exists', flags.length > 0)
check('DEFAULT_POS360_PAYMENT_FLAGS exported', flags.includes('DEFAULT_POS360_PAYMENT_FLAGS'))
check('getPaymentFlags exported', flags.includes('getPaymentFlags'))
check('stripeProviderEnabled: false', flags.includes('stripeProviderEnabled: false'))
check('squareProviderEnabled: false', flags.includes('squareProviderEnabled: false'))
check('cloverProviderEnabled: false', flags.includes('cloverProviderEnabled: false'))
check('toastProviderEnabled: false', flags.includes('toastProviderEnabled: false'))
check('adyenProviderEnabled: false', flags.includes('adyenProviderEnabled: false'))
check('authorizeNetProviderEnabled: false', flags.includes('authorizeNetProviderEnabled: false'))
check('worldpayProviderEnabled: false', flags.includes('worldpayProviderEnabled: false'))
check('manualPaymentEnabled: true', flags.includes('manualPaymentEnabled: true'))
check('splitTenderEnabled: true', flags.includes('splitTenderEnabled: true'))
check('tipSelectionEnabled: true', flags.includes('tipSelectionEnabled: true'))
check('signatureMetadataEnabled: true', flags.includes('signatureMetadataEnabled: true'))
check('receiptGenerationEnabled: true', flags.includes('receiptGenerationEnabled: true'))
check('receiptEmailEnabled: false', flags.includes('receiptEmailEnabled: false'))
check('receiptSmsEnabled: false', flags.includes('receiptSmsEnabled: false'))
check('managerApprovalForRefundsEnabled: true', flags.includes('managerApprovalForRefundsEnabled: true'))
check('managerApprovalForVoidsEnabled: true', flags.includes('managerApprovalForVoidsEnabled: true'))
check('cashDrawerEnabled: true', flags.includes('cashDrawerEnabled: true'))
check('serverCloseoutEnabled: true', flags.includes('serverCloseoutEnabled: true'))
check('shiftCloseoutEnabled: true', flags.includes('shiftCloseoutEnabled: true'))
check('dailyCloseoutEnabled: true', flags.includes('dailyCloseoutEnabled: true'))
check('paymentRiskFlagsEnabled: true', flags.includes('paymentRiskFlagsEnabled: true'))
check('eatRevenueInsightHooksEnabled: false', flags.includes('eatRevenueInsightHooksEnabled: false'))
check('offlinePaymentQueueEnabled: true', flags.includes('offlinePaymentQueueEnabled: true'))
check('38+ flags total', (flags.match(/Enabled/g) || []).length >= 38)

// ── Locales ───────────────────────────────────────────────────────────────────
const locales = read('src', 'locales', 'pos360Payments.js')
check('locales file exists', locales.length > 0)
check('tPayment exported', locales.includes('export function tPayment'))
check('getSupportedPaymentLanguages exported', locales.includes('export function getSupportedPaymentLanguages'))
check('en-US locale', locales.includes("'en-US'"))
check('es-DO locale', locales.includes("'es-DO'"))
check('es locale', locales.includes("'es'"))
check('ht locale', locales.includes("'ht'"))
check('de locale', locales.includes("'de'"))
check('pt locale', locales.includes("'pt'"))
check('payment_provider_not_connected honest note en-US', locales.includes('Payment provider is not connected. No charges have been processed.'))
check('no_card_data_stored honest note', locales.includes('No card data is stored'))
check('no_raw_signature_stored honest note', locales.includes('No signature image is stored'))
check('receipt_not_sent honest note', locales.includes('Receipt has not been sent'))
check('email_not_connected honest note', locales.includes('email has been sent'))
check('sms_not_connected honest note', locales.includes('SMS has been sent'))
check('eat_revenue_insights_not_connected', locales.includes('E.A.T. revenue insights are not connected'))

// ── Service ───────────────────────────────────────────────────────────────────
const svc = read('server', 'services', 'pos360', 'pos360PaymentCloseoutService.js')
check('service file exists', svc.length > 0)
check('service JSDoc: Falls back gracefully', svc.includes('Falls back gracefully when no database connection is configured.'))
check('service JSDoc: Never prints or logs', svc.includes('Never prints or logs the database connection string.'))
check('imports isDbAvailable', svc.includes('isDbAvailable'))
check('imports from ../../db/connection.js', svc.includes("from '../../db/connection.js'"))
check('LOCAL fallback pattern', svc.includes('localPreview: true'))
check('LOCAL fallback includes area', svc.includes("area: AREA"))
check('auditRecord internal helper', svc.includes('async function auditRecord'))
check('contains_secrets=FALSE in audit', svc.includes('contains_secrets, exposes_private_data, exposes_financial_data'))
check('createProviderProfile exported', svc.includes('export async function createProviderProfile'))
check('listProviderProfiles exported', svc.includes('export async function listProviderProfiles'))
check('updateProviderProfile exported', svc.includes('export async function updateProviderProfile'))
check('createTerminalProfile exported', svc.includes('export async function createTerminalProfile'))
check('listTerminalProfiles exported', svc.includes('export async function listTerminalProfiles'))
check('updateTerminalStatus exported', svc.includes('export async function updateTerminalStatus'))
check('createPaymentIntent exported', svc.includes('export async function createPaymentIntent'))
check('listPaymentIntents exported', svc.includes('export async function listPaymentIntents'))
check('updatePaymentIntentStatus exported', svc.includes('export async function updatePaymentIntentStatus'))
check('createPaymentRecord exported', svc.includes('export async function createPaymentRecord'))
check('listPaymentRecords exported', svc.includes('export async function listPaymentRecords'))
check('updatePaymentStatus exported', svc.includes('export async function updatePaymentStatus'))
check('createSplitTenderGroup exported', svc.includes('export async function createSplitTenderGroup'))
check('addPaymentTender exported', svc.includes('export async function addPaymentTender'))
check('createTipRecord exported', svc.includes('export async function createTipRecord'))
check('adjustTip exported', svc.includes('export async function adjustTip'))
check('listTipRecords exported', svc.includes('export async function listTipRecords'))
check('createSignatureRecord exported', svc.includes('export async function createSignatureRecord'))
check('createReceiptRecord exported', svc.includes('export async function createReceiptRecord'))
check('updateReceiptStatus exported', svc.includes('export async function updateReceiptStatus'))
check('logReceiptDeliveryAttempt exported', svc.includes('export async function logReceiptDeliveryAttempt'))
check('createRefundRequest exported', svc.includes('export async function createRefundRequest'))
check('approveRefund exported', svc.includes('export async function approveRefund'))
check('listRefundRequests exported', svc.includes('export async function listRefundRequests'))
check('createVoidRequest exported', svc.includes('export async function createVoidRequest'))
check('approveVoid exported', svc.includes('export async function approveVoid'))
check('createCashDrawer exported', svc.includes('export async function createCashDrawer'))
check('listCashDrawers exported', svc.includes('export async function listCashDrawers'))
check('createCashDrawerEvent exported', svc.includes('export async function createCashDrawerEvent'))
check('listCashDrawerEvents exported', svc.includes('export async function listCashDrawerEvents'))
check('createServerCloseout exported', svc.includes('export async function createServerCloseout'))
check('listServerCloseouts exported', svc.includes('export async function listServerCloseouts'))
check('approveServerCloseout exported', svc.includes('export async function approveServerCloseout'))
check('createShiftCloseout exported', svc.includes('export async function createShiftCloseout'))
check('listShiftCloseouts exported', svc.includes('export async function listShiftCloseouts'))
check('approveShiftCloseout exported', svc.includes('export async function approveShiftCloseout'))
check('createDailyCloseout exported', svc.includes('export async function createDailyCloseout'))
check('listDailyCloseouts exported', svc.includes('export async function listDailyCloseouts'))
check('approveDailyCloseout exported', svc.includes('export async function approveDailyCloseout'))
check('createRiskFlag exported', svc.includes('export async function createRiskFlag'))
check('listRiskFlags exported', svc.includes('export async function listRiskFlags'))
check('createRevenueInsightPlaceholder exported', svc.includes('export async function createRevenueInsightPlaceholder'))
check('listRevenueInsights exported', svc.includes('export async function listRevenueInsights'))
check('queueOfflinePaymentAction exported', svc.includes('export async function queueOfflinePaymentAction'))
check('listOfflinePaymentQueue exported', svc.includes('export async function listOfflinePaymentQueue'))
check('markOfflinePaymentActionSynced exported', svc.includes('export async function markOfflinePaymentActionSynced'))
check('refund manager approval block', svc.includes('manager_approval_required') && svc.includes('managerApprovalRequired: true'))
check('void manager approval block', svc.includes('void_payment'))
check('provider not connected honest note in service', svc.includes('Payment provider is not connected. No charges have been processed.'))
check('no card data note in service', svc.includes('No card data is stored'))
check('no raw signature note in service', svc.includes('No signature image is stored'))
check('receipt not sent note in service', svc.includes('Receipt has not been sent'))
check('email not connected note in service', svc.includes('email has been sent'))
check('EAT not connected note in service', svc.includes('E.A.T. revenue insights are not connected'))
check('idempotency duplicate check on intents', svc.includes('idempotency_key=$1 AND venue_id=$2') || svc.includes('idempotency_key=$'))
check('idempotency duplicate check on records', svc.includes('duplicate: true'))
check('status history on payment records', svc.includes('pos360_payment_status_history'))
check('isValidRiskFlagType used', svc.includes('isValidRiskFlagType'))
check('isValidRiskFlagLevel used', svc.includes('isValidRiskFlagLevel'))
check('isValidCloseoutStatus imported', svc.includes('isValidCloseoutStatus'))
check('EAT flag gate returns honest note', svc.includes("feature: 'eatRevenueInsightHooksEnabled'") && svc.includes('E.A.T. revenue insights are not connected'))

// ── Controller ────────────────────────────────────────────────────────────────
const ctrl = read('server', 'controllers', 'pos360PaymentCloseoutController.js')
check('controller file exists', ctrl.length > 0)
check('ok500 pattern', ctrl.includes('const ok500 = (res, fn)'))
check('vid pattern', ctrl.includes("const vid = req =>"))
check('actor pattern', ctrl.includes("const actor = req =>"))
check('tid pattern', ctrl.includes("const tid = req =>"))
check('createProviderProfile ctrl', ctrl.includes('export const createProviderProfile'))
check('listProviderProfiles ctrl', ctrl.includes('export const listProviderProfiles'))
check('createTerminalProfile ctrl', ctrl.includes('export const createTerminalProfile'))
check('createPaymentIntent ctrl', ctrl.includes('export const createPaymentIntent'))
check('createPaymentRecord ctrl', ctrl.includes('export const createPaymentRecord'))
check('createSplitTenderGroup ctrl', ctrl.includes('export const createSplitTenderGroup'))
check('createTipRecord ctrl', ctrl.includes('export const createTipRecord'))
check('adjustTip ctrl', ctrl.includes('export const adjustTip'))
check('createSignatureRecord ctrl', ctrl.includes('export const createSignatureRecord'))
check('createReceiptRecord ctrl', ctrl.includes('export const createReceiptRecord'))
check('createRefundRequest ctrl', ctrl.includes('export const createRefundRequest'))
check('approveRefund ctrl', ctrl.includes('export const approveRefund'))
check('createVoidRequest ctrl', ctrl.includes('export const createVoidRequest'))
check('approveVoid ctrl', ctrl.includes('export const approveVoid'))
check('createCashDrawer ctrl', ctrl.includes('export const createCashDrawer'))
check('createCashDrawerEvent ctrl', ctrl.includes('export const createCashDrawerEvent'))
check('createServerCloseout ctrl', ctrl.includes('export const createServerCloseout'))
check('approveServerCloseout ctrl', ctrl.includes('export const approveServerCloseout'))
check('createShiftCloseout ctrl', ctrl.includes('export const createShiftCloseout'))
check('approveShiftCloseout ctrl', ctrl.includes('export const approveShiftCloseout'))
check('createDailyCloseout ctrl', ctrl.includes('export const createDailyCloseout'))
check('approveDailyCloseout ctrl', ctrl.includes('export const approveDailyCloseout'))
check('createRiskFlag ctrl', ctrl.includes('export const createRiskFlag'))
check('queueOfflinePaymentAction ctrl', ctrl.includes('export const queueOfflinePaymentAction'))
check('markOfflinePaymentActionSynced ctrl', ctrl.includes('export const markOfflinePaymentActionSynced'))

// ── Routes ────────────────────────────────────────────────────────────────────
const routes = read('server', 'routes', 'pos360PaymentCloseoutRoutes.js')
check('routes file exists', routes.length > 0)
check('mounted comment at /api/pos360/payments-closeout', routes.includes('/api/pos360/payments-closeout'))
check('imports canAccessPOS3', routes.includes('canAccessPOS3'))
check('provider-profiles route', routes.includes('/provider-profiles'))
check('terminal-profiles route', routes.includes('/terminal-profiles'))
check('payment-intents route', routes.includes('/payment-intents'))
check('payment-records route', routes.includes('/payment-records'))
check('split-tender-groups route', routes.includes('/split-tender-groups'))
check('tip-records route', routes.includes('/tip-records'))
check('signature-records route', routes.includes('/signature-records'))
check('receipt-records route', routes.includes('/receipt-records'))
check('refund-requests route', routes.includes('/refund-requests'))
check('void-requests route', routes.includes('/void-requests'))
check('cash-drawers route', routes.includes('/cash-drawers'))
check('server-closeouts route', routes.includes('/server-closeouts'))
check('shift-closeouts route', routes.includes('/shift-closeouts'))
check('daily-closeouts route', routes.includes('/daily-closeouts'))
check('risk-flags route', routes.includes('/risk-flags'))
check('revenue-insights route', routes.includes('/revenue-insights'))
check('offline-queue route', routes.includes('/offline-queue'))
check('POST /provider-profiles canAccessPOS3', routes.includes("canAccessPOS3, ctrl.createProviderProfile"))
check('POST /tip-records canAccessPOS3', routes.includes("canAccessPOS3, ctrl.createTipRecord"))
check('POST /refund-requests canAccessPOS3', routes.includes("canAccessPOS3, ctrl.createRefundRequest"))
check('approve refund canAccessPOS3', routes.includes("canAccessPOS3, ctrl.approveRefund"))
check('approve void canAccessPOS3', routes.includes("canAccessPOS3, ctrl.approveVoid"))
check('approve server closeout canAccessPOS3', routes.includes("canAccessPOS3, ctrl.approveServerCloseout"))
check('approve shift closeout canAccessPOS3', routes.includes("canAccessPOS3, ctrl.approveShiftCloseout"))
check('approve daily closeout canAccessPOS3', routes.includes("canAccessPOS3, ctrl.approveDailyCloseout"))
check('exports default router', routes.includes('export default router'))

// ── UI component ──────────────────────────────────────────────────────────────
const ui = read('src', 'pages', 'pos360', 'POS360PaymentsCloseout.jsx')
check('UI component file exists', ui.length > 0)
check('default export POS360PaymentsCloseout', ui.includes('export default function POS360PaymentsCloseout'))
check('touchscreen header label', ui.includes('Touchscreen · Handheld · Tablet · Desktop'))
check('/smokecraft-pos360.png reference 1', (ui.match(/smokecraft-pos360\.png/g) || []).length >= 2)
check('design token DARK_BG', ui.includes("'#080604'"))
check('design token GOLD', ui.includes("'#c9952c'"))
check('design token DARK_CARD', ui.includes("'#13110d'"))
check('design token RED', ui.includes("'#c0392b'"))
check('design token GREEN', ui.includes("'#27ae60'"))
check('design token BLUE', ui.includes("'#2980b9'"))
check('design token AMBER', ui.includes("'#e67e22'"))
check('imports tPayment', ui.includes("import { tPayment"))
check('imports getSupportedPaymentLanguages', ui.includes('getSupportedPaymentLanguages'))
check('HonestProviderNote component', ui.includes('function HonestProviderNote'))
check('HonestEmptyState component', ui.includes('function HonestEmptyState'))
check('PaymentProviderPanel component', ui.includes('function PaymentProviderPanel'))
check('TerminalProfilePanel component', ui.includes('function TerminalProfilePanel'))
check('PaymentIntentPanel component', ui.includes('function PaymentIntentPanel'))
check('SplitTenderPanel component', ui.includes('function SplitTenderPanel'))
check('TipSelectionPanel component', ui.includes('function TipSelectionPanel'))
check('SignaturePanel component', ui.includes('function SignaturePanel'))
check('ReceiptPanel component', ui.includes('function ReceiptPanel'))
check('RefundPanel component', ui.includes('function RefundPanel'))
check('VoidPanel component', ui.includes('function VoidPanel'))
check('CashDrawerPanel component', ui.includes('function CashDrawerPanel'))
check('CloseoutPanel component', ui.includes('function CloseoutPanel'))
check('RiskFlagsPanel component', ui.includes('function RiskFlagsPanel'))
check('EATRevenueInsightsPanel component', ui.includes('function EATRevenueInsightsPanel'))
check('OfflinePaymentQueuePanel component', ui.includes('function OfflinePaymentQueuePanel'))
check('PaymentLanguageSelector component', ui.includes('function PaymentLanguageSelector'))
check('honest provider note in UI', ui.includes('payment_provider_not_connected'))
check('no_card_data_stored in UI', ui.includes('no_card_data_stored'))
check('no_raw_signature_stored in UI', ui.includes('no_raw_signature_stored'))
check('receipt_not_sent in UI', ui.includes('receipt_not_sent'))
check('email_not_connected in UI', ui.includes('email_not_connected'))
check('sms_not_connected in UI', ui.includes('sms_not_connected'))
check('EAT not connected in UI', ui.includes('eat_revenue_insights_not_connected'))
check('refund_approval_required in UI', ui.includes('refund_approval_required'))
check('void_approval_required in UI', ui.includes('void_approval_required'))
check('API base path references /payments-closeout', ui.includes('/payments-closeout'))
check('6 locale tabs in language selector', (ui.match(/getSupportedPaymentLanguages/g) || []).length >= 1)

// ── server/index.js wiring ────────────────────────────────────────────────────
const serverIndex = read('server', 'index.js')
check('server/index.js imports payments-closeout routes', serverIndex.includes('pos360PaymentCloseoutRoutes'))
check('server/index.js mounts /api/pos360/payments-closeout', serverIndex.includes('/api/pos360/payments-closeout'))

// ── App.jsx wiring ────────────────────────────────────────────────────────────
const appJsx = read('src', 'App.jsx')
check('App.jsx imports POS360PaymentsCloseout', appJsx.includes('POS360PaymentsCloseout'))
check('App.jsx Route payments-closeout', appJsx.includes('payments-closeout'))

// ── package.json ──────────────────────────────────────────────────────────────
const pkg = read('package.json')
check('package.json verify:pos360-payments-closeout script', pkg.includes('verify:pos360-payments-closeout'))

// ── Summary ───────────────────────────────────────────────────────────────────
console.log(`\nPhase B.11 Prompt X — POS360 Payments Closeout Verification`)
console.log(`Passed: ${passed}`)
console.log(`Failed: ${failed}`)
console.log(`Total:  ${passed + failed}`)

if (failed > 0) {
  console.error(`\n${failed} check(s) failed.`)
  process.exit(1)
} else {
  console.log(`\nAll ${passed} checks passed.`)
}
