// Phase E.6 Verification Script — NOVEE OS Remote Module Distribution
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '../../')

const pass = []
const fail = []

function check(label, condition) {
  if (condition) pass.push(label)
  else fail.push(label)
}

function readFile(rel) {
  try { return fs.readFileSync(path.join(root, rel), 'utf8') } catch { return '' }
}

// ── Migration ─────────────────────────────────────────────────────────────────
const sql = readFile('server/db/migrations/064_novee_os_remote_module_distribution.sql')
check('MIGRATION: file 064 exists', sql.length > 0)
check('MIGRATION: module_deployment_packages table', sql.includes('novee_os_module_deployment_packages'))
check('MIGRATION: client_provisioning_requests table', sql.includes('novee_os_client_provisioning_requests'))
check('MIGRATION: invite_sessions table', sql.includes('novee_os_invite_sessions'))
check('MIGRATION: license_keys table', sql.includes('novee_os_license_keys'))
check('MIGRATION: module_activations table', sql.includes('novee_os_module_activations'))
check('MIGRATION: deployment_versions table', sql.includes('novee_os_deployment_versions'))
check('MIGRATION: rollback_records table', sql.includes('novee_os_rollback_records'))
check('MIGRATION: remote_distribution_audit_log table', sql.includes('novee_os_remote_distribution_audit_log'))
check('MIGRATION: no DROP statements', !sql.includes('DROP TABLE'))
check('MIGRATION: CREATE TABLE IF NOT EXISTS used', sql.includes('CREATE TABLE IF NOT EXISTS'))
check('MIGRATION: remote_distribution_ready DEFAULT FALSE', sql.includes('remote_distribution_ready BOOLEAN NOT NULL DEFAULT FALSE'))
check('MIGRATION: remote_distribution_enabled DEFAULT FALSE', sql.includes('remote_distribution_enabled BOOLEAN NOT NULL DEFAULT FALSE'))
check('MIGRATION: production_ready DEFAULT FALSE', sql.includes('production_ready BOOLEAN NOT NULL DEFAULT FALSE'))
check('MIGRATION: rollback_execution_enabled DEFAULT FALSE', sql.includes('rollback_execution_enabled BOOLEAN NOT NULL DEFAULT FALSE'))
check('MIGRATION: remote_activation_allowed DEFAULT FALSE in invite_sessions', sql.includes('remote_activation_allowed BOOLEAN NOT NULL DEFAULT FALSE'))

// ── Contracts ─────────────────────────────────────────────────────────────────
const contracts = readFile('server/services/noveeOS/noveeOSRemoteModuleDistributionContracts.js')
check('CONTRACTS: file exists', contracts.length > 0)
check('CONTRACTS: assertNoFakeRemoteDeliveryClaims', contracts.includes('assertNoFakeRemoteDeliveryClaims'))
check('CONTRACTS: assertNoFakeClientProvisioningClaims', contracts.includes('assertNoFakeClientProvisioningClaims'))
check('CONTRACTS: assertNoFakeInviteCompletionClaims', contracts.includes('assertNoFakeInviteCompletionClaims'))
check('CONTRACTS: assertNoFakeLicenseValidationClaims', contracts.includes('assertNoFakeLicenseValidationClaims'))
check('CONTRACTS: assertNoFakeTenantActivationClaims', contracts.includes('assertNoFakeTenantActivationClaims'))
check('CONTRACTS: assertNoFakeProductionActivationClaims', contracts.includes('assertNoFakeProductionActivationClaims'))
check('CONTRACTS: assertNoFakeRollbackExecutionClaims', contracts.includes('assertNoFakeRollbackExecutionClaims'))
check('CONTRACTS: assertNoRawDistributionSecrets', contracts.includes('assertNoRawDistributionSecrets'))
check('CONTRACTS: assertSecurityDeploymentPilotGatesRequired', contracts.includes('assertSecurityDeploymentPilotGatesRequired'))
check('CONTRACTS: assertRemoteDistributionBlockedUntilReady', contracts.includes('assertRemoteDistributionBlockedUntilReady'))
check('CONTRACTS: validateDeploymentPackagePayload', contracts.includes('validateDeploymentPackagePayload'))
check('CONTRACTS: validateProvisioningRequestPayload', contracts.includes('validateProvisioningRequestPayload'))
check('CONTRACTS: validateInviteSessionPayload', contracts.includes('validateInviteSessionPayload'))
check('CONTRACTS: validateLicenseKeyPayload', contracts.includes('validateLicenseKeyPayload'))
check('CONTRACTS: validateModuleActivationPayload', contracts.includes('validateModuleActivationPayload'))
check('CONTRACTS: validateDeploymentVersionPayload', contracts.includes('validateDeploymentVersionPayload'))
check('CONTRACTS: validateRollbackRecordPayload', contracts.includes('validateRollbackRecordPayload'))
check('CONTRACTS: DEFAULT_DEPLOYMENT_PACKAGES (11)', contracts.includes('DEFAULT_DEPLOYMENT_PACKAGES') && (contracts.match(/package_key:/g) || []).length >= 11)
check('CONTRACTS: DEFAULT_MODULE_ACTIVATIONS (13)', contracts.includes('DEFAULT_MODULE_ACTIVATIONS') && (contracts.match(/module_key:/g) || []).length >= 13)
check('CONTRACTS: DEFAULT_ROLLBACK_RECORDS', contracts.includes('DEFAULT_ROLLBACK_RECORDS'))
check('CONTRACTS: ALLOWED_PACKAGE_TYPES defined', contracts.includes('ALLOWED_PACKAGE_TYPES'))
check('CONTRACTS: ALLOWED_CLIENT_TYPES defined', contracts.includes('ALLOWED_CLIENT_TYPES'))
check('CONTRACTS: ALLOWED_INVITE_TYPES defined', contracts.includes('ALLOWED_INVITE_TYPES'))
check('CONTRACTS: ALLOWED_LICENSE_TYPES defined', contracts.includes('ALLOWED_LICENSE_TYPES'))
check('CONTRACTS: ALLOWED_ACTIVATION_MODES defined', contracts.includes('ALLOWED_ACTIVATION_MODES'))
check('CONTRACTS: FORBIDDEN_RAW_SECRET_FIELDS defined', contracts.includes('FORBIDDEN_RAW_SECRET_FIELDS'))
check('CONTRACTS: rollback_execution_enabled blocked', contracts.includes("rollback_execution_enabled must remain false"))

// ── Feature Flags ─────────────────────────────────────────────────────────────
const flags = readFile('server/config/noveeOSRemoteModuleDistributionFeatureFlags.js')
check('FLAGS: file exists', flags.length > 0)
check('FLAGS: NOVEE_REMOTE_MODULE_DISTRIBUTION_ENABLED: true', flags.includes('NOVEE_REMOTE_MODULE_DISTRIBUTION_ENABLED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_LIVE_DELIVERY_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_LIVE_DELIVERY_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_CLIENT_PROVISIONING_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_CLIENT_PROVISIONING_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_INVITE_LINKS_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_INVITE_LINKS_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_LICENSE_VALIDATION_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_LICENSE_VALIDATION_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_REMOTE_ACTIVATION_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_REMOTE_ACTIVATION_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_ROLLBACK_EXECUTION_ENABLED: false', flags.includes('NOVEE_REMOTE_MODULE_ROLLBACK_EXECUTION_ENABLED: false'))
check('FLAGS: NOVEE_REMOTE_MODULE_SECURITY_GATE_REQUIRED: true', flags.includes('NOVEE_REMOTE_MODULE_SECURITY_GATE_REQUIRED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_DEPLOYMENT_GATE_REQUIRED: true', flags.includes('NOVEE_REMOTE_MODULE_DEPLOYMENT_GATE_REQUIRED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_PILOT_GATE_REQUIRED: true', flags.includes('NOVEE_REMOTE_MODULE_PILOT_GATE_REQUIRED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_FAKE_DELIVERY_CLAIMS_BLOCKED: true', flags.includes('NOVEE_REMOTE_MODULE_FAKE_DELIVERY_CLAIMS_BLOCKED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_FAKE_LICENSE_CLAIMS_BLOCKED: true', flags.includes('NOVEE_REMOTE_MODULE_FAKE_LICENSE_CLAIMS_BLOCKED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_SECRET_EXPOSURE_BLOCKED: true', flags.includes('NOVEE_REMOTE_MODULE_SECRET_EXPOSURE_BLOCKED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_FRONTEND_SAFE_CLAIMS_ENABLED: true', flags.includes('NOVEE_REMOTE_MODULE_FRONTEND_SAFE_CLAIMS_ENABLED: true'))
check('FLAGS: NOVEE_REMOTE_MODULE_AUDIT_LOGGING_ENABLED: true', flags.includes('NOVEE_REMOTE_MODULE_AUDIT_LOGGING_ENABLED: true'))
check('FLAGS: getNoveeOSRemoteModuleDistributionFlags exported', flags.includes('getNoveeOSRemoteModuleDistributionFlags'))
check('FLAGS: export default', flags.includes('export default'))

// ── Service ──────────────────────────────────────────────────────────────────
const svc = readFile('server/services/noveeOS/noveeOSRemoteModuleDistributionService.js')
check('SERVICE: file exists', svc.length > 0)
check('SERVICE: getRemoteModuleDistributionSummary', svc.includes('export async function getRemoteModuleDistributionSummary'))
check('SERVICE: listModuleDeploymentPackages', svc.includes('export async function listModuleDeploymentPackages'))
check('SERVICE: getModuleDeploymentPackage', svc.includes('export async function getModuleDeploymentPackage'))
check('SERVICE: createModuleDeploymentPackagePreview', svc.includes('export async function createModuleDeploymentPackagePreview'))
check('SERVICE: updateModuleDeploymentPackageStatusPreview', svc.includes('export async function updateModuleDeploymentPackageStatusPreview'))
check('SERVICE: listClientProvisioningRequests', svc.includes('export async function listClientProvisioningRequests'))
check('SERVICE: getClientProvisioningRequest', svc.includes('export async function getClientProvisioningRequest'))
check('SERVICE: createClientProvisioningRequestPreview', svc.includes('export async function createClientProvisioningRequestPreview'))
check('SERVICE: updateClientProvisioningRequestStatusPreview', svc.includes('export async function updateClientProvisioningRequestStatusPreview'))
check('SERVICE: listInviteSessions', svc.includes('export async function listInviteSessions'))
check('SERVICE: getInviteSession', svc.includes('export async function getInviteSession'))
check('SERVICE: createInviteSessionPreview', svc.includes('export async function createInviteSessionPreview'))
check('SERVICE: updateInviteSessionStatusPreview', svc.includes('export async function updateInviteSessionStatusPreview'))
check('SERVICE: listLicenseKeys', svc.includes('export async function listLicenseKeys'))
check('SERVICE: getLicenseKey', svc.includes('export async function getLicenseKey'))
check('SERVICE: createLicenseKeyPreview', svc.includes('export async function createLicenseKeyPreview'))
check('SERVICE: updateLicenseKeyStatusPreview', svc.includes('export async function updateLicenseKeyStatusPreview'))
check('SERVICE: listModuleActivations', svc.includes('export async function listModuleActivations'))
check('SERVICE: getModuleActivation', svc.includes('export async function getModuleActivation'))
check('SERVICE: createModuleActivationPreview', svc.includes('export async function createModuleActivationPreview'))
check('SERVICE: updateModuleActivationStatusPreview', svc.includes('export async function updateModuleActivationStatusPreview'))
check('SERVICE: listDeploymentVersions', svc.includes('export async function listDeploymentVersions'))
check('SERVICE: getDeploymentVersion', svc.includes('export async function getDeploymentVersion'))
check('SERVICE: createDeploymentVersionPreview', svc.includes('export async function createDeploymentVersionPreview'))
check('SERVICE: updateDeploymentVersionStatusPreview', svc.includes('export async function updateDeploymentVersionStatusPreview'))
check('SERVICE: listRollbackRecords', svc.includes('export async function listRollbackRecords'))
check('SERVICE: getRollbackRecord', svc.includes('export async function getRollbackRecord'))
check('SERVICE: createRollbackRecordPreview', svc.includes('export async function createRollbackRecordPreview'))
check('SERVICE: updateRollbackRecordStatusPreview', svc.includes('export async function updateRollbackRecordStatusPreview'))
check('SERVICE: getSecurityGateDependency', svc.includes('export async function getSecurityGateDependency'))
check('SERVICE: getDeploymentGateDependency', svc.includes('export async function getDeploymentGateDependency'))
check('SERVICE: getPilotGateDependency', svc.includes('export async function getPilotGateDependency'))
check('SERVICE: getRemoteDistributionReadinessScore', svc.includes('export async function getRemoteDistributionReadinessScore'))
check('SERVICE: getRemoteDistributionBlockers', svc.includes('export async function getRemoteDistributionBlockers'))
check('SERVICE: getSafeRemoteDistributionClaims', svc.includes('export async function getSafeRemoteDistributionClaims'))
check('SERVICE: writeRemoteDistributionAuditEvent', svc.includes('export async function writeRemoteDistributionAuditEvent'))
check('SERVICE: getRemoteDistributionAuditLog', svc.includes('export async function getRemoteDistributionAuditLog'))
check('SERVICE: getRemoteDistributionFeatureFlagSnapshot', svc.includes('export async function getRemoteDistributionFeatureFlagSnapshot'))
check('SERVICE: validateRemoteModuleDistributionReadiness', svc.includes('export async function validateRemoteModuleDistributionReadiness'))
check('SERVICE: safety_status BUILD_ONLY_NO_LIVE_REMOTE_DISTRIBUTION', svc.includes("'BUILD_ONLY_NO_LIVE_REMOTE_DISTRIBUTION'"))
check('SERVICE: remote_distribution_ready: false hardcoded', svc.includes('remote_distribution_ready: false'))
check('SERVICE: live_delivery_enabled: false hardcoded', svc.includes('live_delivery_enabled: false'))
check('SERVICE: rollback_execution_enabled: false hardcoded', svc.includes('rollback_execution_enabled: false'))
check('SERVICE: localFallback pattern', svc.includes('localFallback'))
check('SERVICE: no raw invite token exposure', !svc.includes('invite_token') || svc.includes('reference_only'))

// ── Controller ────────────────────────────────────────────────────────────────
const ctrl = readFile('server/controllers/noveeOSRemoteModuleDistributionController.js')
check('CONTROLLER: file exists', ctrl.length > 0)
check('CONTROLLER: ok500 pattern', ctrl.includes('const ok500 = (res, fn)'))
check('CONTROLLER: actorId pattern', ctrl.includes('const actorId = req =>'))
check('CONTROLLER: ikey pattern', ctrl.includes('const ikey = req =>'))
check('CONTROLLER: tenantId pattern', ctrl.includes('const tenantId = req =>'))
check('CONTROLLER: wrap helper', ctrl.includes('const wrap = (res, data)'))
check('CONTROLLER: productionReady: false in wrap', ctrl.includes('productionReady: false'))
check('CONTROLLER: securityReady: false in wrap', ctrl.includes('securityReady: false'))
check('CONTROLLER: deploymentReady: false in wrap', ctrl.includes('deploymentReady: false'))
check('CONTROLLER: pilotReady: false in wrap', ctrl.includes('pilotReady: false'))
check('CONTROLLER: remoteDistributionReady: false in wrap', ctrl.includes('remoteDistributionReady: false'))
check('CONTROLLER: safeClaim remote_module_distribution_center_exists', ctrl.includes('remote_module_distribution_center_exists'))
check('CONTROLLER: getRemoteModuleDistributionSummary', ctrl.includes('export async function getRemoteModuleDistributionSummary'))
check('CONTROLLER: listModuleDeploymentPackages', ctrl.includes('export async function listModuleDeploymentPackages'))
check('CONTROLLER: createClientProvisioningRequestPreview', ctrl.includes('export async function createClientProvisioningRequestPreview'))
check('CONTROLLER: createInviteSessionPreview', ctrl.includes('export async function createInviteSessionPreview'))
check('CONTROLLER: createLicenseKeyPreview', ctrl.includes('export async function createLicenseKeyPreview'))
check('CONTROLLER: createModuleActivationPreview', ctrl.includes('export async function createModuleActivationPreview'))
check('CONTROLLER: createRollbackRecordPreview', ctrl.includes('export async function createRollbackRecordPreview'))
check('CONTROLLER: getSecurityGateDependency', ctrl.includes('export async function getSecurityGateDependency'))
check('CONTROLLER: validateRemoteModuleDistributionReadiness', ctrl.includes('export async function validateRemoteModuleDistributionReadiness'))

// ── Routes ────────────────────────────────────────────────────────────────────
const routes = readFile('server/routes/noveeOSRemoteModuleDistributionRoutes.js')
check('ROUTES: file exists', routes.length > 0)
check('ROUTES: import express', routes.includes("import express from 'express'"))
check('ROUTES: import canAccessPOS3', routes.includes('canAccessPOS3'))
check('ROUTES: export default router', routes.includes('export default router'))
check('ROUTES: GET /summary', routes.includes("router.get('/summary'"))
check('ROUTES: GET /packages', routes.includes("router.get('/packages'"))
check('ROUTES: GET /packages/:packageId', routes.includes("router.get('/packages/:packageId'"))
check('ROUTES: POST /packages/preview canAccessPOS3', routes.includes("router.post('/packages/preview', canAccessPOS3"))
check('ROUTES: PATCH /packages/:packageId/status-preview', routes.includes("router.patch('/packages/:packageId/status-preview'"))
check('ROUTES: GET /provisioning-requests', routes.includes("router.get('/provisioning-requests'"))
check('ROUTES: GET /provisioning-requests/:provisioningRequestId', routes.includes("router.get('/provisioning-requests/:provisioningRequestId'"))
check('ROUTES: POST /provisioning-requests/preview', routes.includes("router.post('/provisioning-requests/preview'"))
check('ROUTES: PATCH /provisioning-requests/:provisioningRequestId/status-preview', routes.includes("router.patch('/provisioning-requests/:provisioningRequestId/status-preview'"))
check('ROUTES: GET /invite-sessions', routes.includes("router.get('/invite-sessions'"))
check('ROUTES: GET /invite-sessions/:inviteSessionId', routes.includes("router.get('/invite-sessions/:inviteSessionId'"))
check('ROUTES: POST /invite-sessions/preview', routes.includes("router.post('/invite-sessions/preview'"))
check('ROUTES: PATCH /invite-sessions/:inviteSessionId/status-preview', routes.includes("router.patch('/invite-sessions/:inviteSessionId/status-preview'"))
check('ROUTES: GET /license-keys', routes.includes("router.get('/license-keys'"))
check('ROUTES: GET /license-keys/:licenseKeyId', routes.includes("router.get('/license-keys/:licenseKeyId'"))
check('ROUTES: POST /license-keys/preview', routes.includes("router.post('/license-keys/preview'"))
check('ROUTES: PATCH /license-keys/:licenseKeyId/status-preview', routes.includes("router.patch('/license-keys/:licenseKeyId/status-preview'"))
check('ROUTES: GET /module-activations', routes.includes("router.get('/module-activations'"))
check('ROUTES: GET /module-activations/:moduleActivationId', routes.includes("router.get('/module-activations/:moduleActivationId'"))
check('ROUTES: POST /module-activations/preview', routes.includes("router.post('/module-activations/preview'"))
check('ROUTES: PATCH /module-activations/:moduleActivationId/status-preview', routes.includes("router.patch('/module-activations/:moduleActivationId/status-preview'"))
check('ROUTES: GET /deployment-versions', routes.includes("router.get('/deployment-versions'"))
check('ROUTES: GET /deployment-versions/:deploymentVersionId', routes.includes("router.get('/deployment-versions/:deploymentVersionId'"))
check('ROUTES: GET /rollback-records', routes.includes("router.get('/rollback-records'"))
check('ROUTES: GET /rollback-records/:rollbackRecordId', routes.includes("router.get('/rollback-records/:rollbackRecordId'"))
check('ROUTES: GET /security-gate-dependency', routes.includes("router.get('/security-gate-dependency'"))
check('ROUTES: GET /deployment-gate-dependency', routes.includes("router.get('/deployment-gate-dependency'"))
check('ROUTES: GET /pilot-gate-dependency', routes.includes("router.get('/pilot-gate-dependency'"))
check('ROUTES: GET /readiness-score', routes.includes("router.get('/readiness-score'"))
check('ROUTES: GET /blockers', routes.includes("router.get('/blockers'"))
check('ROUTES: GET /safe-claims', routes.includes("router.get('/safe-claims'"))
check('ROUTES: GET /audit-log', routes.includes("router.get('/audit-log'"))
check('ROUTES: GET /feature-flags', routes.includes("router.get('/feature-flags'"))
check('ROUTES: GET /validate-readiness', routes.includes("router.get('/validate-readiness'"))

// ── server/index.js ───────────────────────────────────────────────────────────
const idx = readFile('server/index.js')
check('INDEX: import noveeOSRemoteModuleDistributionRoutes', idx.includes('noveeOSRemoteModuleDistributionRoutes'))
check('INDEX: mount /api/novee-os/remote-distribution', idx.includes('/api/novee-os/remote-distribution'))

// ── Frontend page ─────────────────────────────────────────────────────────────
const page = readFile('src/pages/noveeOS/RemoteModuleDistribution.jsx')
check('FRONTEND: file exists', page.length > 0)
check('FRONTEND: export default function RemoteModuleDistribution', page.includes('export default function RemoteModuleDistribution'))
check('FRONTEND: API = /api/novee-os/remote-distribution', page.includes('/api/novee-os/remote-distribution'))
check('FRONTEND: Panel A — Summary', page.includes('A —'))
check('FRONTEND: Panel B — Package Registry', page.includes('B —'))
check('FRONTEND: Panel C — Client Provisioning', page.includes('C —'))
check('FRONTEND: Panel D — Invite Sessions', page.includes('D —'))
check('FRONTEND: Panel E — License Keys', page.includes('E —'))
check('FRONTEND: Panel F — Module Activations', page.includes('F —'))
check('FRONTEND: Panel G — Deployment Versions', page.includes('G —'))
check('FRONTEND: Panel H — Rollback Records', page.includes('H —'))
check('FRONTEND: Panel I — Blockers', page.includes('I —'))
check('FRONTEND: Panel J — Safe Claims', page.includes('J —'))
check('FRONTEND: Panel K — Audit Log', page.includes('K —'))
check('FRONTEND: Panel L — Feature Flags', page.includes('L —'))
check('FRONTEND: safety banner BUILD ONLY', page.includes('BUILD ONLY'))
check('FRONTEND: rollback execution disabled warning', page.includes('ROLLBACK EXECUTION IS DISABLED') || page.includes('EXECUTION DISABLED'))
check('FRONTEND: no raw tokens note', page.includes('raw invite tokens') || page.includes('no raw tokens'))
check('FRONTEND: no raw keys note', page.includes('raw license keys') || page.includes('no raw keys'))
check('FRONTEND: module activation registry 13 modules', page.includes('13'))
check('FRONTEND: NAVY color', page.includes('#0a0d14'))
check('FRONTEND: GOLD color', page.includes('#c9952c'))
check('FRONTEND: AMBI in module list', page.includes('AMBI'))
check('FRONTEND: Agent X in module list', page.includes('Agent X'))
check('FRONTEND: EgoMusic in module list', page.includes('EgoMusic'))
// SmokeCraft must remain not production-ready
check('FRONTEND: SmokeCraft shown but not production-ready', !page.includes('smokecraft_production_ready: true') && !page.includes("SmokeCraft.*production.*ready.*true"))

// ── App.jsx ───────────────────────────────────────────────────────────────────
const app = readFile('src/App.jsx')
check('APP: import RemoteModuleDistribution', app.includes('RemoteModuleDistribution'))
check('APP: route novee-os/remote-distribution', app.includes('novee-os/remote-distribution'))

// ── NoveeOSCommandCenter.jsx ──────────────────────────────────────────────────
const cmd = readFile('src/pages/noveeOS/NoveeOSCommandCenter.jsx')
check('COMMAND CENTER: E.6 links to /novee-os/remote-distribution', cmd.includes('/novee-os/remote-distribution'))
check('COMMAND CENTER: E.6 shows built-hidden', cmd.includes("'E.6 — Remote Module Distribution'") && cmd.includes('built-hidden'))
check('COMMAND CENTER: E.7 remains pending', cmd.includes("'E.7 — Onboarding + Training'") && cmd.includes('missing'))
check('COMMAND CENTER: E.8 remains pending', cmd.includes("'E.8 — AMBI Foundation'") && cmd.includes('missing'))
check('COMMAND CENTER: E.9 remains pending', cmd.includes("'E.9 — Documentation Portal'") && cmd.includes('missing'))
check('COMMAND CENTER: E.10 remains pending', cmd.includes("'E.10 — Final Go-Live Gate'") && cmd.includes('missing'))

// ── NoveeHome ─────────────────────────────────────────────────────────────────
const home = readFile('src/pages/NoveeHome.jsx')
check('NOVEE HOME: E.6 Remote Module Distribution link', home.includes('remote-distribution'))

// ── Docs ─────────────────────────────────────────────────────────────────────
const docs = readFile('docs/PHASE_E_6_REMOTE_MODULE_DISTRIBUTION.md')
check('DOCS: file exists', docs.length > 0)
check('DOCS: BUILD ONLY safety note', docs.includes('BUILD ONLY') || docs.includes('BUILD_ONLY'))
check('DOCS: What Is NOT Live section', docs.includes('NOT Live'))
check('DOCS: Safe Sales Language section', docs.includes('Safe Sales Language'))
check('DOCS: Unsafe Sales Language section', docs.includes('Unsafe Sales Language'))
check('DOCS: E.3/E.4/E.5 dependencies documented', docs.includes('E.3') && docs.includes('E.4') && docs.includes('E.5'))
check('DOCS: Readiness Checklist section', docs.includes('Readiness Checklist'))
check('DOCS: AMBI name-only noted', docs.includes('AMBI'))
check('DOCS: rollback execution disabled noted', docs.includes('rollback'))

// ── package.json ──────────────────────────────────────────────────────────────
const pkg = readFile('package.json')
check('PACKAGE: verify:phase-e6-remote-module-distribution script', pkg.includes('verify:phase-e6-remote-module-distribution'))

// ── Summary ───────────────────────────────────────────────────────────────────
console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
console.log('  Phase E.6 — NOVEE OS Remote Module Distribution Verification')
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
console.log(`\n  PASS: ${pass.length}`)
console.log(`  FAIL: ${fail.length}`)
if (fail.length > 0) {
  console.log('\n  FAILURES:')
  fail.forEach(f => console.log(`    ✗ ${f}`))
}
console.log('\n' + (fail.length === 0
  ? `  ✓ ALL ${pass.length} CHECKS PASSED — Phase E.6 verified`
  : `  ✗ ${fail.length} checks failed — fix before committing`))
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')
process.exit(fail.length > 0 ? 1 : 0)
