import { readFileSync } from 'fs'
import { resolve } from 'path'

const root = resolve(process.cwd())
const read = p => readFileSync(resolve(root, p), 'utf8')

let pass = 0; let fail = 0
function check(label, condition) {
  if (condition) { pass++ } else { fail++; console.error(`FAIL: ${label}`) }
}

const sql = read('server/db/migrations/043_pos360_reports_analytics_decision_layer.sql')
const contracts = read('server/services/pos360/pos360ReportsContracts.js')
const flags = read('server/config/pos360ReportsFeatureFlags.js')
const locales = read('src/locales/pos360Reports.js')
const service = read('server/services/pos360/pos360ReportsAnalyticsDecisionService.js')
const controller = read('server/controllers/pos360ReportsAnalyticsDecisionController.js')
const routes = read('server/routes/pos360ReportsAnalyticsDecisionRoutes.js')
const ui = read('src/pages/pos360/POS360ReportsAnalyticsDecision.jsx')
const index = read('server/index.js')
const app = read('src/App.jsx')
const pkg = read('package.json')

// ── Migration ───────────────────────────────────────────────────────────────
check('migration: file exists', sql.length > 100)
check('migration: pos360_report_definitions', sql.includes('pos360_report_definitions'))
check('migration: pos360_report_kpi_definitions', sql.includes('pos360_report_kpi_definitions'))
check('migration: pos360_report_kpi_thresholds', sql.includes('pos360_report_kpi_thresholds'))
check('migration: pos360_report_snapshots', sql.includes('pos360_report_snapshots'))
check('migration: pos360_report_snapshot_sections', sql.includes('pos360_report_snapshot_sections'))
check('migration: pos360_dashboard_profiles', sql.includes('pos360_dashboard_profiles'))
check('migration: pos360_dashboard_widgets', sql.includes('pos360_dashboard_widgets'))
check('migration: pos360_dashboard_view_events', sql.includes('pos360_dashboard_view_events'))
check('migration: pos360_daily_operations_reports', sql.includes('pos360_daily_operations_reports'))
check('migration: pos360_daily_closeout_report_links', sql.includes('pos360_daily_closeout_report_links'))
check('migration: pos360_staff_performance_report_links', sql.includes('pos360_staff_performance_report_links'))
check('migration: pos360_guest_intelligence_report_links', sql.includes('pos360_guest_intelligence_report_links'))
check('migration: pos360_inventory_health_report_links', sql.includes('pos360_inventory_health_report_links'))
check('migration: pos360_event_package_report_links', sql.includes('pos360_event_package_report_links'))
check('migration: pos360_payment_analytics_report_links', sql.includes('pos360_payment_analytics_report_links'))
check('migration: pos360_alert_rules', sql.includes('pos360_alert_rules'))
check('migration: pos360_alert_events', sql.includes('pos360_alert_events'))
check('migration: pos360_eat_decision_insights', sql.includes('pos360_eat_decision_insights'))
check('migration: pos360_report_export_requests', sql.includes('pos360_report_export_requests'))
check('migration: pos360_scheduled_report_contracts', sql.includes('pos360_scheduled_report_contracts'))
check('migration: pos360_bi_provider_profiles', sql.includes('pos360_bi_provider_profiles'))
check('migration: pos360_report_offline_queue', sql.includes('pos360_report_offline_queue'))
check('migration: pos360_report_audit', sql.includes('pos360_report_audit'))
check('migration: no DROP TABLE', !sql.includes('DROP TABLE'))
check('migration: CREATE TABLE IF NOT EXISTS on snapshots', sql.includes('CREATE TABLE IF NOT EXISTS pos360_report_snapshots'))
check('migration: CREATE TABLE IF NOT EXISTS on audit', sql.includes('CREATE TABLE IF NOT EXISTS pos360_report_audit'))
check('migration: venue_id present', sql.includes('venue_id'))
check('migration: report_date field', sql.includes('report_date'))
check('migration: date_range_start', sql.includes('date_range_start'))
check('migration: date_range_end', sql.includes('date_range_end'))
check('migration: payment_record_id nullable', sql.includes('payment_record_id'))
check('migration: server_closeout_id nullable', sql.includes('server_closeout_id'))
check('migration: shift_closeout_id nullable', sql.includes('shift_closeout_id'))
check('migration: daily_closeout_id nullable', sql.includes('daily_closeout_id'))
check('migration: cash_drawer_id nullable', sql.includes('cash_drawer_id'))
check('migration: staff_profile_id nullable', sql.includes('staff_profile_id'))
check('migration: reservation_id nullable', sql.includes('reservation_id'))
check('migration: waitlist_entry_id nullable', sql.includes('waitlist_entry_id'))
check('migration: private_event_id nullable', sql.includes('private_event_id'))
check('migration: package_selection_id nullable', sql.includes('package_selection_id'))
check('migration: customer_id nullable', sql.includes('customer_id'))
check('migration: inventory_item_id nullable', sql.includes('inventory_item_id'))
check('migration: vendor_id nullable', sql.includes('vendor_id'))
check('migration: contains_secrets DEFAULT FALSE on audit', sql.includes('contains_secrets') && sql.includes('DEFAULT FALSE'))
check('migration: exposes_private_data DEFAULT TRUE', sql.includes('exposes_private_data') && sql.includes('DEFAULT TRUE'))
check('migration: exposes_financial_data DEFAULT TRUE', sql.includes('exposes_financial_data') && sql.includes('DEFAULT TRUE'))
check('migration: contains_ai_generated_content DEFAULT FALSE', sql.includes('contains_ai_generated_content') && sql.includes('DEFAULT FALSE'))
check('migration: export_completed DEFAULT FALSE', sql.includes('export_completed') && sql.includes('DEFAULT FALSE'))
check('migration: delivery_completed DEFAULT FALSE', sql.includes('delivery_completed') && sql.includes('DEFAULT FALSE'))
check('migration: bi_connected DEFAULT FALSE', sql.includes('bi_connected') && sql.includes('DEFAULT FALSE'))
check('migration: stores_secrets DEFAULT FALSE on BI provider', sql.includes('stores_secrets') && sql.includes('DEFAULT FALSE'))
check('migration: idempotency_key present', sql.includes('idempotency_key'))
check('migration: generated_from_real_data DEFAULT FALSE', sql.includes('generated_from_real_data') && sql.includes('DEFAULT FALSE'))

// ── Contracts ───────────────────────────────────────────────────────────────
check('contracts: REPORT_TYPES', contracts.includes('REPORT_TYPES'))
check('contracts: executive type', contracts.includes("'executive'"))
check('contracts: daily_operations type', contracts.includes("'daily_operations'"))
check('contracts: closeout type', contracts.includes("'closeout'"))
check('contracts: eat type', contracts.includes("'eat'"))
check('contracts: KPI_GROUPS', contracts.includes('KPI_GROUPS'))
check('contracts: revenue kpi group', contracts.includes("'revenue'"))
check('contracts: THRESHOLD_TYPES', contracts.includes('THRESHOLD_TYPES'))
check('contracts: warning threshold', contracts.includes("'warning'"))
check('contracts: COMPARISON_OPERATORS', contracts.includes('COMPARISON_OPERATORS'))
check('contracts: gt operator', contracts.includes("'gt'"))
check('contracts: SNAPSHOT_STATUSES', contracts.includes('SNAPSHOT_STATUSES'))
check('contracts: locked status', contracts.includes("'locked'"))
check('contracts: generated_placeholder status', contracts.includes("'generated_placeholder'"))
check('contracts: DASHBOARD_TYPES', contracts.includes('DASHBOARD_TYPES'))
check('contracts: owner dashboard type', contracts.includes("'owner'"))
check('contracts: eat dashboard type', contracts.includes("'eat'"))
check('contracts: WIDGET_TYPES', contracts.includes('WIDGET_TYPES'))
check('contracts: kpi_card widget', contracts.includes("'kpi_card'"))
check('contracts: eat_decision widget', contracts.includes("'eat_decision'"))
check('contracts: ALERT_TYPES', contracts.includes('ALERT_TYPES'))
check('contracts: inventory_low alert', contracts.includes("'inventory_low'"))
check('contracts: void_spike alert', contracts.includes("'void_spike'"))
check('contracts: ALERT_SEVERITIES', contracts.includes('ALERT_SEVERITIES'))
check('contracts: critical severity', contracts.includes("'critical'"))
check('contracts: ALERT_STATUSES', contracts.includes('ALERT_STATUSES'))
check('contracts: acknowledged status', contracts.includes("'acknowledged'"))
check('contracts: DECISION_INSIGHT_TYPES', contracts.includes('DECISION_INSIGHT_TYPES'))
check('contracts: operations_recommendation', contracts.includes("'operations_recommendation'"))
check('contracts: DECISION_STATUSES', contracts.includes('DECISION_STATUSES'))
check('contracts: placeholder decision', contracts.includes("'placeholder'"))
check('contracts: unavailable decision', contracts.includes("'unavailable'"))
check('contracts: EXPORT_TYPES', contracts.includes('EXPORT_TYPES'))
check('contracts: pdf export', contracts.includes("'pdf'"))
check('contracts: csv export', contracts.includes("'csv'"))
check('contracts: external_bi export', contracts.includes("'external_bi'"))
check('contracts: EXPORT_STATUSES', contracts.includes('EXPORT_STATUSES'))
check('contracts: SCHEDULED_CADENCES', contracts.includes('SCHEDULED_CADENCES'))
check('contracts: daily cadence', contracts.includes("'daily'"))
check('contracts: DELIVERY_CHANNELS', contracts.includes('DELIVERY_CHANNELS'))
check('contracts: none channel', contracts.includes("'none'"))
check('contracts: SCHEDULE_STATUSES', contracts.includes('SCHEDULE_STATUSES'))
check('contracts: active_placeholder', contracts.includes("'active_placeholder'"))
check('contracts: BI_PROVIDERS', contracts.includes('BI_PROVIDERS'))
check('contracts: looker provider', contracts.includes("'looker'"))
check('contracts: powerbi provider', contracts.includes("'powerbi'"))
check('contracts: PROVIDER_STATUSES', contracts.includes('PROVIDER_STATUSES'))
check('contracts: not_connected status', contracts.includes("'not_connected'"))
check('contracts: isValidReportType', contracts.includes('isValidReportType'))
check('contracts: isValidKpiGroup', contracts.includes('isValidKpiGroup'))
check('contracts: isValidThresholdType', contracts.includes('isValidThresholdType'))
check('contracts: isValidComparisonOperator', contracts.includes('isValidComparisonOperator'))
check('contracts: isValidSnapshotStatus', contracts.includes('isValidSnapshotStatus'))
check('contracts: isValidDashboardType', contracts.includes('isValidDashboardType'))
check('contracts: isValidWidgetType', contracts.includes('isValidWidgetType'))
check('contracts: isValidAlertType', contracts.includes('isValidAlertType'))
check('contracts: isValidAlertSeverity', contracts.includes('isValidAlertSeverity'))
check('contracts: isValidAlertStatus', contracts.includes('isValidAlertStatus'))
check('contracts: isValidDecisionInsightType', contracts.includes('isValidDecisionInsightType'))
check('contracts: isValidDecisionStatus', contracts.includes('isValidDecisionStatus'))
check('contracts: isValidExportType', contracts.includes('isValidExportType'))
check('contracts: isValidExportStatus', contracts.includes('isValidExportStatus'))
check('contracts: isValidScheduledCadence', contracts.includes('isValidScheduledCadence'))
check('contracts: isValidDeliveryChannel', contracts.includes('isValidDeliveryChannel'))
check('contracts: isValidScheduleStatus', contracts.includes('isValidScheduleStatus'))
check('contracts: isValidBiProvider', contracts.includes('isValidBiProvider'))
check('contracts: isValidProviderStatus', contracts.includes('isValidProviderStatus'))

// ── Feature Flags ───────────────────────────────────────────────────────────
check('flags: file exists', flags.length > 100)
check('flags: DEFAULT_POS360_REPORTS_FLAGS', flags.includes('DEFAULT_POS360_REPORTS_FLAGS'))
check('flags: getReportsFlags', flags.includes('getReportsFlags'))
check('flags: reportsEnabled', flags.includes('reportsEnabled'))
check('flags: executiveDashboardsEnabled', flags.includes('executiveDashboardsEnabled'))
check('flags: dailyOperationsReportsEnabled', flags.includes('dailyOperationsReportsEnabled'))
check('flags: closeoutReportsEnabled', flags.includes('closeoutReportsEnabled'))
check('flags: paymentAnalyticsEnabled', flags.includes('paymentAnalyticsEnabled'))
check('flags: staffAnalyticsEnabled', flags.includes('staffAnalyticsEnabled'))
check('flags: guestAnalyticsEnabled', flags.includes('guestAnalyticsEnabled'))
check('flags: inventoryHealthReportsEnabled', flags.includes('inventoryHealthReportsEnabled'))
check('flags: smokeCraftEngagementReportsEnabled', flags.includes('smokeCraftEngagementReportsEnabled'))
check('flags: eatDecisionLayerEnabled', flags.includes('eatDecisionLayerEnabled'))
check('flags: reportSnapshotsEnabled', flags.includes('reportSnapshotsEnabled'))
check('flags: kpiDefinitionsEnabled', flags.includes('kpiDefinitionsEnabled'))
check('flags: alertRulesEnabled', flags.includes('alertRulesEnabled'))
check('flags: exportRequestsEnabled', flags.includes('exportRequestsEnabled'))
check('flags: scheduledReportsEnabled', flags.includes('scheduledReportsEnabled'))
check('flags: biProviderContractsEnabled', flags.includes('biProviderContractsEnabled'))
check('flags: offlineReportQueueEnabled', flags.includes('offlineReportQueueEnabled'))
check('flags: noFakeRevenueEnforced', flags.includes('noFakeRevenueEnforced'))
check('flags: noFakeProfitEnforced', flags.includes('noFakeProfitEnforced'))
check('flags: noFakeExportsEnforced', flags.includes('noFakeExportsEnforced'))
check('flags: noFakeEatAiEnforced', flags.includes('noFakeEatAiEnforced'))
check('flags: canAccessPOS3ProtectionRequired', flags.includes('canAccessPOS3ProtectionRequired'))
check('flags: 35+ flags total', (flags.match(/:/g) || []).length >= 35)

// ── Locales ─────────────────────────────────────────────────────────────────
check('locales: file exists', locales.length > 100)
check('locales: en-US', locales.includes("'en-US'"))
check('locales: es-DO', locales.includes("'es-DO'"))
check('locales: es', locales.includes("'es'"))
check('locales: ht', locales.includes("'ht'"))
check('locales: de', locales.includes("'de'"))
check('locales: pt', locales.includes("'pt'"))
check('locales: tReports export', locales.includes('tReports'))
check('locales: getSupportedReportsLanguages export', locales.includes('getSupportedReportsLanguages'))
check('locales: bi_not_connected label', locales.includes('bi_not_connected'))
check('locales: export_not_completed label', locales.includes('export_not_completed'))
check('locales: scheduled_delivery_not_sent label', locales.includes('scheduled_delivery_not_sent'))
check('locales: no_fake_revenue label', locales.includes('no_fake_revenue'))
check('locales: no_fake_profit label', locales.includes('no_fake_profit'))
check('locales: no_ai_insight_generated label', locales.includes('no_ai_insight_generated'))
check('locales: private_data_protected label', locales.includes('private_data_protected'))
check('locales: financial_data_protected label', locales.includes('financial_data_protected'))
check('locales: offline_queue_note label', locales.includes('offline_queue_note'))
check('locales: real_data_required label', locales.includes('real_data_required'))
check('locales: eat_not_connected label', locales.includes('eat_not_connected'))
check('locales: report_placeholder label', locales.includes('report_placeholder'))

// ── Service ─────────────────────────────────────────────────────────────────
check('service: file exists', service.length > 100)
check('service: falls back gracefully', service.includes('Falls back gracefully when no database connection is configured'))
check('service: never logs db string', service.includes('Never prints or logs the database connection string'))
check('service: isDbAvailable import', service.includes('isDbAvailable'))
check('service: connection.js import', service.includes("from '../../db/connection.js'"))
check('service: AREA constant', service.includes("AREA = 'pos360-reports-analytics-decision'"))
check('service: localPreview true', service.includes('localPreview: true'))
check('service: database_not_configured', service.includes("'database_not_configured'"))
check('service: auditRecord helper', service.includes('auditRecord'))
check('service: contains_secrets false in audit', service.includes('contains_secrets') && service.includes('FALSE') || service.includes('contains_secrets') && service.includes('false'))
check('service: createReportDefinition', service.includes('createReportDefinition'))
check('service: listReportDefinitions', service.includes('listReportDefinitions'))
check('service: createKpiDefinition', service.includes('createKpiDefinition'))
check('service: listKpiDefinitions', service.includes('listKpiDefinitions'))
check('service: createKpiThreshold', service.includes('createKpiThreshold'))
check('service: listKpiThresholds', service.includes('listKpiThresholds'))
check('service: updateKpiThreshold', service.includes('updateKpiThreshold'))
check('service: createReportSnapshotPlaceholder', service.includes('createReportSnapshotPlaceholder'))
check('service: getReportSnapshot', service.includes('getReportSnapshot'))
check('service: listReportSnapshots', service.includes('listReportSnapshots'))
check('service: lockReportSnapshot', service.includes('lockReportSnapshot'))
check('service: createReportSnapshotSection', service.includes('createReportSnapshotSection'))
check('service: createDashboardProfile', service.includes('createDashboardProfile'))
check('service: listDashboardProfiles', service.includes('listDashboardProfiles'))
check('service: createDashboardWidget', service.includes('createDashboardWidget'))
check('service: listDashboardWidgets', service.includes('listDashboardWidgets'))
check('service: recordDashboardViewEvent', service.includes('recordDashboardViewEvent'))
check('service: getExecutiveDashboardSummary', service.includes('getExecutiveDashboardSummary'))
check('service: createDailyOperationsReportPlaceholder', service.includes('createDailyOperationsReportPlaceholder'))
check('service: getDailyOperationsReport', service.includes('getDailyOperationsReport'))
check('service: listDailyOperationsReports', service.includes('listDailyOperationsReports'))
check('service: createDailyCloseoutReportLink', service.includes('createDailyCloseoutReportLink'))
check('service: listDailyCloseoutReportLinks', service.includes('listDailyCloseoutReportLinks'))
check('service: createStaffPerformanceReportLink', service.includes('createStaffPerformanceReportLink'))
check('service: createGuestIntelligenceReportLink', service.includes('createGuestIntelligenceReportLink'))
check('service: createInventoryHealthReportLink', service.includes('createInventoryHealthReportLink'))
check('service: createEventPackageReportLink', service.includes('createEventPackageReportLink'))
check('service: createPaymentAnalyticsReportLink', service.includes('createPaymentAnalyticsReportLink'))
check('service: listCrossModuleReportLinks', service.includes('listCrossModuleReportLinks'))
check('service: createAlertRule', service.includes('createAlertRule'))
check('service: listAlertRules', service.includes('listAlertRules'))
check('service: updateAlertRule', service.includes('updateAlertRule'))
check('service: createAlertEvent', service.includes('createAlertEvent'))
check('service: listAlertEvents', service.includes('listAlertEvents'))
check('service: acknowledgeAlertEvent', service.includes('acknowledgeAlertEvent'))
check('service: resolveAlertEvent', service.includes('resolveAlertEvent'))
check('service: createEatDecisionInsightPlaceholder', service.includes('createEatDecisionInsightPlaceholder'))
check('service: listEatDecisionInsights', service.includes('listEatDecisionInsights'))
check('service: reviewEatDecisionInsight', service.includes('reviewEatDecisionInsight'))
check('service: getEatDecisionSummary', service.includes('getEatDecisionSummary'))
check('service: createReportExportRequest', service.includes('createReportExportRequest'))
check('service: listReportExportRequests', service.includes('listReportExportRequests'))
check('service: markReportExportReadyPlaceholder', service.includes('markReportExportReadyPlaceholder'))
check('service: createScheduledReportContract', service.includes('createScheduledReportContract'))
check('service: listScheduledReportContracts', service.includes('listScheduledReportContracts'))
check('service: updateScheduledReportStatus', service.includes('updateScheduledReportStatus'))
check('service: createBiProviderProfile', service.includes('createBiProviderProfile'))
check('service: listBiProviderProfiles', service.includes('listBiProviderProfiles'))
check('service: updateBiProviderStatus', service.includes('updateBiProviderStatus'))
check('service: queueOfflineReportAction', service.includes('queueOfflineReportAction'))
check('service: listOfflineReportQueue', service.includes('listOfflineReportQueue'))
check('service: markOfflineReportActionSynced', service.includes('markOfflineReportActionSynced'))
check('service: idempotencyKey required on mutations', service.includes("'idempotencyKey_required'"))
check('service: no fake revenue honest note', service.includes('Revenue') && service.includes('real data'))
check('service: no fake profit honest note', service.includes('profit') || service.includes('Profit'))
check('service: no fake order totals', service.includes('order'))
check('service: no fake payment totals', service.includes('payment') || service.includes('Payment'))
check('service: no fake closeout totals', service.includes('closeout') || service.includes('Closeout'))
check('service: no fake staff performance', service.includes('staff') || service.includes('Staff'))
check('service: no fake guest analytics', service.includes('guest') || service.includes('Guest'))
check('service: no fake inventory health', service.includes('inventory') || service.includes('Inventory'))
check('service: no fake SmokeCraft', service.includes('SmokeCraft') || service.includes('smokecraft'))
check('service: no fake EAT AI', service.includes('contains_ai_generated_content') && (service.includes('FALSE') || service.includes('false')))
check('service: export_completed FALSE', service.includes('export_completed') && (service.includes('FALSE') || service.includes('false')))
check('service: delivery_completed FALSE', service.includes('delivery_completed') && (service.includes('FALSE') || service.includes('false')))
check('service: bi_connected FALSE', service.includes('bi_connected') && (service.includes('FALSE') || service.includes('false')))
check('service: stores_secrets FALSE', service.includes('stores_secrets') && (service.includes('FALSE') || service.includes('false')))
check('service: honest empty state', service.includes('honestNote') || service.includes('localPreview'))

// ── Controller ──────────────────────────────────────────────────────────────
check('controller: file exists', controller.length > 100)
check('controller: ok500 pattern', controller.includes('ok500'))
check('controller: vid pattern', controller.includes('vid(req)'))
check('controller: actor pattern', controller.includes('actor(req)'))
check('controller: createReportDefinition', controller.includes('createReportDefinition'))
check('controller: listReportDefinitions', controller.includes('listReportDefinitions'))
check('controller: createKpiDefinition', controller.includes('createKpiDefinition'))
check('controller: createKpiThreshold', controller.includes('createKpiThreshold'))
check('controller: createReportSnapshotPlaceholder', controller.includes('createReportSnapshotPlaceholder'))
check('controller: lockReportSnapshot', controller.includes('lockReportSnapshot'))
check('controller: createDashboardProfile', controller.includes('createDashboardProfile'))
check('controller: getExecutiveDashboardSummary', controller.includes('getExecutiveDashboardSummary'))
check('controller: createDailyOperationsReportPlaceholder', controller.includes('createDailyOperationsReportPlaceholder'))
check('controller: createStaffPerformanceReportLink', controller.includes('createStaffPerformanceReportLink'))
check('controller: createGuestIntelligenceReportLink', controller.includes('createGuestIntelligenceReportLink'))
check('controller: createInventoryHealthReportLink', controller.includes('createInventoryHealthReportLink'))
check('controller: createEventPackageReportLink', controller.includes('createEventPackageReportLink'))
check('controller: createPaymentAnalyticsReportLink', controller.includes('createPaymentAnalyticsReportLink'))
check('controller: createAlertRule', controller.includes('createAlertRule'))
check('controller: acknowledgeAlertEvent', controller.includes('acknowledgeAlertEvent'))
check('controller: resolveAlertEvent', controller.includes('resolveAlertEvent'))
check('controller: createEatDecisionInsightPlaceholder', controller.includes('createEatDecisionInsightPlaceholder'))
check('controller: reviewEatDecisionInsight', controller.includes('reviewEatDecisionInsight'))
check('controller: getEatDecisionSummary', controller.includes('getEatDecisionSummary'))
check('controller: createReportExportRequest', controller.includes('createReportExportRequest'))
check('controller: markReportExportReadyPlaceholder', controller.includes('markReportExportReadyPlaceholder'))
check('controller: createScheduledReportContract', controller.includes('createScheduledReportContract'))
check('controller: createBiProviderProfile', controller.includes('createBiProviderProfile'))
check('controller: queueOfflineReportAction', controller.includes('queueOfflineReportAction'))
check('controller: markOfflineReportActionSynced', controller.includes('markOfflineReportActionSynced'))

// ── Routes ──────────────────────────────────────────────────────────────────
check('routes: file exists', routes.length > 100)
check('routes: canAccessPOS3 import', routes.includes('canAccessPOS3'))
check('routes: /definitions', routes.includes('/definitions'))
check('routes: /kpis', routes.includes('/kpis'))
check('routes: /kpi-thresholds', routes.includes('/kpi-thresholds'))
check('routes: /snapshots', routes.includes('/snapshots'))
check('routes: /snapshots lock', routes.includes('/lock'))
check('routes: /dashboards', routes.includes('/dashboards'))
check('routes: /executive-summary', routes.includes('/executive-summary'))
check('routes: /daily-operations', routes.includes('/daily-operations'))
check('routes: /daily-closeout-links', routes.includes('/daily-closeout-links'))
check('routes: /links', routes.includes('/links'))
check('routes: /links/staff-performance', routes.includes('/links/staff-performance'))
check('routes: /links/guest-intelligence', routes.includes('/links/guest-intelligence'))
check('routes: /links/inventory-health', routes.includes('/links/inventory-health'))
check('routes: /links/event-packages', routes.includes('/links/event-packages'))
check('routes: /links/payment-analytics', routes.includes('/links/payment-analytics'))
check('routes: /alerts/rules', routes.includes('/alerts/rules'))
check('routes: /alerts/events', routes.includes('/alerts/events'))
check('routes: /alerts acknowledge', routes.includes('/acknowledge'))
check('routes: /alerts resolve', routes.includes('/resolve'))
check('routes: /eat/decision-insights', routes.includes('/eat/decision-insights'))
check('routes: /eat/decision-summary', routes.includes('/eat/decision-summary'))
check('routes: /exports', routes.includes('/exports'))
check('routes: /exports ready-placeholder', routes.includes('/ready-placeholder'))
check('routes: /scheduled-reports', routes.includes('/scheduled-reports'))
check('routes: /bi-providers', routes.includes('/bi-providers'))
check('routes: /offline-queue', routes.includes('/offline-queue'))
check('routes: canAccessPOS3 on write for snapshots', routes.includes('canAccessPOS3') && routes.includes('createReportSnapshotPlaceholder'))
check('routes: canAccessPOS3 on write for alerts', routes.includes('canAccessPOS3') && routes.includes('createAlertRule'))
check('routes: canAccessPOS3 on write for eat', routes.includes('canAccessPOS3') && routes.includes('createEatDecisionInsightPlaceholder'))
check('routes: canAccessPOS3 on write for exports', routes.includes('canAccessPOS3') && routes.includes('createReportExportRequest'))
check('routes: canAccessPOS3 on write for bi-providers', routes.includes('canAccessPOS3') && routes.includes('createBiProviderProfile'))
check('routes: export default router', routes.includes('export default router'))

// ── Frontend ─────────────────────────────────────────────────────────────────
check('ui: file exists', ui.length > 100)
check('ui: ReportsDashboard component', ui.includes('ReportsDashboard'))
check('ui: ExecutiveDashboardPanel', ui.includes('ExecutiveDashboardPanel'))
check('ui: DailyOperationsPanel', ui.includes('DailyOperationsPanel'))
check('ui: DailyCloseoutIntelligencePanel', ui.includes('DailyCloseoutIntelligencePanel'))
check('ui: PaymentAnalyticsPanel', ui.includes('PaymentAnalyticsPanel'))
check('ui: StaffAnalyticsPanel', ui.includes('StaffAnalyticsPanel'))
check('ui: GuestAnalyticsPanel', ui.includes('GuestAnalyticsPanel'))
check('ui: LoyaltyAnalyticsPanel', ui.includes('LoyaltyAnalyticsPanel'))
check('ui: ReservationAnalyticsPanel', ui.includes('ReservationAnalyticsPanel'))
check('ui: EventPackageAnalyticsPanel', ui.includes('EventPackageAnalyticsPanel'))
check('ui: InventoryHealthPanel', ui.includes('InventoryHealthPanel'))
check('ui: SmokeCraftEngagementPanel', ui.includes('SmokeCraftEngagementPanel'))
check('ui: KPIManagerPanel', ui.includes('KPIManagerPanel'))
check('ui: KPIThresholdPanel', ui.includes('KPIThresholdPanel'))
check('ui: AlertRulePanel', ui.includes('AlertRulePanel'))
check('ui: AlertEventPanel', ui.includes('AlertEventPanel'))
check('ui: ReportSnapshotPanel', ui.includes('ReportSnapshotPanel'))
check('ui: SnapshotLockPanel', ui.includes('SnapshotLockPanel'))
check('ui: ExportRequestPanel', ui.includes('ExportRequestPanel'))
check('ui: ScheduledReportPanel', ui.includes('ScheduledReportPanel'))
check('ui: BIProviderPanel', ui.includes('BIProviderPanel'))
check('ui: EATDecisionLayerPanel', ui.includes('EATDecisionLayerPanel'))
check('ui: EATDecisionReviewPanel', ui.includes('EATDecisionReviewPanel'))
check('ui: OfflineReportQueuePanel', ui.includes('OfflineReportQueuePanel'))
check('ui: ReportsLanguageSelector', ui.includes('ReportsLanguageSelector'))
check('ui: PrivateDataProtectionPanel', ui.includes('PrivateDataProtectionPanel'))
check('ui: FinancialDataProtectionPanel', ui.includes('FinancialDataProtectionPanel'))
check('ui: HonestRevenueStatePanel', ui.includes('HonestRevenueStatePanel'))
check('ui: HonestExportStatePanel', ui.includes('HonestExportStatePanel'))
check('ui: HonestAIStatePanel', ui.includes('HonestAIStatePanel'))
check('ui: HonestEmptyStatePanel', ui.includes('HonestEmptyStatePanel'))
check('ui: Touchscreen header', ui.includes('Touchscreen'))
check('ui: Handheld header', ui.includes('Handheld'))
check('ui: smokecraft-pos360.png ref 1', ui.includes('/smokecraft-pos360.png'))
check('ui: smokecraft-pos360.png ref 2', (ui.match(/smokecraft-pos360\.png/g) || []).length >= 2)
check('ui: no fake populated data', !ui.includes('$12,450') && !ui.includes('$98,000') && !ui.includes('fakeRevenue'))
check('ui: integration not connected language', ui.includes('not connected'))
check('ui: DARK_BG token', ui.includes("'#080604'"))
check('ui: GOLD token', ui.includes("'#c9952c'"))
check('ui: API base /api/pos360/reports', ui.includes('/api/pos360/reports'))
check('ui: export default POS360ReportsAnalyticsDecision', ui.includes('export default function POS360ReportsAnalyticsDecision'))

// ── Safety ──────────────────────────────────────────────────────────────────
check('safety: PII handling language in ui', ui.includes('private data') || ui.includes('Private Data'))
check('safety: financial data handling in ui', ui.includes('financial data') || ui.includes('Financial Data'))
check('safety: contains_secrets false in service', service.includes('contains_secrets'))
check('safety: stores_secrets false in service', service.includes('stores_secrets'))
check('safety: contains_ai_generated_content false in service', service.includes('contains_ai_generated_content'))
check('safety: export_completed false in service', service.includes('export_completed'))
check('safety: delivery_completed false in service', service.includes('delivery_completed'))
check('safety: bi_connected false in service', service.includes('bi_connected'))
check('safety: offline queue honest sync note in ui', ui.includes('offline') || ui.includes('Offline'))
check('safety: canAccessPOS3 in routes', routes.includes('canAccessPOS3'))
check('safety: revenue real-data protection in service', service.includes('real data') || service.includes('Real data'))
check('safety: profit real-data protection', service.includes('profit') || flags.includes('noFakeProfitEnforced'))
check('safety: export not completed protection', service.includes('export_completed') && (service.includes('FALSE') || service.includes('false')))
check('safety: scheduled delivery not sent protection', service.includes('delivery_completed') && (service.includes('FALSE') || service.includes('false')))
check('safety: EAT AI not connected protection', service.includes('contains_ai_generated_content') && service.includes('FALSE'))
check('safety: build-safe exports in service', service.includes('export async function'))

// ── Wiring ──────────────────────────────────────────────────────────────────
check('wiring: index.js imports reports routes', index.includes('pos360ReportsAnalyticsDecisionRoutes'))
check('wiring: index.js mounts /api/pos360/reports', index.includes('/api/pos360/reports'))
check('wiring: App.jsx imports POS360ReportsAnalyticsDecision', app.includes('POS360ReportsAnalyticsDecision'))
check('wiring: App.jsx route reports-analytics-decision', app.includes('reports-analytics-decision'))
check('wiring: package.json verify script', pkg.includes('verify:pos360-reports-analytics-decision'))

console.log(`\nPhase B.13 Verification: ${pass} passed, ${fail} failed`)
if (fail > 0) process.exit(1)
