#!/usr/bin/env node
// Verification: Phase B.16 — POS360 Kitchen, Bar, Humidor Fulfillment, KDS & Production Governance

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');

function read(rel) { return readFileSync(path.join(root, rel), 'utf8'); }

let passed = 0; let failed = 0; const failures = [];
function check(label, condition) { if (condition) { passed++; } else { failed++; failures.push(label); } }

// ── Migration ──────────────────────────────────────────────────────────────
const sql = read('server/db/migrations/046_pos360_fulfillment_kds_order_routing.sql');
check('migration: file exists', sql.length > 100);
check('migration: no DROP TABLE', !sql.includes('DROP TABLE'));
check('migration: CREATE TABLE IF NOT EXISTS', sql.includes('CREATE TABLE IF NOT EXISTS'));
check('migration: pos360_fulfillment_station_profiles', sql.includes('pos360_fulfillment_station_profiles'));
check('migration: pos360_fulfillment_station_capabilities', sql.includes('pos360_fulfillment_station_capabilities'));
check('migration: pos360_item_routing_rules', sql.includes('pos360_item_routing_rules'));
check('migration: pos360_order_production_tickets', sql.includes('pos360_order_production_tickets'));
check('migration: pos360_order_production_ticket_items', sql.includes('pos360_order_production_ticket_items'));
check('migration: pos360_kds_queue_records', sql.includes('pos360_kds_queue_records'));
check('migration: pos360_kds_queue_item_status_history', sql.includes('pos360_kds_queue_item_status_history'));
check('migration: pos360_course_fire_controls', sql.includes('pos360_course_fire_controls'));
check('migration: pos360_station_staff_assignments', sql.includes('pos360_station_staff_assignments'));
check('migration: pos360_production_handoff_records', sql.includes('pos360_production_handoff_records'));
check('migration: pos360_item_unavailable_records', sql.includes('pos360_item_unavailable_records'));
check('migration: pos360_production_manager_overrides', sql.includes('pos360_production_manager_overrides'));
check('migration: pos360_production_refire_records', sql.includes('pos360_production_refire_records'));
check('migration: pos360_production_rush_delay_records', sql.includes('pos360_production_rush_delay_records'));
check('migration: pos360_guest_self_order_handoff_records', sql.includes('pos360_guest_self_order_handoff_records'));
check('migration: pos360_server_order_handoff_records', sql.includes('pos360_server_order_handoff_records'));
check('migration: pos360_humidor_fulfillment_records', sql.includes('pos360_humidor_fulfillment_records'));
check('migration: pos360_bar_fulfillment_records', sql.includes('pos360_bar_fulfillment_records'));
check('migration: pos360_kitchen_fulfillment_records', sql.includes('pos360_kitchen_fulfillment_records'));
check('migration: pos360_external_kds_provider_profiles', sql.includes('pos360_external_kds_provider_profiles'));
check('migration: pos360_production_visibility_insights', sql.includes('pos360_production_visibility_insights'));
check('migration: pos360_production_offline_queue', sql.includes('pos360_production_offline_queue'));
check('migration: pos360_production_audit', sql.includes('pos360_production_audit'));
check('migration: venue_id present', sql.includes('venue_id'));
check('migration: order_id hook', sql.includes('order_id'));
check('migration: order_source', sql.includes('order_source'));
check('migration: ticket_id hook', sql.includes('ticket_id'));
check('migration: ticket_item_id hook', sql.includes('ticket_item_id'));
check('migration: station_id hook', sql.includes('station_id'));
check('migration: staff_profile_id hook', sql.includes('staff_profile_id'));
check('migration: table_id hook', sql.includes('table_id'));
check('migration: section_id hook', sql.includes('section_id'));
check('migration: reservation_id hook', sql.includes('reservation_id'));
check('migration: waitlist_entry_id hook', sql.includes('waitlist_entry_id'));
check('migration: private_event_id hook', sql.includes('private_event_id'));
check('migration: package_selection_id hook', sql.includes('package_selection_id'));
check('migration: payment_record_id hook', sql.includes('payment_record_id'));
check('migration: guest_profile_id hook', sql.includes('guest_profile_id'));
check('migration: customer_id hook', sql.includes('customer_id'));
check('migration: inventory_item_id hook', sql.includes('inventory_item_id'));
check('migration: smokecraft_session_id hook', sql.includes('smokecraft_session_id'));
check('migration: provider_profile_id hook', sql.includes('provider_profile_id'));
check('migration: sync_run_id hook', sql.includes('sync_run_id'));
check('migration: contains_secrets DEFAULT FALSE', sql.includes('contains_secrets') && sql.includes('DEFAULT FALSE'));
check('migration: stores_secrets DEFAULT FALSE', sql.includes('stores_secrets') && sql.includes('DEFAULT FALSE'));
check('migration: exposes_private_data DEFAULT TRUE', sql.includes('exposes_private_data') && sql.includes('DEFAULT TRUE'));
check('migration: exposes_financial_data DEFAULT TRUE', sql.includes('exposes_financial_data') && sql.includes('DEFAULT TRUE'));
check('migration: provider_connected DEFAULT FALSE', sql.includes('provider_connected') && sql.includes('DEFAULT FALSE'));
check('migration: kds_connected DEFAULT FALSE', sql.includes('kds_connected') && sql.includes('DEFAULT FALSE'));
check('migration: printer_connected DEFAULT FALSE', sql.includes('printer_connected') && sql.includes('DEFAULT FALSE'));
check('migration: inventory_deducted DEFAULT FALSE', sql.includes('inventory_deducted') && sql.includes('DEFAULT FALSE'));
check('migration: external_sync_completed DEFAULT FALSE', sql.includes('external_sync_completed') && sql.includes('DEFAULT FALSE'));
check('migration: contains_ai_generated_content DEFAULT FALSE', sql.includes('contains_ai_generated_content') && sql.includes('DEFAULT FALSE'));
check('migration: idempotency_key UNIQUE', sql.includes('idempotency_key') && sql.includes('UNIQUE'));
check('migration: generated_from_real_order DEFAULT FALSE', sql.includes('generated_from_real_order') && sql.includes('DEFAULT FALSE'));

// ── Contracts ──────────────────────────────────────────────────────────────
const contracts = read('server/services/pos360/pos360FulfillmentContracts.js');
check('contracts: file exists', contracts.length > 100);
check('contracts: STATION_TYPES', contracts.includes('STATION_TYPES'));
check('contracts: STATION_STATUSES', contracts.includes('STATION_STATUSES'));
check('contracts: CAPABILITY_GROUPS', contracts.includes('CAPABILITY_GROUPS'));
check('contracts: SUPPORTED_STATUSES', contracts.includes('SUPPORTED_STATUSES'));
check('contracts: ROUTING_RULE_TYPES', contracts.includes('ROUTING_RULE_TYPES'));
check('contracts: ORDER_SOURCES', contracts.includes('ORDER_SOURCES'));
check('contracts: TICKET_STATUSES', contracts.includes('TICKET_STATUSES'));
check('contracts: ITEM_TYPES', contracts.includes('ITEM_TYPES'));
check('contracts: ITEM_STATUSES', contracts.includes('ITEM_STATUSES'));
check('contracts: QUEUE_TYPES', contracts.includes('QUEUE_TYPES'));
check('contracts: QUEUE_STATUSES', contracts.includes('QUEUE_STATUSES'));
check('contracts: QUEUE_PRIORITIES', contracts.includes('QUEUE_PRIORITIES'));
check('contracts: FIRE_STATUSES', contracts.includes('FIRE_STATUSES'));
check('contracts: HANDOFF_TYPES', contracts.includes('HANDOFF_TYPES'));
check('contracts: HANDOFF_STATUSES', contracts.includes('HANDOFF_STATUSES'));
check('contracts: UNAVAILABLE_STATUSES', contracts.includes('UNAVAILABLE_STATUSES'));
check('contracts: OVERRIDE_TYPES', contracts.includes('OVERRIDE_TYPES'));
check('contracts: OVERRIDE_STATUSES', contracts.includes('OVERRIDE_STATUSES'));
check('contracts: FULFILLMENT_STATUSES', contracts.includes('FULFILLMENT_STATUSES'));
check('contracts: EXTERNAL_PROVIDER_STATUSES', contracts.includes('EXTERNAL_PROVIDER_STATUSES'));
check('contracts: VISIBILITY_INSIGHT_TYPES', contracts.includes('VISIBILITY_INSIGHT_TYPES'));
check('contracts: isValidStationType', contracts.includes('isValidStationType'));
check('contracts: isValidStationStatus', contracts.includes('isValidStationStatus'));
check('contracts: isValidCapabilityGroup', contracts.includes('isValidCapabilityGroup'));
check('contracts: isValidSupportedStatus', contracts.includes('isValidSupportedStatus'));
check('contracts: isValidRoutingRuleType', contracts.includes('isValidRoutingRuleType'));
check('contracts: isValidOrderSource', contracts.includes('isValidOrderSource'));
check('contracts: isValidTicketStatus', contracts.includes('isValidTicketStatus'));
check('contracts: isValidItemType', contracts.includes('isValidItemType'));
check('contracts: isValidItemStatus', contracts.includes('isValidItemStatus'));
check('contracts: isValidQueueType', contracts.includes('isValidQueueType'));
check('contracts: isValidQueueStatus', contracts.includes('isValidQueueStatus'));
check('contracts: isValidQueuePriority', contracts.includes('isValidQueuePriority'));
check('contracts: isValidFireStatus', contracts.includes('isValidFireStatus'));
check('contracts: isValidHandoffType', contracts.includes('isValidHandoffType'));
check('contracts: isValidHandoffStatus', contracts.includes('isValidHandoffStatus'));
check('contracts: isValidUnavailableStatus', contracts.includes('isValidUnavailableStatus'));
check('contracts: isValidOverrideType', contracts.includes('isValidOverrideType'));
check('contracts: isValidOverrideStatus', contracts.includes('isValidOverrideStatus'));
check('contracts: isValidFulfillmentStatus', contracts.includes('isValidFulfillmentStatus'));
check('contracts: isValidExternalProviderStatus', contracts.includes('isValidExternalProviderStatus'));
check('contracts: isValidVisibilityInsightType', contracts.includes('isValidVisibilityInsightType'));
check('contracts: humidor in STATION_TYPES', contracts.includes("'humidor'"));
check('contracts: guest_self_order in ORDER_SOURCES', contracts.includes('guest_self_order'));
check('contracts: received_placeholder in TICKET_STATUSES', contracts.includes('received_placeholder'));
check('contracts: voided_external in ITEM_STATUSES', contracts.includes('voided_external'));
check('contracts: pending_manager_approval in OVERRIDE_STATUSES', contracts.includes('pending_manager_approval'));

// ── Feature Flags ──────────────────────────────────────────────────────────
const flags = read('server/config/pos360FulfillmentFeatureFlags.js');
check('flags: file exists', flags.length > 100);
check('flags: DEFAULT_POS360_FULFILLMENT_FLAGS', flags.includes('DEFAULT_POS360_FULFILLMENT_FLAGS'));
check('flags: getFulfillmentFlags', flags.includes('getFulfillmentFlags'));
check('flags: fulfillmentEnabled', flags.includes('fulfillmentEnabled'));
check('flags: stationProfilesEnabled', flags.includes('stationProfilesEnabled'));
check('flags: itemRoutingRulesEnabled', flags.includes('itemRoutingRulesEnabled'));
check('flags: orderProductionTicketsEnabled', flags.includes('orderProductionTicketsEnabled'));
check('flags: kdsQueuesEnabled', flags.includes('kdsQueuesEnabled'));
check('flags: kitchenQueueEnabled', flags.includes('kitchenQueueEnabled'));
check('flags: barQueueEnabled', flags.includes('barQueueEnabled'));
check('flags: humidorQueueEnabled', flags.includes('humidorQueueEnabled'));
check('flags: expoQueueEnabled', flags.includes('expoQueueEnabled'));
check('flags: pickupQueueEnabled', flags.includes('pickupQueueEnabled'));
check('flags: courseFireControlsEnabled', flags.includes('courseFireControlsEnabled'));
check('flags: stationStaffAssignmentsEnabled', flags.includes('stationStaffAssignmentsEnabled'));
check('flags: productionHandoffsEnabled', flags.includes('productionHandoffsEnabled'));
check('flags: itemUnavailableControlsEnabled', flags.includes('itemUnavailableControlsEnabled'));
check('flags: managerOverridesEnabled', flags.includes('managerOverridesEnabled'));
check('flags: guestSelfOrderHandoffEnabled', flags.includes('guestSelfOrderHandoffEnabled'));
check('flags: serverOrderHandoffEnabled', flags.includes('serverOrderHandoffEnabled'));
check('flags: humidorFulfillmentEnabled', flags.includes('humidorFulfillmentEnabled'));
check('flags: barFulfillmentEnabled', flags.includes('barFulfillmentEnabled'));
check('flags: kitchenFulfillmentEnabled', flags.includes('kitchenFulfillmentEnabled'));
check('flags: externalKdsProviderContractsEnabled', flags.includes('externalKdsProviderContractsEnabled'));
check('flags: productionVisibilityInsightsEnabled', flags.includes('productionVisibilityInsightsEnabled'));
check('flags: eatOperationalVisibilityEnabled', flags.includes('eatOperationalVisibilityEnabled'));
check('flags: smokecraftHumidorVisibilityEnabled', flags.includes('smokecraftHumidorVisibilityEnabled'));
check('flags: offlineProductionQueueEnabled', flags.includes('offlineProductionQueueEnabled'));
check('flags: noFakeKdsProviderEnforced', flags.includes('noFakeKdsProviderEnforced'));
check('flags: noFakePrinterProviderEnforced', flags.includes('noFakePrinterProviderEnforced'));
check('flags: noFakeInventoryDeductionEnforced', flags.includes('noFakeInventoryDeductionEnforced'));
check('flags: noFakeOrderCompletionEnforced', flags.includes('noFakeOrderCompletionEnforced'));
check('flags: noFakeEatAiEnforced', flags.includes('noFakeEatAiEnforced'));
check('flags: noSecretsStorageEnforced', flags.includes('noSecretsStorageEnforced'));
check('flags: canAccessPOS3ProtectionRequired', flags.includes('canAccessPOS3ProtectionRequired'));
check('flags: 35+ flags present', (flags.match(/:\s*true/g) || []).length >= 35);

// ── Locales ────────────────────────────────────────────────────────────────
const locales = read('src/locales/pos360Fulfillment.js');
check('locales: file exists', locales.length > 100);
check('locales: en-US', locales.includes("'en-US'"));
check('locales: es-DO', locales.includes("'es-DO'"));
check('locales: es', locales.includes("'es'"));
check('locales: ht', locales.includes("'ht'"));
check('locales: de', locales.includes("'de'"));
check('locales: pt', locales.includes("'pt'"));
check('locales: tFulfillment', locales.includes('tFulfillment'));
check('locales: getSupportedFulfillmentLanguages', locales.includes('getSupportedFulfillmentLanguages'));
check('locales: kdsNotConnected', locales.includes('kdsNotConnected'));
check('locales: printerNotConnected', locales.includes('printerNotConnected'));
check('locales: inventoryNotDeducted', locales.includes('inventoryNotDeducted'));
check('locales: orderNotCompleted', locales.includes('orderNotCompleted'));
check('locales: eatAiNotConnected', locales.includes('eatAiNotConnected'));
check('locales: noSecretsStored', locales.includes('noSecretsStored'));
check('locales: privateDataProtected', locales.includes('privateDataProtected'));
check('locales: financialDataProtected', locales.includes('financialDataProtected'));
check('locales: managerApprovalRequired', locales.includes('managerApprovalRequired'));
check('locales: honestEmptyState', locales.includes('honestEmptyState'));
check('locales: integrationNotConnected', locales.includes('integrationNotConnected'));
check('locales: deviceLine present', locales.includes('Touchscreen'));
check('locales: humidorQueue key', locales.includes('humidorQueue'));
check('locales: kitchenFulfillment key', locales.includes('kitchenFulfillment'));
check('locales: barFulfillment key', locales.includes('barFulfillment'));

// ── Service ────────────────────────────────────────────────────────────────
const svc = read('server/services/pos360/pos360FulfillmentKdsService.js');
check('service: file exists', svc.length > 100);
check('service: JSDoc falls back gracefully', svc.includes('Falls back gracefully'));
check('service: JSDoc never prints connection string', svc.includes('Never prints or logs the database connection string'));
check('service: AREA constant', svc.includes("AREA = 'pos360-fulfillment-kds'"));
check('service: isDbAvailable import', svc.includes('isDbAvailable'));
check('service: connection.js import path', svc.includes("from '../../db/connection.js'"));
check('service: LOCAL fallback', svc.includes('localPreview: true'));
check('service: writeAudit function', svc.includes('writeAudit'));
check('service: writeKdsHistory function', svc.includes('writeKdsHistory'));
check('service: contains_secrets FALSE in audit', svc.includes('contains_secrets: false') || svc.includes('contains_secrets,FALSE') || svc.includes('FALSE,FALSE'));
check('service: stores_secrets FALSE in audit', svc.includes('stores_secrets: false') || svc.includes('stores_secrets,FALSE'));
check('service: createStationProfile', svc.includes('createStationProfile'));
check('service: getStationProfile', svc.includes('getStationProfile'));
check('service: listStationProfiles', svc.includes('listStationProfiles'));
check('service: updateStationStatus', svc.includes('updateStationStatus'));
check('service: createStationCapability', svc.includes('createStationCapability'));
check('service: listStationCapabilities', svc.includes('listStationCapabilities'));
check('service: createItemRoutingRule', svc.includes('createItemRoutingRule'));
check('service: listItemRoutingRules', svc.includes('listItemRoutingRules'));
check('service: updateItemRoutingRule', svc.includes('updateItemRoutingRule'));
check('service: createProductionTicketPlaceholder', svc.includes('createProductionTicketPlaceholder'));
check('service: getProductionTicket', svc.includes('getProductionTicket'));
check('service: listProductionTickets', svc.includes('listProductionTickets'));
check('service: updateProductionTicketStatus', svc.includes('updateProductionTicketStatus'));
check('service: createProductionTicketItem', svc.includes('createProductionTicketItem'));
check('service: listProductionTicketItems', svc.includes('listProductionTicketItems'));
check('service: updateProductionTicketItemStatus', svc.includes('updateProductionTicketItemStatus'));
check('service: createKdsQueueRecord', svc.includes('createKdsQueueRecord'));
check('service: listKdsQueueRecords', svc.includes('listKdsQueueRecords'));
check('service: updateKdsQueueStatus', svc.includes('updateKdsQueueStatus'));
check('service: updateKdsQueuePriority', svc.includes('updateKdsQueuePriority'));
check('service: createCourseFireControl', svc.includes('createCourseFireControl'));
check('service: listCourseFireControls', svc.includes('listCourseFireControls'));
check('service: updateCourseFireStatus', svc.includes('updateCourseFireStatus'));
check('service: createStationStaffAssignment', svc.includes('createStationStaffAssignment'));
check('service: listStationStaffAssignments', svc.includes('listStationStaffAssignments'));
check('service: createProductionHandoff', svc.includes('createProductionHandoff'));
check('service: listProductionHandoffs', svc.includes('listProductionHandoffs'));
check('service: updateProductionHandoffStatus', svc.includes('updateProductionHandoffStatus'));
check('service: createItemUnavailableRecord', svc.includes('createItemUnavailableRecord'));
check('service: listItemUnavailableRecords', svc.includes('listItemUnavailableRecords'));
check('service: createProductionManagerOverride', svc.includes('createProductionManagerOverride'));
check('service: decideProductionManagerOverride', svc.includes('decideProductionManagerOverride'));
check('service: createProductionRefire', svc.includes('createProductionRefire'));
check('service: listProductionRefires', svc.includes('listProductionRefires'));
check('service: createProductionRushDelay', svc.includes('createProductionRushDelay'));
check('service: listProductionRushDelayRecords', svc.includes('listProductionRushDelayRecords'));
check('service: createGuestSelfOrderHandoffPlaceholder', svc.includes('createGuestSelfOrderHandoffPlaceholder'));
check('service: listGuestSelfOrderHandoffs', svc.includes('listGuestSelfOrderHandoffs'));
check('service: createServerOrderHandoffPlaceholder', svc.includes('createServerOrderHandoffPlaceholder'));
check('service: listServerOrderHandoffs', svc.includes('listServerOrderHandoffs'));
check('service: createHumidorFulfillmentRecord', svc.includes('createHumidorFulfillmentRecord'));
check('service: listHumidorFulfillmentRecords', svc.includes('listHumidorFulfillmentRecords'));
check('service: updateHumidorFulfillmentStatus', svc.includes('updateHumidorFulfillmentStatus'));
check('service: createBarFulfillmentRecord', svc.includes('createBarFulfillmentRecord'));
check('service: listBarFulfillmentRecords', svc.includes('listBarFulfillmentRecords'));
check('service: updateBarFulfillmentStatus', svc.includes('updateBarFulfillmentStatus'));
check('service: createKitchenFulfillmentRecord', svc.includes('createKitchenFulfillmentRecord'));
check('service: listKitchenFulfillmentRecords', svc.includes('listKitchenFulfillmentRecords'));
check('service: updateKitchenFulfillmentStatus', svc.includes('updateKitchenFulfillmentStatus'));
check('service: createExternalKdsProviderProfile', svc.includes('createExternalKdsProviderProfile'));
check('service: listExternalKdsProviderProfiles', svc.includes('listExternalKdsProviderProfiles'));
check('service: updateExternalKdsProviderStatus', svc.includes('updateExternalKdsProviderStatus'));
check('service: createProductionVisibilityInsightPlaceholder', svc.includes('createProductionVisibilityInsightPlaceholder'));
check('service: listProductionVisibilityInsights', svc.includes('listProductionVisibilityInsights'));
check('service: getProductionOperationsSummary', svc.includes('getProductionOperationsSummary'));
check('service: queueOfflineProductionAction', svc.includes('queueOfflineProductionAction'));
check('service: listOfflineProductionQueue', svc.includes('listOfflineProductionQueue'));
check('service: markOfflineProductionActionSynced', svc.includes('markOfflineProductionActionSynced'));
check('service: idempotency duplicate check', svc.includes('duplicate: true'));
check('service: no fake kds_connected true', !svc.includes('kds_connected: true'));
check('service: no fake printer_connected true', !svc.includes('printer_connected: true'));
check('service: no fake inventory deduction', !svc.includes('inventory_deducted: true'));
check('service: no fake external_sync_completed true', !svc.includes('external_sync_completed: true'));
check('service: no fake generated_from_real_order true', !svc.includes('generated_from_real_order: true'));
check('service: no fake provider_connected true', !svc.includes('provider_connected: true'));
check('service: manager approval required for override', svc.includes("pending_manager_approval"));
check('service: honest empty state', svc.includes('localPreview'));

// ── Controller ─────────────────────────────────────────────────────────────
const ctrl = read('server/controllers/pos360FulfillmentKdsController.js');
check('controller: file exists', ctrl.length > 100);
check('controller: ok500 pattern', ctrl.includes('ok500'));
check('controller: vid pattern', ctrl.includes('vid(req)'));
check('controller: actor pattern', ctrl.includes('actor(req)'));
check('controller: ikey pattern', ctrl.includes('ikey(req)'));
check('controller: createStationProfile handler', ctrl.includes('createStationProfile'));
check('controller: updateStationStatus handler', ctrl.includes('updateStationStatus'));
check('controller: createProductionTicketPlaceholder handler', ctrl.includes('createProductionTicketPlaceholder'));
check('controller: createKdsQueueRecord handler', ctrl.includes('createKdsQueueRecord'));
check('controller: decideProductionManagerOverride handler', ctrl.includes('decideProductionManagerOverride'));
check('controller: createHumidorFulfillmentRecord handler', ctrl.includes('createHumidorFulfillmentRecord'));
check('controller: createBarFulfillmentRecord handler', ctrl.includes('createBarFulfillmentRecord'));
check('controller: createKitchenFulfillmentRecord handler', ctrl.includes('createKitchenFulfillmentRecord'));
check('controller: createExternalKdsProviderProfile handler', ctrl.includes('createExternalKdsProviderProfile'));
check('controller: getProductionOperationsSummary handler', ctrl.includes('getProductionOperationsSummary'));
check('controller: queueOfflineProductionAction handler', ctrl.includes('queueOfflineProductionAction'));

// ── Routes ─────────────────────────────────────────────────────────────────
const routes = read('server/routes/pos360FulfillmentKdsRoutes.js');
check('routes: file exists', routes.length > 100);
check('routes: canAccessPOS3 import', routes.includes('canAccessPOS3'));
check('routes: POST /stations with canAccessPOS3', routes.includes("router.post('/stations', canAccessPOS3"));
check('routes: GET /stations', routes.includes("router.get('/stations'"));
check('routes: PATCH /stations status with canAccessPOS3', routes.includes("canAccessPOS3, c.updateStationStatus"));
check('routes: POST routing-rules with canAccessPOS3', routes.includes("router.post('/routing-rules', canAccessPOS3"));
check('routes: POST /tickets with canAccessPOS3', routes.includes("router.post('/tickets', canAccessPOS3"));
check('routes: GET /tickets', routes.includes("router.get('/tickets'"));
check('routes: PATCH ticket status with canAccessPOS3', routes.includes("canAccessPOS3, c.updateProductionTicketStatus"));
check('routes: POST kds-queue with canAccessPOS3', routes.includes("router.post('/kds-queue', canAccessPOS3"));
check('routes: PATCH kds-queue status with canAccessPOS3', routes.includes("canAccessPOS3, c.updateKdsQueueStatus"));
check('routes: POST course-fire with canAccessPOS3', routes.includes("canAccessPOS3, c.createCourseFireControl"));
check('routes: POST station-assignments with canAccessPOS3', routes.includes("router.post('/station-assignments', canAccessPOS3"));
check('routes: POST handoffs with canAccessPOS3', routes.includes("router.post('/handoffs', canAccessPOS3"));
check('routes: POST item-unavailable with canAccessPOS3', routes.includes("router.post('/item-unavailable', canAccessPOS3"));
check('routes: POST manager-overrides with canAccessPOS3', routes.includes("router.post('/manager-overrides', canAccessPOS3"));
check('routes: POST override decision with canAccessPOS3', routes.includes("canAccessPOS3, c.decideProductionManagerOverride"));
check('routes: POST refires with canAccessPOS3', routes.includes("router.post('/refires', canAccessPOS3"));
check('routes: POST rush-delay with canAccessPOS3', routes.includes("router.post('/rush-delay', canAccessPOS3"));
check('routes: POST guest-self-order-handoffs with canAccessPOS3', routes.includes("router.post('/guest-self-order-handoffs', canAccessPOS3"));
check('routes: POST server-order-handoffs with canAccessPOS3', routes.includes("router.post('/server-order-handoffs', canAccessPOS3"));
check('routes: POST /humidor with canAccessPOS3', routes.includes("router.post('/humidor', canAccessPOS3"));
check('routes: POST /bar with canAccessPOS3', routes.includes("router.post('/bar', canAccessPOS3"));
check('routes: POST /kitchen with canAccessPOS3', routes.includes("router.post('/kitchen', canAccessPOS3"));
check('routes: POST external-kds-providers with canAccessPOS3', routes.includes("router.post('/external-kds-providers', canAccessPOS3"));
check('routes: POST visibility-insights with canAccessPOS3', routes.includes("router.post('/visibility-insights', canAccessPOS3"));
check('routes: GET /operations-summary', routes.includes("router.get('/operations-summary'"));
check('routes: export default router', routes.includes('export default router'));

// ── UI ─────────────────────────────────────────────────────────────────────
const ui = read('src/pages/pos360/POS360FulfillmentKds.jsx');
check('ui: file exists', ui.length > 100);
check('ui: smokecraft-pos360.png (1)', ui.includes('/smokecraft-pos360.png'));
check('ui: smokecraft-pos360.png (2)', (ui.match(/smokecraft-pos360\.png/g) || []).length >= 2);
check('ui: Touchscreen · Handheld · Tablet · Desktop', ui.includes('Touchscreen · Handheld · Tablet · Desktop'));
check('ui: DARK_BG token', ui.includes("'#080604'"));
check('ui: GOLD token', ui.includes("'#c9952c'"));
check('ui: DARK_CARD token', ui.includes("'#13110d'"));
check('ui: FulfillmentDashboard', ui.includes('FulfillmentDashboard'));
check('ui: StationProfilesPanel', ui.includes('StationProfilesPanel'));
check('ui: StationCapabilitiesPanel', ui.includes('StationCapabilitiesPanel'));
check('ui: ItemRoutingRulesPanel', ui.includes('ItemRoutingRulesPanel'));
check('ui: ProductionTicketsPanel', ui.includes('ProductionTicketsPanel'));
check('ui: ProductionTicketItemsPanel', ui.includes('ProductionTicketItemsPanel'));
check('ui: KitchenQueuePanel', ui.includes('KitchenQueuePanel'));
check('ui: BarQueuePanel', ui.includes('BarQueuePanel'));
check('ui: HumidorQueuePanel', ui.includes('HumidorQueuePanel'));
check('ui: ExpoQueuePanel', ui.includes('ExpoQueuePanel'));
check('ui: PickupQueuePanel', ui.includes('PickupQueuePanel'));
check('ui: KDSQueuePanel', ui.includes('KDSQueuePanel'));
check('ui: CourseFireControlPanel', ui.includes('CourseFireControlPanel'));
check('ui: StationStaffAssignmentPanel', ui.includes('StationStaffAssignmentPanel'));
check('ui: ProductionHandoffPanel', ui.includes('ProductionHandoffPanel'));
check('ui: ItemUnavailablePanel', ui.includes('ItemUnavailablePanel'));
check('ui: ManagerOverridePanel', ui.includes('ManagerOverridePanel'));
check('ui: RefirePanel', ui.includes('RefirePanel'));
check('ui: RushDelayPanel', ui.includes('RushDelayPanel'));
check('ui: GuestSelfOrderHandoffPanel', ui.includes('GuestSelfOrderHandoffPanel'));
check('ui: ServerOrderHandoffPanel', ui.includes('ServerOrderHandoffPanel'));
check('ui: HumidorFulfillmentPanel', ui.includes('HumidorFulfillmentPanel'));
check('ui: BarFulfillmentPanel', ui.includes('BarFulfillmentPanel'));
check('ui: KitchenFulfillmentPanel', ui.includes('KitchenFulfillmentPanel'));
check('ui: ExternalKdsProviderPanel', ui.includes('ExternalKdsProviderPanel'));
check('ui: ProductionVisibilityPanel', ui.includes('ProductionVisibilityPanel'));
check('ui: EATOperationalVisibilityPanel', ui.includes('EATOperationalVisibilityPanel'));
check('ui: SmokeCraftHumidorVisibilityPanel', ui.includes('SmokeCraftHumidorVisibilityPanel'));
check('ui: OfflineProductionQueuePanel', ui.includes('OfflineProductionQueuePanel'));
check('ui: FulfillmentLanguageSelector', ui.includes('FulfillmentLanguageSelector'));
check('ui: PrivateDataProtectionPanel', ui.includes('PrivateDataProtectionPanel'));
check('ui: FinancialDataProtectionPanel', ui.includes('FinancialDataProtectionPanel'));
check('ui: NoSecretsStoredPanel', ui.includes('NoSecretsStoredPanel'));
check('ui: HonestKdsStatePanel', ui.includes('HonestKdsStatePanel'));
check('ui: HonestPrinterStatePanel', ui.includes('HonestPrinterStatePanel'));
check('ui: HonestInventoryStatePanel', ui.includes('HonestInventoryStatePanel'));
check('ui: HonestOrderStatePanel', ui.includes('HonestOrderStatePanel'));
check('ui: HonestAIStatePanel', ui.includes('HonestAIStatePanel'));
check('ui: HonestEmptyStatePanel', ui.includes('HonestEmptyStatePanel'));
check('ui: kds_connected: false badge', ui.includes('kds_connected: false'));
check('ui: printer_connected: false badge', ui.includes('printer_connected: false'));
check('ui: inventory_deducted: false badge', ui.includes('inventory_deducted: false'));
check('ui: generated_from_real_order: false badge', ui.includes('generated_from_real_order: false'));
check('ui: external_sync_completed: false badge', ui.includes('external_sync_completed: false'));
check('ui: contains_ai_generated_content: false badge', ui.includes('contains_ai_generated_content: false'));
check('ui: provider_connected: false badge', ui.includes('provider_connected: false'));
check('ui: stores_secrets: false badge', ui.includes('stores_secrets: false'));
check('ui: SmokeCraft progression locks note', ui.includes('SmokeCraft') && ui.includes('VISIT_STRUCTURE'));
check('ui: no fake order data', ui.includes('No fake') || ui.includes('no fake') || ui.includes('remains FALSE'));
check('ui: integration not connected language', ui.includes('not connected'));
check('ui: PII handling mention', ui.includes('private data') || ui.includes('Private data'));
check('ui: financial data mention', ui.includes('financial data') || ui.includes('Financial data'));

// ── Server wiring ──────────────────────────────────────────────────────────
const idx = read('server/index.js');
check('server index: import pos360FulfillmentKdsRoutes', idx.includes('pos360FulfillmentKdsRoutes'));
check('server index: app.use /api/pos360/fulfillment', idx.includes('/api/pos360/fulfillment'));
check('server index: B.15 integrations route still present', idx.includes('/api/pos360/integrations'));
check('server index: B.14 settings route still present', idx.includes('/api/pos360/settings'));
check('server index: B.13 reports route still present', idx.includes('/api/pos360/reports'));

// ── App.jsx wiring ─────────────────────────────────────────────────────────
const app = read('src/App.jsx');
check('app: import POS360FulfillmentKds', app.includes('POS360FulfillmentKds'));
check('app: Route path="fulfillment-kds"', app.includes('fulfillment-kds'));
check('app: B.15 external-integrations route still present', app.includes('external-integrations'));
check('app: B.14 settings-venue-admin route still present', app.includes('settings-venue-admin'));

// ── package.json ───────────────────────────────────────────────────────────
const pkg = read('package.json');
check('package.json: verify:pos360-fulfillment-kds script', pkg.includes('verify:pos360-fulfillment-kds'));
check('package.json: prior verify scripts still present', pkg.includes('verify:pos360-external-integrations'));

// ── Security invariants ────────────────────────────────────────────────────
check('security: no fake kds_connected=true in service', !svc.includes('kds_connected: true'));
check('security: no fake printer_connected=true in service', !svc.includes('printer_connected: true'));
check('security: no fake inventory_deducted=true in service', !svc.includes('inventory_deducted: true'));
check('security: no fake external_sync_completed=true', !svc.includes('external_sync_completed: true'));
check('security: no fake generated_from_real_order=true', !svc.includes('generated_from_real_order: true'));
check('security: no fake contains_ai_generated_content=true', !svc.includes('contains_ai_generated_content: true'));
check('security: canAccessPOS3 on all write routes', routes.includes('canAccessPOS3'));
check('security: no secrets storage in service', !svc.includes('stores_secrets: true'));
check('security: manager approval not bypassed', svc.includes('pending_manager_approval') && !svc.includes('approved_bypass'));
check('security: no DATABASE_URL logging', !svc.includes('console.log') || !svc.includes('DATABASE_URL'));

// ── Summary ────────────────────────────────────────────────────────────────
const total = passed + failed;
console.log(`\nPhase B.16 — POS360 Fulfillment KDS & Production Governance`);
console.log(`Checks: ${total} | Passed: ${passed} | Failed: ${failed}`);

if (failures.length > 0) {
  console.log('\nFAILED CHECKS:');
  failures.forEach(f => console.log(`  ✗ ${f}`));
  process.exit(1);
} else {
  console.log('\n✓ All checks passed — Phase B.16 verification PASS');
  process.exit(0);
}
