import { readFileSync } from 'fs'
import { resolve } from 'path'

const root = resolve(process.cwd())
const read = p => readFileSync(resolve(root, p), 'utf8')

let pass = 0
let fail = 0

function check(label, condition) {
  if (condition) { pass++; } else { fail++; console.error(`FAIL: ${label}`) }
}

const sql = read('server/db/migrations/042_pos360_staff_roles_labor_governance.sql')
const contracts = read('server/services/pos360/pos360StaffContracts.js')
const flags = read('server/config/pos360StaffFeatureFlags.js')
const locales = read('src/locales/pos360Staff.js')
const service = read('server/services/pos360/pos360StaffLaborGovernanceService.js')
const controller = read('server/controllers/pos360StaffLaborGovernanceController.js')
const routes = read('server/routes/pos360StaffLaborGovernanceRoutes.js')
const ui = read('src/pages/pos360/POS360StaffLaborGovernance.jsx')
const index = read('server/index.js')
const app = read('src/App.jsx')
const pkg = read('package.json')

// Migration: tables exist
check('migration: pos360_staff_profiles', sql.includes('pos360_staff_profiles'))
check('migration: pos360_staff_roles', sql.includes('pos360_staff_roles'))
check('migration: pos360_staff_role_templates', sql.includes('pos360_staff_role_templates'))
check('migration: pos360_staff_permissions', sql.includes('pos360_staff_permissions'))
check('migration: pos360_staff_role_permissions', sql.includes('pos360_staff_role_permissions'))
check('migration: pos360_staff_permission_overrides', sql.includes('pos360_staff_permission_overrides'))
check('migration: pos360_staff_assignments', sql.includes('pos360_staff_assignments'))
check('migration: pos360_staff_schedule_templates', sql.includes('pos360_staff_schedule_templates'))
check('migration: pos360_staff_scheduled_shifts', sql.includes('pos360_staff_scheduled_shifts'))
check('migration: pos360_staff_shift_status_history', sql.includes('pos360_staff_shift_status_history'))
check('migration: pos360_staff_availability', sql.includes('pos360_staff_availability'))
check('migration: pos360_staff_time_off_requests', sql.includes('pos360_staff_time_off_requests'))
check('migration: pos360_staff_time_clock_punches', sql.includes('pos360_staff_time_clock_punches'))
check('migration: pos360_staff_time_clock_corrections', sql.includes('pos360_staff_time_clock_corrections'))
check('migration: pos360_staff_break_records', sql.includes('pos360_staff_break_records'))
check('migration: pos360_staff_labor_summaries', sql.includes('pos360_staff_labor_summaries'))
check('migration: pos360_manager_governance_rules', sql.includes('pos360_manager_governance_rules'))
check('migration: pos360_manager_approval_requests', sql.includes('pos360_manager_approval_requests'))
check('migration: pos360_staff_risk_flags', sql.includes('pos360_staff_risk_flags'))
check('migration: pos360_staff_labor_insights', sql.includes('pos360_staff_labor_insights'))
check('migration: pos360_staff_payroll_provider_profiles', sql.includes('pos360_staff_payroll_provider_profiles'))
check('migration: pos360_staff_offline_queue', sql.includes('pos360_staff_offline_queue'))
check('migration: pos360_staff_audit', sql.includes('pos360_staff_audit'))

// Migration: CREATE TABLE IF NOT EXISTS pattern
check('migration: IF NOT EXISTS on staff_profiles', sql.includes('CREATE TABLE IF NOT EXISTS pos360_staff_profiles'))
check('migration: IF NOT EXISTS on scheduled_shifts', sql.includes('CREATE TABLE IF NOT EXISTS pos360_staff_scheduled_shifts'))
check('migration: IF NOT EXISTS on labor_summaries', sql.includes('CREATE TABLE IF NOT EXISTS pos360_staff_labor_summaries'))
check('migration: IF NOT EXISTS on audit', sql.includes('CREATE TABLE IF NOT EXISTS pos360_staff_audit'))

// Migration: key columns
check('migration: staff_profiles.staff_user_id', sql.includes('staff_user_id'))
check('migration: staff_profiles.display_name', sql.includes('display_name'))
check('migration: staff_profiles.staff_code', sql.includes('staff_code'))
check('migration: staff_profiles.preferred_language', sql.includes('preferred_language'))
check('migration: staff_profiles.exposes_private_data', sql.includes('exposes_private_data') && sql.includes('DEFAULT TRUE'))
check('migration: staff_roles.role_type', sql.includes('role_type'))
check('migration: staff_roles.is_manager_role', sql.includes('is_manager_role'))
check('migration: staff_permissions.permission_key', sql.includes('permission_key'))
check('migration: staff_permissions.permission_group', sql.includes('permission_group'))
check('migration: staff_permissions.requires_manager_role', sql.includes('requires_manager_role'))
check('migration: staff_permissions.financial_permission', sql.includes('financial_permission'))
check('migration: staff_permission_overrides.override_type', sql.includes('override_type'))
check('migration: staff_assignments.assignment_type', sql.includes('assignment_type'))
check('migration: staff_assignments.assignment_status', sql.includes('assignment_status'))
check('migration: scheduled_shifts.shift_date', sql.includes('shift_date'))
check('migration: scheduled_shifts.shift_status', sql.includes('shift_status'))
check('migration: scheduled_shifts.publish_status', sql.includes('publish_status'))
check('migration: availability.day_of_week', sql.includes('day_of_week'))
check('migration: availability.preference_level', sql.includes('preference_level'))
check('migration: time_off.request_type', sql.includes('request_type'))
check('migration: time_off.request_status', sql.includes('request_status'))
check('migration: time_clock_punches.punch_type', sql.includes('punch_type'))
check('migration: time_clock_punches.punch_source', sql.includes('punch_source'))
check('migration: time_clock_punches.punch_status', sql.includes('punch_status'))
check('migration: time_clock_punches.processed_externally', sql.includes('processed_externally') && sql.includes('DEFAULT FALSE'))
check('migration: time_clock_corrections.correction_type', sql.includes('correction_type'))
check('migration: time_clock_corrections.manager_approval_required', sql.includes('manager_approval_required'))
check('migration: break_records.break_type', sql.includes('break_type'))
check('migration: labor_summaries.scheduled_minutes', sql.includes('scheduled_minutes'))
check('migration: labor_summaries.actual_minutes', sql.includes('actual_minutes'))
check('migration: labor_summaries.payroll_connected', sql.includes('payroll_connected') && sql.includes('DEFAULT FALSE'))
check('migration: labor_summaries.exposes_financial_data', sql.includes('exposes_financial_data') && sql.includes('DEFAULT TRUE'))
check('migration: governance_rules.protected_action', sql.includes('protected_action'))
check('migration: governance_rules.requires_manager_approval', sql.includes('requires_manager_approval'))
check('migration: approval_requests.approval_status', sql.includes('approval_status'))
check('migration: approval_requests.before_snapshot', sql.includes('before_snapshot'))
check('migration: approval_requests.exposes_financial_data DEFAULT FALSE', sql.includes('exposes_financial_data') && sql.includes('DEFAULT FALSE'))
check('migration: staff_risk_flags.risk_type', sql.includes('risk_type'))
check('migration: staff_risk_flags.risk_status', sql.includes('risk_status'))
check('migration: labor_insights.contains_ai_generated_content', sql.includes('contains_ai_generated_content') && sql.includes('DEFAULT FALSE'))
check('migration: labor_insights.honest_state', sql.includes('honest_state'))
check('migration: payroll_provider_profiles.provider_name', sql.includes('provider_name'))
check('migration: payroll_provider_profiles.stores_secrets DEFAULT FALSE', sql.includes('stores_secrets') && sql.includes('DEFAULT FALSE'))
check('migration: offline_queue.sync_status', sql.includes('sync_status'))
check('migration: audit.contains_secrets DEFAULT FALSE', sql.includes('contains_secrets') && sql.includes('DEFAULT FALSE'))
check('migration: audit.exposes_private_data', sql.includes('exposes_private_data'))
check('migration: idempotency_key on staff_profiles', sql.includes('idempotency_key'))

// Contracts
check('contracts: ROLE_TYPES', contracts.includes('ROLE_TYPES'))
check('contracts: owner role', contracts.includes("'owner'"))
check('contracts: general_manager role', contracts.includes("'general_manager'"))
check('contracts: manager role', contracts.includes("'manager'"))
check('contracts: host role', contracts.includes("'host'"))
check('contracts: server role', contracts.includes("'server'"))
check('contracts: bartender role', contracts.includes("'bartender'"))
check('contracts: humidor_specialist role', contracts.includes("'humidor_specialist'"))
check('contracts: custom role', contracts.includes("'custom'"))
check('contracts: PERMISSION_GROUPS', contracts.includes('PERMISSION_GROUPS'))
check('contracts: payments permission group', contracts.includes("'payments'"))
check('contracts: staff permission group', contracts.includes("'staff'"))
check('contracts: audit permission group', contracts.includes("'audit'"))
check('contracts: PROTECTED_MANAGER_ACTIONS', contracts.includes('PROTECTED_MANAGER_ACTIONS'))
check('contracts: refund_request action', contracts.includes("'refund_request'"))
check('contracts: void_request action', contracts.includes("'void_request'"))
check('contracts: tip_adjustment action', contracts.includes("'tip_adjustment'"))
check('contracts: time_clock_correction action', contracts.includes("'time_clock_correction'"))
check('contracts: schedule_publish action', contracts.includes("'schedule_publish'"))
check('contracts: payroll_export_placeholder action', contracts.includes("'payroll_export_placeholder'"))
check('contracts: ASSIGNMENT_TYPES', contracts.includes('ASSIGNMENT_TYPES'))
check('contracts: SHIFT_STATUSES', contracts.includes('SHIFT_STATUSES'))
check('contracts: PUBLISH_STATUSES', contracts.includes('PUBLISH_STATUSES'))
check('contracts: isValidRoleType', contracts.includes('isValidRoleType'))
check('contracts: isValidPermissionGroup', contracts.includes('isValidPermissionGroup'))
check('contracts: isValidAssignmentType', contracts.includes('isValidAssignmentType'))
check('contracts: isValidShiftStatus', contracts.includes('isValidShiftStatus'))

// Feature flags
check('flags: DEFAULT_POS360_STAFF_FLAGS', flags.includes('DEFAULT_POS360_STAFF_FLAGS'))
check('flags: staffManagementEnabled', flags.includes('staffManagementEnabled'))
check('flags: noFakePayrollEnforced', flags.includes('noFakePayrollEnforced'))
check('flags: noFakeNotificationsEnforced', flags.includes('noFakeNotificationsEnforced'))
check('flags: noSecretsStorageEnforced', flags.includes('noSecretsStorageEnforced'))
check('flags: getStaffFlags export', flags.includes('getStaffFlags'))
check('flags: spread DEFAULT_POS360_STAFF_FLAGS', flags.includes('...DEFAULT_POS360_STAFF_FLAGS'))

// Locales
check('locales: payroll_not_connected', locales.includes('payroll_not_connected'))
check('locales: no_payroll_processed', locales.includes('no_payroll_processed'))
check('locales: labor_cost_placeholder', locales.includes('labor_cost_placeholder'))
check('locales: schedule_notification_not_sent', locales.includes('schedule_notification_not_sent'))
check('locales: staff_pii_protected', locales.includes('staff_pii_protected'))
check('locales: eat_labor_insights_not_connected', locales.includes('eat_labor_insights_not_connected'))
check('locales: offline_queue_note', locales.includes('offline_queue_note'))
check('locales: tStaff export', locales.includes('tStaff'))
check('locales: getSupportedStaffLanguages export', locales.includes('getSupportedStaffLanguages'))
check('locales: en-US', locales.includes("'en-US'"))
check('locales: es-DO', locales.includes("'es-DO'"))
check('locales: ht', locales.includes("'ht'"))
check('locales: de', locales.includes("'de'"))
check('locales: pt', locales.includes("'pt'"))

// Service
check('service: opening JSDoc falls back gracefully', service.includes('Falls back gracefully when no database connection is configured'))
check('service: never prints db connection string', service.includes('Never prints or logs the database connection string'))
check('service: isDbAvailable import', service.includes('isDbAvailable'))
check('service: connection.js import', service.includes("from '../../db/connection.js'"))
check('service: AREA constant', service.includes("AREA = 'pos360-staff-labor-governance'"))
check('service: localPreview true', service.includes('localPreview: true'))
check('service: database_not_configured error', service.includes("'database_not_configured'"))
check('service: auditRecord helper', service.includes('auditRecord'))
check('service: contains_secrets: false', service.includes('contains_secrets') && (service.includes('false') || service.includes('FALSE')))
check('service: createStaffProfile', service.includes('createStaffProfile'))
check('service: getStaffProfile', service.includes('getStaffProfile'))
check('service: listStaffProfiles', service.includes('listStaffProfiles'))
check('service: updateStaffProfile', service.includes('updateStaffProfile'))
check('service: deactivateStaffProfile', service.includes('deactivateStaffProfile'))
check('service: createStaffRole', service.includes('createStaffRole'))
check('service: listStaffRoles', service.includes('listStaffRoles'))
check('service: updateStaffRole', service.includes('updateStaffRole'))
check('service: listRoleTemplates', service.includes('listRoleTemplates'))
check('service: seedVenueRoleTemplatesPlaceholder', service.includes('seedVenueRoleTemplatesPlaceholder'))
check('service: listStaffPermissions', service.includes('listStaffPermissions'))
check('service: grantRolePermission', service.includes('grantRolePermission'))
check('service: revokeRolePermission', service.includes('revokeRolePermission'))
check('service: createPermissionOverride', service.includes('createPermissionOverride'))
check('service: decidePermissionOverride', service.includes('decidePermissionOverride'))
check('service: evaluateStaffPermission', service.includes('evaluateStaffPermission'))
check('service: createStaffAssignment', service.includes('createStaffAssignment'))
check('service: listStaffAssignments', service.includes('listStaffAssignments'))
check('service: updateStaffAssignmentStatus', service.includes('updateStaffAssignmentStatus'))
check('service: transferStaffAssignment', service.includes('transferStaffAssignment'))
check('service: createScheduleTemplate', service.includes('createScheduleTemplate'))
check('service: listScheduleTemplates', service.includes('listScheduleTemplates'))
check('service: createScheduledShift', service.includes('createScheduledShift'))
check('service: listScheduledShifts', service.includes('listScheduledShifts'))
check('service: updateShiftStatus', service.includes('updateShiftStatus'))
check('service: publishSchedulePlaceholder', service.includes('publishSchedulePlaceholder'))
check('service: schedule notification not sent honest note', service.includes('Schedule notification has not been sent'))
check('service: createStaffAvailability', service.includes('createStaffAvailability'))
check('service: listStaffAvailability', service.includes('listStaffAvailability'))
check('service: createTimeOffRequest', service.includes('createTimeOffRequest'))
check('service: listTimeOffRequests', service.includes('listTimeOffRequests'))
check('service: decideTimeOffRequest', service.includes('decideTimeOffRequest'))
check('service: createTimeClockPunch', service.includes('createTimeClockPunch'))
check('service: listTimeClockPunches', service.includes('listTimeClockPunches'))
check('service: createTimeClockCorrection', service.includes('createTimeClockCorrection'))
check('service: decideTimeClockCorrection', service.includes('decideTimeClockCorrection'))
check('service: manager approval block in createTimeClockCorrection', service.includes('manager_approval_required') || service.includes('managerApprovalRequired'))
check('service: createBreakRecord', service.includes('createBreakRecord'))
check('service: listBreakRecords', service.includes('listBreakRecords'))
check('service: createLaborSummaryPlaceholder', service.includes('createLaborSummaryPlaceholder'))
check('service: listLaborSummaries', service.includes('listLaborSummaries'))
check('service: lockLaborSummary', service.includes('lockLaborSummary'))
check('service: labor cost placeholder honest note', service.includes('Labor cost is a placeholder only'))
check('service: no payroll processed honest note', service.includes('No payroll has been processed'))
check('service: createManagerGovernanceRule', service.includes('createManagerGovernanceRule'))
check('service: listManagerGovernanceRules', service.includes('listManagerGovernanceRules'))
check('service: createManagerApprovalRequest', service.includes('createManagerApprovalRequest'))
check('service: listManagerApprovalRequests', service.includes('listManagerApprovalRequests'))
check('service: decideManagerApprovalRequest', service.includes('decideManagerApprovalRequest'))
check('service: createStaffRiskFlag', service.includes('createStaffRiskFlag'))
check('service: listStaffRiskFlags', service.includes('listStaffRiskFlags'))
check('service: reviewStaffRiskFlag', service.includes('reviewStaffRiskFlag'))
check('service: createLaborInsightPlaceholder', service.includes('createLaborInsightPlaceholder'))
check('service: listLaborInsights', service.includes('listLaborInsights'))
check('service: getLaborIntelligenceSummary', service.includes('getLaborIntelligenceSummary'))
check('service: EAT not connected in labor insight', service.includes('E.A.T.') || service.includes('eat') || service.includes('EAT'))
check('service: createPayrollProviderProfile', service.includes('createPayrollProviderProfile'))
check('service: listPayrollProviderProfiles', service.includes('listPayrollProviderProfiles'))
check('service: updatePayrollProviderStatus', service.includes('updatePayrollProviderStatus'))
check('service: payroll not connected honest note', service.includes('Payroll provider is not connected'))
check('service: queueOfflineStaffAction', service.includes('queueOfflineStaffAction'))
check('service: listOfflineStaffQueue', service.includes('listOfflineStaffQueue'))
check('service: markOfflineStaffActionSynced', service.includes('markOfflineStaffActionSynced'))

// Controller
check('controller: ok500 pattern', controller.includes('ok500'))
check('controller: vid pattern', controller.includes('vid(req)'))
check('controller: actor pattern', controller.includes('actor(req)'))
check('controller: tid pattern', controller.includes('tid(req)'))
check('controller: createStaffProfile', controller.includes('createStaffProfile'))
check('controller: getStaffProfile', controller.includes('getStaffProfile'))
check('controller: listStaffProfiles', controller.includes('listStaffProfiles'))
check('controller: updateStaffProfile', controller.includes('updateStaffProfile'))
check('controller: deactivateStaffProfile', controller.includes('deactivateStaffProfile'))
check('controller: createStaffRole', controller.includes('createStaffRole'))
check('controller: listRoleTemplates', controller.includes('listRoleTemplates'))
check('controller: grantRolePermission', controller.includes('grantRolePermission'))
check('controller: revokeRolePermission', controller.includes('revokeRolePermission'))
check('controller: createPermissionOverride', controller.includes('createPermissionOverride'))
check('controller: evaluateStaffPermission', controller.includes('evaluateStaffPermission'))
check('controller: createStaffAssignment', controller.includes('createStaffAssignment'))
check('controller: transferStaffAssignment', controller.includes('transferStaffAssignment'))
check('controller: createScheduledShift', controller.includes('createScheduledShift'))
check('controller: publishSchedulePlaceholder', controller.includes('publishSchedulePlaceholder'))
check('controller: createTimeOffRequest', controller.includes('createTimeOffRequest'))
check('controller: decideTimeOffRequest', controller.includes('decideTimeOffRequest'))
check('controller: createTimeClockPunch', controller.includes('createTimeClockPunch'))
check('controller: createTimeClockCorrection', controller.includes('createTimeClockCorrection'))
check('controller: decideTimeClockCorrection', controller.includes('decideTimeClockCorrection'))
check('controller: createLaborSummaryPlaceholder', controller.includes('createLaborSummaryPlaceholder'))
check('controller: lockLaborSummary', controller.includes('lockLaborSummary'))
check('controller: createManagerGovernanceRule', controller.includes('createManagerGovernanceRule'))
check('controller: decideManagerApprovalRequest', controller.includes('decideManagerApprovalRequest'))
check('controller: createStaffRiskFlag', controller.includes('createStaffRiskFlag'))
check('controller: getLaborIntelligenceSummary', controller.includes('getLaborIntelligenceSummary'))
check('controller: createPayrollProviderProfile', controller.includes('createPayrollProviderProfile'))
check('controller: queueOfflineStaffAction', controller.includes('queueOfflineStaffAction'))
check('controller: markOfflineStaffActionSynced', controller.includes('markOfflineStaffActionSynced'))

// Routes
check('routes: canAccessPOS3 import', routes.includes('canAccessPOS3'))
check('routes: GET /profiles', routes.includes("get('/profiles'") || routes.includes('get(\'/profiles\''))
check('routes: POST /profiles with canAccessPOS3', routes.includes('canAccessPOS3') && routes.includes('createStaffProfile'))
check('routes: /roles', routes.includes('/roles'))
check('routes: /permissions', routes.includes('/permissions'))
check('routes: /assignments', routes.includes('/assignments'))
check('routes: /shifts', routes.includes('/shifts'))
check('routes: /shifts/publish', routes.includes('/shifts/publish'))
check('routes: /availability', routes.includes('/availability'))
check('routes: /time-off', routes.includes('/time-off'))
check('routes: /time-clock', routes.includes('/time-clock'))
check('routes: /breaks', routes.includes('/breaks'))
check('routes: /labor-summaries', routes.includes('/labor-summaries'))
check('routes: /governance-rules', routes.includes('/governance-rules'))
check('routes: /approval-requests', routes.includes('/approval-requests'))
check('routes: /risk-flags', routes.includes('/risk-flags'))
check('routes: /labor-insights', routes.includes('/labor-insights'))
check('routes: /labor-intelligence', routes.includes('/labor-intelligence'))
check('routes: /payroll-providers', routes.includes('/payroll-providers'))
check('routes: /offline-queue', routes.includes('/offline-queue'))
check('routes: canAccessPOS3 on write for shifts', routes.includes('canAccessPOS3') && routes.includes('createScheduledShift'))
check('routes: canAccessPOS3 on write for time-off decide', routes.includes('canAccessPOS3') && routes.includes('decideTimeOffRequest'))
check('routes: canAccessPOS3 on write for corrections', routes.includes('canAccessPOS3') && routes.includes('createTimeClockCorrection'))
check('routes: export default router', routes.includes('export default router'))

// UI
check('ui: DARK_BG token', ui.includes("'#080604'"))
check('ui: GOLD token', ui.includes("'#c9952c'"))
check('ui: DARK_CARD token', ui.includes("'#13110d'"))
check('ui: DARK_LINE token', ui.includes("'#2a2520'"))
check('ui: smokecraft-pos360.png reference 1', ui.includes('/smokecraft-pos360.png'))
check('ui: smokecraft-pos360.png reference 2', (ui.match(/smokecraft-pos360\.png/g) || []).length >= 2)
check('ui: Touchscreen Handheld Tablet Desktop header', ui.includes('Touchscreen · Handheld · Tablet · Desktop'))
check('ui: API base /api/pos360/staff', ui.includes('/api/pos360/staff'))
check('ui: HonestNote component', ui.includes('HonestNote'))
check('ui: HonestEmptyState component', ui.includes('HonestEmptyState'))
check('ui: StatusBadge component', ui.includes('StatusBadge'))
check('ui: localPreview state', ui.includes('localPreview'))
check('ui: payroll not connected honest note', ui.includes('Payroll provider is not connected'))
check('ui: labor cost placeholder note', ui.includes('Labor cost is a placeholder'))
check('ui: schedule notification not sent note', ui.includes('Schedule notification'))
check('ui: time clock local record note', ui.includes('local record'))
check('ui: EAT insights not connected note', ui.includes('E.A.T.') || ui.includes('E.A.T'))
check('ui: offline queue note', ui.includes('offline') || ui.includes('Offline'))
check('ui: tab Profiles', ui.includes("'Profiles'"))
check('ui: tab Roles', ui.includes("'Roles'"))
check('ui: tab Permissions', ui.includes("'Permissions'"))
check('ui: tab Shifts', ui.includes("'Shifts'"))
check('ui: tab Labor Summaries', ui.includes("'Labor Summaries'"))
check('ui: tab Governance', ui.includes("'Governance'"))
check('ui: tab Payroll', ui.includes("'Payroll'"))
check('ui: tab Offline Queue', ui.includes("'Offline Queue'"))
check('ui: default export POS360StaffLaborGovernance', ui.includes('export default function POS360StaffLaborGovernance'))

// Wiring
check('wiring: index.js imports staff routes', index.includes('pos360StaffLaborGovernanceRoutes'))
check('wiring: index.js mounts /api/pos360/staff', index.includes('/api/pos360/staff'))
check('wiring: App.jsx imports POS360StaffLaborGovernance', app.includes('POS360StaffLaborGovernance'))
check('wiring: App.jsx route staff-labor-governance', app.includes('staff-labor-governance'))
check('wiring: package.json verify script', pkg.includes('verify:pos360-staff-labor-governance'))

console.log(`\nPhase B.12 Verification: ${pass} passed, ${fail} failed`)
if (fail > 0) process.exit(1)
