/**
 * NOMPF — Initial Module Manifests (Draft)
 * These are draft manifests for the future NOVEE OS module build series.
 * Status: not_yet_packaged / needs_module_manifest
 * Do not claim any module is packaged or installed.
 */

import { createModuleManifest } from './moduleManifestSchema.js'

const DRAFT = {
  moduleStatus: 'not_yet_packaged',
  manifestNote: 'needs_module_manifest',
}

export function getInitialModuleManifests() {
  return [
    createModuleManifest({
      moduleId: 'smokecraft-experience',
      moduleName: 'SmokeCraft Experience Module',
      moduleSlug: 'smokecraft-experience',
      moduleType: 'experience_module',
      moduleCategory: 'hospitality',
      moduleDescription: 'SmokeCraft cigar experience — SmokeCraft journey, passport, connections, 8-visit/24-session progression, asset screens, hotspot layer.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'core',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: true,
      marketplaceEligible: true,
      dependencies: ['nompf-core'],
      requiredServices: ['smokecraftJourneyService', 'passportProgressService'],
      requiredComponents: ['SmokeCraftAssetScreen', 'SmokeCraftHotspotLayer', 'SmokeCraftAssetRoute'],
      pricingModel: 'per_venue',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'pos360',
      moduleName: 'POS360 Module',
      moduleSlug: 'pos360',
      moduleType: 'commerce_module',
      moduleCategory: 'commerce',
      moduleDescription: 'POS360 point-of-sale system — order management, table layout, staff routing, integrations hub.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'core',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: true,
      marketplaceEligible: true,
      dependencies: ['nompf-core'],
      requiredServices: ['pos360IntegrationService', 'orderLifecycleService'],
      pricingModel: 'per_venue',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'eat-command-hub',
      moduleName: 'E.A.T. Command Hub Module',
      moduleSlug: 'eat-command-hub',
      moduleType: 'operations_module',
      moduleCategory: 'operations',
      moduleDescription: 'E.A.T. (Experience, Analytics, Tracking) Command Hub — operational sync, hooks system, event contracts.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'core',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: false,
      dependencies: ['nompf-core', 'pos360'],
      requiredServices: ['eatCommandHubContract'],
      pricingModel: 'included',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'ispae',
      moduleName: 'Inventory Availability Module (ISPAE)',
      moduleSlug: 'ispae',
      moduleType: 'inventory_module',
      moduleCategory: 'inventory',
      moduleDescription: 'Inventory Sync and Product Availability Engine — real-time availability, depletion tracking, item pairing.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: true,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'pos360'],
      requiredServices: ['inventoryAvailabilityService', 'inventoryPersistenceService'],
      pricingModel: 'premium_addon',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'dmrc',
      moduleName: 'Reorder Connector Add-On Module (DMRC)',
      moduleSlug: 'dmrc',
      moduleType: 'connector_module',
      moduleCategory: 'inventory',
      moduleDescription: 'Distributor and Manufacturer Reorder Connector — purchase order drafts, reorder approval gate, vendor management.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'ispae'],
      requiredServices: ['reorderApprovalService', 'purchaseOrderSubmissionGateway'],
      requiredEnvVars: ['VENDOR_API_KEY', 'DISTRIBUTOR_API_KEY', 'MANUFACTURER_API_KEY'],
      pricingModel: 'premium_addon',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'locc',
      moduleName: 'Live Operations Command Center Module (LOCC)',
      moduleSlug: 'locc',
      moduleType: 'operations_module',
      moduleCategory: 'operations',
      moduleDescription: 'Live Operations Command Center — operations dashboard, role safety gateway, sync event monitoring.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'pos360'],
      requiredServices: ['operationsDashboardService'],
      pricingModel: 'enterprise_addon',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'eocg',
      moduleName: 'External Operations Connector Gateway Module (EOCG)',
      moduleSlug: 'eocg',
      moduleType: 'connector_module',
      moduleCategory: 'operations',
      moduleDescription: 'External Operations Connector Gateway — provider-neutral POS sync, external operational sync.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: false,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: false,
      dependencies: ['nompf-core', 'locc'],
      requiredServices: ['externalPOSConnectorGateway'],
      requiredEnvVars: ['EXTERNAL_POS_API_KEY'],
      pricingModel: 'enterprise_addon',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'venue-onboarding',
      moduleName: 'Venue Onboarding Module',
      moduleSlug: 'venue-onboarding',
      moduleType: 'management_module',
      moduleCategory: 'platform',
      moduleDescription: 'Venue setup, configuration, branding, and onboarding workflows.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'core',
      premiumEligible: false,
      enterpriseEligible: false,
      whiteLabelEligible: true,
      marketplaceEligible: false,
      dependencies: ['nompf-core'],
      requiredServices: ['venueOnboardingService'],
      pricingModel: 'included',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'partner-vendors',
      moduleName: 'Partner Vendor Module',
      moduleSlug: 'partner-vendors',
      moduleType: 'connector_module',
      moduleCategory: 'commerce',
      moduleDescription: 'Partner vendor onboarding, catalog management, and vendor relationship workflows.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: true,
      dependencies: ['nompf-core'],
      requiredServices: ['partnerVendorService'],
      pricingModel: 'per_venue',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'payments-checkout',
      moduleName: 'Payment / Checkout Module',
      moduleSlug: 'payments-checkout',
      moduleType: 'commerce_module',
      moduleCategory: 'commerce',
      moduleDescription: 'Stripe-powered checkout, tax compliance, payment intent management.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'core',
      premiumEligible: false,
      enterpriseEligible: false,
      whiteLabelEligible: true,
      marketplaceEligible: false,
      dependencies: ['nompf-core'],
      requiredServices: ['customerCheckoutService', 'stripeReadinessService'],
      requiredEnvVars: ['STRIPE_SECRET_KEY', 'VITE_STRIPE_PUBLISHABLE_KEY'],
      pricingModel: 'included',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'kds',
      moduleName: 'KDS Module',
      moduleSlug: 'kds',
      moduleType: 'operations_module',
      moduleCategory: 'operations',
      moduleDescription: 'Kitchen Display System — fulfillment routing, station management, order dispatch.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: true,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'pos360'],
      requiredServices: ['kdsRoutingService'],
      pricingModel: 'per_venue',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'ncie',
      moduleName: 'NCIE Module',
      moduleSlug: 'ncie',
      moduleType: 'intelligence_module',
      moduleCategory: 'intelligence',
      moduleDescription: 'NOVEE OS Customer Intelligence Engine — customer behavior, recommendations, intelligence hooks.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'pos360'],
      requiredServices: ['ncieWiringService'],
      pricingModel: 'enterprise_addon',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'passport-connections',
      moduleName: 'Passport Connections Module',
      moduleSlug: 'passport-connections',
      moduleType: 'experience_module',
      moduleCategory: 'hospitality',
      moduleDescription: 'Passport and connections loyalty tracking — visit progression, rewards, connection locking.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: true,
      enterpriseEligible: false,
      whiteLabelEligible: true,
      marketplaceEligible: true,
      dependencies: ['nompf-core', 'smokecraft-experience'],
      requiredServices: ['passportProgressService', 'passportEntryService'],
      pricingModel: 'per_venue',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'white-label-licensing',
      moduleName: 'White-Label Licensing Module',
      moduleSlug: 'white-label-licensing',
      moduleType: 'licensing_module',
      moduleCategory: 'licensing',
      moduleDescription: 'White-label licensing, tier enforcement, license gate, reseller access controls.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: false,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: false,
      dependencies: ['nompf-core'],
      requiredServices: ['whiteLabelLicensingReadinessService'],
      pricingModel: 'white_label_license',
      ...DRAFT,
    }),
    createModuleManifest({
      moduleId: 'marketplace-registry',
      moduleName: 'Marketplace Registry Module',
      moduleSlug: 'marketplace-registry',
      moduleType: 'marketplace_module',
      moduleCategory: 'marketplace',
      moduleDescription: 'NOVEE OS marketplace listing registry, module discovery, marketplace storefront foundation.',
      moduleVersion: '0.0.0',
      coreOrAddon: 'addon',
      premiumEligible: false,
      enterpriseEligible: true,
      whiteLabelEligible: false,
      marketplaceEligible: false,
      dependencies: ['nompf-core', 'white-label-licensing'],
      requiredServices: ['marketplacePackagingReadinessService'],
      pricingModel: 'enterprise_addon',
      ...DRAFT,
    }),
  ]
}
